#pragma once
/* Placeholder — regenerated by `make -f Makefile.casport cascas_host_offsets.h`. */
#define HOST_PORT_RAM_BASE  0xac200000u
#define HOST_PORT_RAM_SIZE  0x00132a6du
#define HOST_PORT_OFF_cascas_host_diff_run  0x000fca74u
#define HOST_PORT_OFF_cascas_host_integrate_run  0x000fcb84u
