REASONING_MARKERS = (
    "Use ",
    "Using ",
    "let ",
    "Let ",
    "hence",
    "so ",
    "therefore",
    "method:",
    "Method:",
    "substitute",
    "rearranged",
    "differentiate",
    "integrat",
    "expand",
    "factor ",
    "solve ",
    "rule",
    "equation:",
    "original equation:",
    "identity:",
    "LHS:",
    "RHS:",
    "Hence ",
    "Therefore ",
    "Thus ",
    "final =",
    "Final =",
    "result:",
    "Result:",
    "answer:",
    "Answer:",
    "working:",
    "Attempt ",
    "Tried ",
    "Given:",
)
