#!/usr/bin/env python3
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[1]
HOST = Path("/tmp/cscalc_engine_host")


def build():
    subprocess.check_call([
        "g++", "-std=c++11", "-Wall", "-Wextra", "-Wno-unused-function", "-Itools",
        "tools/cscalc_engine.cpp", "tools/cscalc_engine_host.cpp",
        "-o", str(HOST),
    ], cwd=ROOT)


def run(expr):
    return subprocess.check_output([str(HOST), expr], cwd=ROOT, text=True)


def require(expr, needles):
    out = run(expr)
    for needle in needles:
        if needle not in out:
            raise SystemExit(f"{expr!r} missing {needle!r}\n{out}")
    for bad in ["Verified", "not checked", "syntax error", "Bad Argument"]:
        if bad in out:
            raise SystemExit(f"{expr!r} contains banned {bad!r}\n{out}")


def main():
    build()
    require("bin(45)", ["Repeated division", "45_10"])
    require("hex(45)", ["45_10", "2D_16"])
    require("den(2D,16)", ["place value", "45_10"])
    require("convert(101101,2,16)", ["101101_2 = 45_10", "45_10 = 2D_16"])
    require("bitsneeded(150,unsigned)", ["minimum unsigned", "8 bits"])
    require("unsignedrange(8)", ["unsigned range", "0 to 255"])
    require("twosrange(8)", ["two's complement range", "-128 to 127"])
    require("signmagrange(8)", ["sign-and-magnitude range"])
    require("onesrange(8)", ["one's complement range"])
    require("twos(-5,8)", ["8-bit two's complement", "11111011"])
    require("twosdec(11111011)", ["subtract 2^8", "-5"])
    require("signmag(-5,8)", ["sign-and-magnitude", "10000101"])
    require("signmagdec(10000101)", ["first bit is sign", "-5"])
    require("ones(-5,8)", ["one's complement", "11111010"])
    require("onesdec(11111010)", ["One's complement", "-5"])
    require("twosadd(11111011,00000011,8)", ["Decode/add", "-5+3=-2"])
    require("twossub(00000101,00001001,8)", ["Subtraction", "5-9=-4"])
    require("binadd(1011,0110,4)", ["Add from the right", "1011 + 0110 = 0001"])
    require("binsub(1011,0110,4)", ["binary subtraction", "result"])
    require("shift(00101100,left,2)", ["left shift", "10110000"])
    require("arithshift(11101100,right,2)", ["preserve the sign bit", "11111011"])
    require("parity(1011001,even)", ["Even parity", "parity bit"])
    require("repeatenc(101,3)", ["repeat each data bit", "111000111"])
    require("repeatdec(111000111,3)", ["split into groups", "decoded"])
    require("xorbits(1010,1100)", ["XOR", "0110"])
    require("andbits(1010,1100)", ["AND", "1000"])
    require("orbits(1010,1100)", ["OR", "1110"])
    require("notbits(1010)", ["NOT", "0101"])
    require("grayenc(1011)", ["Gray code", "1110"])
    require("graydec(1110)", ["Gray to binary", "1011"])
    require("hamming(1010,1111)", ["Hamming distance", "2"])
    require("hammingenc(1011)", ["Hamming(7,4)", "code word"])
    require("checksum(173,8)", ["Checksum", "checksum ="])
    require("rpn(3,4,+,2,*)", ["RPN", "answer"])
    require("binarysearch(7,1,3,5,7,9)", ["Binary search", "found"])
    require("linearsearch(7,4,7,1,9)", ["Linear search", "found"])
    require("bubblesort(5,1,4,2)", ["Bubble sort", "[1,2,4,5]"])
    require("insertionsort(5,1,4,2)", ["Insertion sort", "[1,2,4,5]"])
    require("selectionsort(5,1,4,2)", ["Selection sort", "[1,2,4,5]"])
    require("mergesort(5,1,4,2)", ["Merge sort", "[1,2,4,5]"])
    require("stack(3,4,pop,5)", ["Stack is LIFO", "push 5"])
    require("queue(3,4,pop,5)", ["Queue is FIFO", "enqueue 5"])
    require("preorder(A,B,C,D,E)", ["Pre-order"])
    require("inorder(A,B,C,D,E)", ["In-order"])
    require("postorder(A,B,C,D,E)", ["Post-order"])
    require("dijkstra(A,D,A,B,4,A,C,2,B,D,3,C,D,5)", ["Dijkstra", "shortest path"])
    require("fixed(101.101)", ["fixed-point", "5.625"])
    require("fixedtc(1101.10)", ["two's complement", "-2.5"])
    require("fixedenc(5.625,3,3)", ["Encode fixed point", "101.101"])
    require("fixedfrac(0.375,4)", ["fixed point", "0.0110"])
    require("fixedtcenc(-2.5,4,3)", ["two's-complement scaled integer", "1101.100"])
    require("floatdec(0101100,11101)", ["mantissa", "exponent", "value"])
    require("floatnorm(00011010,0110)", ["Normalise", "mantissa"])
    require("normal(0101100)", ["normalised"])
    require("floatenc(12.75,8,4)", ["Normalise", "mantissa"])
    require("floatrange(8,4)", ["Exponent", "largest positive"])
    require("floatprecision(8,3)", ["Precision", "step"])
    require("floatnearest(0.1,8,4)", ["closest", "representable"])
    require("floatcanrepresent(500,8,4)", ["representability", "too large"])
    require("floatadd(1.5,2.25,8,4)", ["Add floating-point numbers", "normalise"])
    require("image(800,600,24)", ["Image bits", "11520000 bits"])
    require("imagecolors(800,600,256)", ["colour depth", "bits"])
    require("colourdepth(256)", ["2^b", "8 bits"])
    require("colourcount(8)", ["colours", "256"])
    require("sound(44100,60,16,2)", ["Sound bits", "84672000 bits"])
    require("bitrate(48000000,12)", ["Bit rate", "bit/s"])
    require("bitratemb(12,8)", ["MB", "Mbit/s"])
    require("transfer(48000000,4000000)", ["Transfer time", "12 s"])
    require("ascii(65)", ["ASCII", "A"])
    require("unicode(8364)", ["Unicode"])
    require("chars(120,8)", ["Text bits", "960 bits"])
    require("charset(96,7)", ["character set"])
    require("symbolbits(130)", ["Need 2^b", "8 bits"])
    require("compress(1000,250)", ["Compression ratio", "4"])
    require("dictcompress(8000,300,5,700)", ["Dictionary compression"])
    require("rle(12,8,4)", ["Run-length bits", "144 bits"])
    require("huffman(A,5,1,B,2,3,C,1,3)", ["Huffman"])
    require("records(1200,32)", ["records", "38400"])
    require("addressspace(16)", ["2^16"])
    require("addressbits(65536)", ["ceil", "16 bits"])
    require("memorycapacity(16,8)", ["capacity"])
    require("hashmod(10,27,18,29)", ["key mod table size", "27 mod 10 = 7"])
    require("bool(A+B)", ["Group cells", "simplified"])
    require("bool_simplify(A+A)", ["Using: A+A", "2. A    (Tautology)", "Result: A"])
    require("bool_simplify(A nand B)", ["NAND identity", "Result: A,+B,"])
    require("bool_simplify(A nor B)", ["NOR identity", "Result: A,.B,"])
    require("bool_simplify(A implies B)", ["Implication identity", "Result: A,+B"])
    require("bool_simplify(A*B + A*B' + A'*B)", ["Truth table: 1-rows 1,2,3", "K-map grouping", "Result: A+B"])
    require("bool_simplify(A and not A)", ["Tautology", "Result: 0"])
    require("bool_simplify(A or not A)", ["Tautology", "Result: 1"])
    require("bool_simplify(A*B + A*B' + A*C)", ["K-map grouping", "Result: A"])
    require("bool_simplify(A*B+A'*C+B*C)", ["Consensus", "Result: A.B+A,.C"])
    require("bool_simplify((A+B)*(A+C))", ["Distributive", "Result: A+B.C"])
    require("bool_simplify(A*(B+C))", ["Expansion of brackets", "Result: A.B+A.C"])
    require("bool_simplify(not(not A and not B))", ["De Morgan's law", "Result: A+B"])
    require("bool_simplify((not A and not B) or (A and not B))", ["K-map grouping", "Result: B,"])
    require("bool_simplify(A*(B'+0)+A'*(B+B))", ["Common sense", "Result: A.B,+A,.B"])
    require("bool_simplify(A*B*C+A*B*C'+A*B)", ["K-map grouping", "Result: AB"])
    require("bool_simplify((E*F)+(E*G))", ["Distributive", "Result: E.(F+G)"])
    require("bool_simplify((A+C)*(A*B)+(C*B))", ["K-map grouping", "Result: AB+CB"])
    require("bool_simplify(B*A*(B+A)*A+C*1)", ["Common sense", "K-map grouping", "Result: BA+C"])
    require("bool_simplify(A*(A+C)*B*(B+C)+A)", ["Absorption", "Result: A"])
    require("bool_simplify(A+B*B')", ["Tautology", "Result: A"])
    require("bool_simplify((A+B)*(A+B'))", ["K-map grouping", "Result: A"])
    require("boolprove((A+B)*(A+C),A+B*C)", ["LHS simplifies to A+BC", "Same output rows"])
    require("bool_simplify((A+B),)", ["Using: (A+B),", "De Morgan's law", "Result: A,.B,"])
    require("bool_simplify(A+A*B)", ["Using: A+A.B", "Absorption", "Result: A"])
    require("bool(A,,)", ["simplified = A"])
    require("bool(A,,,)", ["simplified = A'"])
    require("bool(A+0)", ["Identity law", "simplified = A"])
    require("bool(A*1)", ["Identity law", "simplified = A"])
    require("bool(A+A)", ["Idempotent law", "simplified = A"])
    require("bool(A*A)", ["Idempotent law", "simplified = A"])
    require("bool(A+A')", ["Complement law", "simplified = 1"])
    require("bool(A*A')", ["Complement law", "simplified = 0"])
    require("bool(ABC)", ["simplified = ABC"])
    require("truth(A+B)", ["Truth table for A+B.", "simplified = A+B"])
    require("bool((A&B)')", ["De Morgan's law", "group", "simplified = A'+B'"])
    require("bool((A+B)')", ["De Morgan's law", "simplified = A'B'"])
    require("bool(A+A*B)", ["Absorption law", "group"])
    require("bool(A*B+A'*C+B*C)", ["Consensus theorem", "simplified"])
    require("bool((A+B)*(A+C))", ["Distributive law", "simplified = A+BC"])
    require("truth(A and B)", ["Truth table"])
    require("truthbits(A,B,0110)", ["Truth-table output-column", "output bits", "Group cells"])
    require("minterms(1,3,5,7)", ["minterms"])
    require("maxterms(0,2,4,6)", ["Maxterm"])
    require("kmap(1,3,5,7)", ["K-map", "simplified"])
    require("kmapdc(1,3,7,5)", ["K-map", "simplified"])
    require("posform(A+B)", ["POS"])
    require("nandform(A+B)", ["NAND"])
    require("norform(A+B)", ["NOR"])
    require("convert decimal 45 to binary", ["Supported:"])
    print("OK cscalc command engine")


if __name__ == "__main__":
    main()
