#!/usr/bin/env python3
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[1]
HOST = Path("/tmp/cscalc_engine_host")


def build():
    subprocess.check_call([
        "g++", "-std=c++11", "-Wall", "-Wextra", "-Itools",
        "tools/cscalc_engine.cpp", "tools/cscalc_engine_host.cpp",
        "-o", str(HOST),
    ], cwd=ROOT)


def run(expr):
    return subprocess.check_output([str(HOST), expr], cwd=ROOT, text=True)


def require(expr, needles):
    out = run(expr)
    for needle in needles:
        if needle not in out:
            raise SystemExit(f"{expr!r} missing {needle!r}\n{out}")
    banned = ["Verified", "not checked", "syntax error", "Bad Argument"]
    for bad in banned:
        if bad in out:
            raise SystemExit(f"{expr!r} contains banned {bad!r}\n{out}")
    return out


def main():
    build()
    require("bin(45)", ["Repeated division", "45_10"])
    require("binary(45)", ["Repeated division", "45_10"])
    require("convert 45 to binary", ["Repeated division", "45_10"])
    require("den(101101,2)", ["place value", "45_10"])
    require("convert 101101 binary to denary", ["place value", "45_10"])
    require("101101", ["Bare 0/1 input", "45_10"])
    require("bitsneeded(150,unsigned)", ["minimum unsigned binary width", "Need 0 <= 150 <= 2^n-1", "8 bits are needed"])
    require("minimum bits needed to represent denary 150 unsigned binary", ["minimum unsigned binary width", "range 0 to 255", "8 bits are needed"])
    require("twos(-5,8)", ["8-bit", "11111011"])
    require("convert denary -13 to 8 bit two complement binary", ["8-bit two's complement", "-13 -> 11110011"])
    require("twosdec(11111011)", ["subtract 2^8", "-5"])
    require("bitsneeded(-45,twos)", ["minimum two's-complement width", "-2^(n-1) <= -45", "7 bits are needed"])
    require("minimum bits needed to represent -45 in two's complement", ["minimum two's-complement width", "range -64 to 63", "7 bits are needed"])
    require("unsignedrange(8)", ["unsigned range", "0 to 255"])
    require("8-bit two's complement range", ["two's complement range", "-128 to 127"])
    require("decode 11111011 as two's complement", ["subtract 2^8", "-5"])
    require("signmag(-5,8)", ["8-bit sign-and-magnitude", "sign bit = 1", "magnitude = |-5| = 5", "10000101"])
    require("signmagdec(10000101)", ["first bit is sign", "magnitude bits 0000101 = 5", "10000101 = -5"])
    require("bitsneeded(-45,signmag)", ["minimum sign-and-magnitude width", "1 sign bit", "total bits = 7"])
    require("fewest bits for -45 sign magnitude", ["minimum sign-and-magnitude width", "m = 6", "total bits = 7"])
    require("8-bit sign magnitude range", ["sign-and-magnitude range", "-127 to 127", "+0 and -0"])
    require("decode 10000101 as sign magnitude", ["first bit is sign", "10000101 = -5"])
    require("encode -5 as sign magnitude 8 bit", ["8-bit sign-and-magnitude", "10000101"])
    require("twosadd(01111111,00000001)", ["127+1=128", "overflow"])
    require("twossub(00000101,00000011)", ["Subtraction", "two's complement of second value = 11111101", "00000101 + 11111101 = 00000010", "5-3=2"])
    require("subtract 00000011 from 00000101 using two's complement", ["Subtraction", "two's complement of second value = 11111101", "5-3=2"])
    require("add 01111111 and 00000001 using two's complement", ["Decode/add", "127+1=128", "overflow"])
    require("binadd(1011,0110,4)", ["carrying", "0001", "overflow"])
    require("shift(00101100,left,2)", ["left shift", "10110000"])
    require("arithshift(11110000,right,2)", ["preserve the sign bit", "11110000 = -16", "11111100 = -4"])
    require("arithmetic right shift 11110000 by 2", ["preserve the sign bit", "11111100 = -4"])
    require("arithshift(01000000,left,1)", ["Arithmetic left shift", "10000000 = -128", "overflow risk"])
    require("parity(1011001,even)", ["Even parity", "has 4 one-bits", "parity bit = 0"])
    require("odd parity bit for 1011001", ["Odd parity", "has 4 one-bits", "parity bit = 1"])
    require("repeatenc(101,3)", ["Repetition code", "repeat each data bit 3 times", "transmitted bits = 111000111"])
    require("repeatdec(111000101,3)", ["majority voting", "101: 2 ones, 1 zeros -> 1", "decoded data bits = 101", "errors corrected"])
    require("decode repetition code 111000101 in groups of 3", ["split into groups of 3", "decoded data bits = 101"])
    require("encode 101 using repetition code group size 3", ["repeat each data bit 3 times", "transmitted bits = 111000111"])
    require("xorbits(10101100,11001010)", ["XOR gives 1", "result = 01100110"])
    require("xor 10101100 11001010", ["XOR gives 1", "01100110"])
    require("andbits(10101100,11001010)", ["AND gives 1", "result = 10001000"])
    require("orbits(10101100,11001010)", ["OR gives 1", "result = 11101110"])
    require("notbits(10101100)", ["NOT flips", "01010011"])
    require("invert bits 10101100", ["NOT flips", "01010011"])
    require("hamming(101101,111001)", ["Hamming distance", "different positions", "distance = 2"])
    require("hamming distance between 101101 and 111001", ["Hamming distance", "distance = 2"])
    require("checksum(8,00110011,01010101)", ["Checksum", "decimal sum = 136", "10001000"])
    require("checksum for 00110011 01010101", ["Checksum", "10001000"])
    require("checkdigit(12345,11,6,5,4,3,2)", ["weighted modulo", "sum = 50", "remainder", "mod 11 = 5"])
    require("check digit for 12345 weights 6 5 4 3 2 mod 11", ["weighted modulo", "sum = 50", "mod 11 = 5"])
    require("rpn(3,4,+,5,*)", ["postfix/RPN", "3 + 4 = 7", "7 * 5 = 35", "answer = 35"])
    require("evaluate RPN 3 4 + 5 *", ["postfix/RPN", "3 + 4 = 7", "answer = 35"])
    require("postfix 10 2 divide 3 plus", ["10 / 2 = 5", "5 + 3 = 8", "answer = 8"])
    require("binarysearch(7,1,3,5,7,9)", ["Binary search", "mid=3 value=5 -> right", "found at position 4"])
    require("binary search for 7 in 1 3 5 7 9", ["Binary search", "found at position 4"])
    require("linearsearch(5,8,3,5,2)", ["Linear search", "position 3: 5 = target", "found at position 3"])
    require("bubblesort(5,1,4,2)", ["Bubble sort", "start [5,1,4,2]", "pass 1: [1,4,2,5]", "pass 3: [1,2,4,5]"])
    require("insertion sort 5 1 4 2", ["Insertion sort", "insert 1: [1,5,4,2]", "insert 2: [1,2,4,5]"])
    require("selectionsort(5,1,4,2)", ["Selection sort", "place 1 at position 1: [1,5,4,2]", "place 2 at position 2: [1,2,4,5]"])
    require("merge sort 5 1 4 2", ["Merge sort", "merge runs of 1: [1,5,2,4]", "merge runs of 2: [1,2,4,5]"])
    require("stack(3,4,pop,5)", ["Stack is LIFO", "push 3 -> stack [3]", "pop 4 -> stack [3]", "push 5 -> stack [3,5]"])
    require("stack push 3 push 4 pop push 5", ["Stack is LIFO", "pop 4 -> stack [3]", "push 5 -> stack [3,5]"])
    require("queue(3,4,pop,5)", ["Queue is FIFO", "enqueue 3 -> queue [3]", "dequeue 3 -> queue [4]", "enqueue 5 -> queue [4,5]"])
    require("queue enqueue 3 enqueue 4 dequeue enqueue 5", ["Queue is FIFO", "dequeue 3 -> queue [4]", "enqueue 5 -> queue [4,5]"])
    require("preorder(a,b,c,d,e,f,g)", ["level-order input", "Pre-order traversal uses root, left, right", "Pre-order: a,b,d,e,c,f,g"])
    require("inorder(a,b,c,d,e,f,g)", ["In-order traversal uses left, root, right", "In-order: d,b,e,a,f,c,g"])
    require("postorder(a,b,c,d,e,f,g)", ["Post-order traversal uses left, right, root", "Post-order: d,e,b,f,g,c,a"])
    require("preorder tree traversal nodes A B C D E F G", ["Pre-order", "a,b,d,e,c,f,g"])
    require("preordertree(a,a,b,c,b,d,e,c,none,f,d,none,none,e,none,none,f,none,none)", ["explicit binary-tree links", "root = a", "Pre-order: a,b,d,e,c,f"])
    require("inordertree(a,a,b,c,b,d,e,c,none,f,d,none,none,e,none,none,f,none,none)", ["In-order traversal uses left, root, right", "In-order: d,b,e,a,c,f"])
    require("postorder tree root A left right triples A B C B D E C none F D none none E none none F none none", ["explicit binary-tree links", "Post-order: d,e,b,f,c,a"])
    require("dijkstra(a,d,a,b,4,a,c,2,c,b,1,b,d,5,c,d,8)", ["Dijkstra", "fix a at 0", "a->c: 0+2=2, update", "shortest path: a->c->b->d", "distance = 8"])
    require("shortest path from A to D edges A B 4 A C 2 C B 1 B D 5 C D 8", ["Dijkstra", "shortest path: a->c->b->d", "distance = 8"])
    require("fsm(s0,1011,s0,0,s0,s0,1,s1,s1,0,s0,s1,1,s1)", ["finite state machine", "start state = s0", "read 1: s0 --1--> s1", "final state = s1"])
    require("finite state machine start s0 input 1011 transitions s0 0 s0 s0 1 s1 s1 0 s0 s1 1 s1", ["finite state machine", "read 0: s1 --0--> s0", "final state = s1"])
    require("fsmout(a,101,a,0,a,0,a,1,b,1,b,0,a,1,b,1,b,0)", ["with outputs", "read 1: a --1/1--> b", "output = 111"])
    require("mealy finite state machine start a input 101 output transitions a 0 a 0 a 1 b 1 b 0 a 1 b 1 b 0", ["with outputs", "output = 111"])
    require("fixed(101.101)", ["place values", "5.625"])
    require("fixed point 101.101", ["place values", "5.625"])
    require("fixedtc(111.01)", ["two's complement", "-0.75"])
    require("fixed two's complement 111.01", ["two's complement", "-0.75"])
    require("fixedenc(5.625,3,3)", ["scaling by 2^fraction bits", "fixed point = 101.101"])
    require("fixed point encode 5.625 with 3 whole bits and 3 fractional bits", ["scaled integer", "fixed point = 101.101"])
    require("fixedfrac(12.375,4)", ["whole bits needed for 12.375 = 4", "fixed point = 1100.0110"])
    require("convert the decimal number 12.375 to fixed point binary with 4 fractional bits", ["scale by 2^fraction bits", "1100.0110"])
    require("fixedtcenc(-0.75,3,2)", ["two's-complement scaled integer", "fixed point = 111.01"])
    require("signed fixed point encode -0.75 with 3 whole bits and 2 fractional bits", ["two's-complement scaled integer", "fixed point = 111.01"])
    require("floatdec(0101100,11101)", ["mantissa", "exponent", "0.0859375"])
    require("floatenc(12.75,8,4)", ["Normalise", "mantissa", "exponent"])
    require("floatdecode(0101100,11101)", ["mantissa", "exponent"])
    require("mantissa 0101100 exponent 11101", ["mantissa", "exponent", "0.0859375"])
    require("floatnorm(00011010,0110)", ["first two mantissa bits differ", "shift mantissa left 2", "mantissa = 01101000", "exponent = 0100"])
    require("normalise mantissa 00011010 exponent 0110", ["shift mantissa left 2", "mantissa = 01101000"])
    require("floating point encode -608 with 7 bit mantissa and 5 bit exponent", ["Normalise", "mantissa (7 bits)", "exponent (5 bits)"])
    require("floatadd(01000000,0010,00100000,0010)", ["aligning exponents", "use common exponent 2", "mantissas: 0.5 + 0.25 = 0.75", "mantissa (8 bits) = 01100000", "exponent (4 bits) = 0010"])
    require("floatsub(01000000,0010,00100000,0010)", ["aligning exponents", "mantissas: 0.5 - 0.25 = 0.25", "normalise: 0.5 * 2^1", "exponent (4 bits) = 0001"])
    require("add floating point mantissa 01000000 exponent 0010 mantissa 00100000 exponent 0010", ["Add floating-point", "mantissa (8 bits) = 01100000"])
    require("subtract floating point mantissa 01000000 exponent 0010 mantissa 00100000 exponent 0010", ["Subtract floating-point", "exponent (4 bits) = 0001"])
    require("floatmul(01000000,0010,01000000,0001)", ["multiply mantissas and add exponents", "mantissas: 0.5 * 0.5 = 0.25", "exponents: 2 + 1 = 3", "normalise: 0.5 * 2^2", "exponent (4 bits) = 0010"])
    require("floatdiv(01000000,0010,01000000,0001)", ["divide mantissas and subtract exponents", "mantissas: 0.5 / 0.5 = 1", "exponents: 2 - 1 = 1", "normalise: 0.5 * 2^2", "exponent (4 bits) = 0010"])
    require("multiply floating point mantissa 01000000 exponent 0010 mantissa 01000000 exponent 0001", ["Multiply floating-point", "mantissa (8 bits) = 01000000"])
    require("divide floating point mantissa 01000000 exponent 0010 mantissa 01000000 exponent 0001", ["Divide floating-point", "normalise: 0.5 * 2^2"])
    require("floatprecision(8,4)", ["last mantissa bit", "2^(4-(8-1))", "0.125"])
    require("floating point precision mantissa 8 exponent 4", ["last mantissa bit", "0.125"])
    require("floatnearest(12.7,8,4)", ["closest representable", "step at this exponent", "nearest multiple = 12.75", "mantissa (8 bits)", "exponent (4 bits)"])
    require("closest representable floating point value 12.7 with 8 bit mantissa and 4 bit exponent", ["closest representable", "nearest multiple = 12.75"])
    require("floatbitsadd(12.765625,8,4)", ["mantissa precision", "current step", "exact step", "extra mantissa bits needed = 3"])
    require("smallest number of bits added to mantissa so decimal 12.765625 is exact with 8 bit mantissa and 4 bit exponent", ["mantissa precision", "extra mantissa bits needed = 3"])
    require("floatrange(8,4)", ["exponent range", "mantissa step", "largest positive"])
    require("floating point range with 8 bit mantissa and 4 bit exponent", ["exponent range", "largest positive"])
    require("normal(0101100)", ["Normalised", "is normalised"])
    require("image(1920,1080,24)", ["width * height", "49766400 bits", "MB"])
    require("bitmap image 1920 x 1080 with 24 bit colour", ["width * height", "49766400 bits"])
    require("bitmap image width=1920 height=1080 depth=24", ["width * height", "49766400 bits"])
    require("imagecolors(100,50,16)", ["ceil(log2(16)) = 4", "20000 bits"])
    require("bitmap image 100 x 50 with 16 colours", ["ceil(log2(16)) = 4", "20000 bits"])
    require("bitmap image width=100 height=50 colours=16", ["ceil(log2(16)) = 4", "20000 bits"])
    require("sound(44100,60,16,2)", ["sample rate", "84672000 bits", "MB"])
    require("audio duration=60 channels=2 resolution=16 sample rate=44100", ["Sound bits", "84672000 bits", "MB"])
    require("calculate file size for a sound sample sampled at 44100 Hz for 30 seconds using 16 bit resolution stereo", ["44100*30*16*2", "42336000 bits"])
    require("calculate file size for a sound file sampled at 44.1 kHz for 2 minutes using 16 bit resolution stereo", ["44100*120*16*2", "169344000 bits"])
    require("transfer time for 8000 bits at 2000 bit/s", ["Transfer time", "4 s"])
    require("bitratemb(12,6)", ["12 MB = 96 Mbit", "bit rate = 96/6 = 16 Mbit/s"])
    require("bit rate for file size 12 megabytes transmitted in 6 seconds", ["12 MB = 96 Mbit", "16 Mbit/s"])
    require("bit rate for file size 12 megabytes transmitted in 2 minutes", ["12 MB = 96 Mbit", "bit rate = 96/120 = 0.8 Mbit/s"])
    require("bitratekb(500,2)", ["500 KB = 4000 kbit", "2000 kbit/s"])
    require("transfermb(10,2)", ["10 MB = 80 Mbit", "time = 80/2 = 40 s"])
    require("download time for 10 megabytes at 2 megabits per second", ["Convert megabytes", "10 MB = 80 Mbit", "40 s"])
    require("download time file size=10 megabytes bitrate=2 megabits per second", ["Convert megabytes", "10 MB = 80 Mbit", "40 s"])
    require("compress(1200,300)", ["ratio = 4", "saving = 75"])
    require("compression compressed=300 original=1200", ["ratio = 4", "saving = 75"])
    require("dictcompress(1200,200,50,8)", ["Dictionary compression size", "reference bits = 50*8 = 400", "compressed bits = 200 + 400 = 600", "saving = 50"])
    require("dictionary compression original 1200 dictionary 200 references 50 reference bits 8", ["Dictionary compression size", "compressed bits = 200 + 400 = 600"])
    require("dictionary compression references=50 original=1200 reference bits=8 dictionary=200", ["Dictionary compression size", "compressed bits = 200 + 400 = 600"])
    require("huffman(a45,b13,c12,d16,e9,f5)", ["combine two smallest", "F(5)+E(9)=14", "code lengths", "encoded bits = sum(freq*length) = 224", "fixed length = 100*3 = 300 bits"])
    require("huffman frequencies 45 13 12 16 9 5", ["combine two smallest", "encoded bits = sum(freq*length) = 224"])
    require("rle(12,8,4)", ["Run-length bits", "144 bits"])
    require("run length encoding 12 runs 8 symbol bits 4 count bits", ["Run-length bits", "144 bits"])
    require("run length encoding count bits=4 runs=12 symbol bits=8", ["Run-length bits", "144 bits"])
    require("rletext(aaabcccc,8,4)", ["consecutive repeated", "runs: ax3,bx1,cx4", "original bits = 8*8", "encoded bits = 3*(8+4)"])
    require("run length encode aaabcccc with 8 symbol bits and 4 count bits", ["consecutive repeated", "runs: ax3,bx1,cx4", "encoded bits = 3*(8+4)"])
    require("records(120,32)", ["records * bytes", "3840 bytes"])
    require("database file 120 records 32 bytes per record", ["records * bytes", "3840 bytes"])
    require("database records=120 bytes per record=32", ["records * bytes", "3840 bytes"])
    require("sqlselect(students,name,age,>,16)", ["SQL SELECT", "SELECT name", "FROM students", "WHERE age > 16"])
    require("sql select name from students where age greater than 16", ["SQL SELECT", "SELECT name", "WHERE age > 16"])
    require("sqlcount(students,age,>=,18)", ["SQL COUNT", "SELECT COUNT(*)", "WHERE age >= 18"])
    require("count records from students where age at least 18", ["SQL COUNT", "WHERE age >= 18"])
    require("addressspace(16)", ["Addressable locations", "2^16 = 65536 addresses"])
    require("16 bit address bus addressable locations", ["Addressable locations", "65536 addresses"])
    require("addressbits(4294967296,8)", ["locations = 4294967296*8/8", "32 bits"])
    require("how many address bits are needed to address 4 GB of memory", ["ceil(log2(addressable locations))", "32 bits"])
    require("memorycapacity(16,8)", ["Memory capacity", "locations = 2^16 = 65536", "524288", "65536 bytes"])
    require("16 bit address bus with 8 bit words memory capacity", ["Memory capacity", "65536 bytes"])
    require("hashmod(10,27,18,29,37)", ["Hash address = key mod table size", "27 mod 10 = 7", "37 mod 10 = 7, collision"])
    require("hash table size 10 keys 27 18 29 37", ["Hash address = key mod table size", "29 mod 10 = 9", "collision"])
    require("hashlinear(10,27,18,29,37)", ["linear probing", "27 mod 10 = 7, place at 7", "37 mod 10 = 7 occupied; probe 3, place at 0"])
    require("hash table size 10 linear probing keys 27 18 29 37", ["linear probing", "place at 0"])
    require("chars(120,8)", ["characters", "960 bits", "MB"])
    require("text characters=120 bits per character=8", ["characters", "960 bits"])
    require("charset(120,128)", ["ceil(log2(128)) = 7", "text bits = 120*7"])
    require("text characters=120 character set=128", ["ceil(log2(128)) = 7", "840 bits"])
    require("store 120 characters from character set of 128 symbols", ["ceil(log2(128)) = 7", "840 bits"])
    require("ascii(65)", ["ASCII code conversion", "ASCII code 65 represents 'A'", "01000001_2 = 41_16"])
    require("ASCII code for A", ["ASCII code conversion", "'A' has denary code 65", "01000001_2 = 41_16"])
    require("unicode code point 8364", ["Unicode code point conversion", "U+20AC = 8364_10", "0010000010101100_2"])
    require("bool(A+B')", ["truth table", "minterms", "simplified"])
    require("truth(A and not B)", ["Truth table for a&!b", "A B | F", "0 0 | 0", "1 0 | 1", "minterms: 2"])
    require("truth table for A and not B", ["Truth table for a&!b", "A B | F", "1 0 | 1", "simplified = AB'"])
    require("boolean(AB+C)", ["truth table", "simplified"])
    require("bool(A and not B)", ["truth table", "simplified = AB'"])
    require("A and not B", ["truth table", "simplified = AB'"])
    require("simplify A and not B", ["truth table", "simplified = AB'"])
    require("simplify boolean expression A and not B", ["truth table", "simplified = AB'"])
    require("bool(A+A)", ["Boolean algebra", "Idempotent law", "simplified = A"])
    require("simplify A + A B", ["Boolean algebra", "Absorption law", "simplified = A"])
    require("bool(A+A')", ["Boolean algebra", "Complement law", "simplified = 1"])
    require("bool((A+A')B)", ["Boolean algebra", "Complement law", "1&b -> b", "simplified = B"])
    require("bool((A+0)(B+1))", ["Boolean algebra", "Identity law", "Dominance law", "a&1 -> a", "simplified = A"])
    require("bool(A+A'B)", ["Boolean algebra", "Covering law", "a+b", "simplified"])
    require("bool(A(A'+B))", ["Boolean algebra", "Covering law", "a&b", "simplified = AB"])
    require("bool(not(A and B))", ["Boolean algebra", "De Morgan", "simplified"])
    require("bool(A B + A C)", ["Boolean algebra", "Distributive law", "a&(b+c)", "simplified"])
    require("bool((A+B)(A+C))", ["Boolean algebra", "Distributive law", "a+b&c", "simplified"])
    require("bool((A+B)(A+B+C))", ["Boolean algebra", "Absorption law", "a+b", "simplified"])
    require("bool(A xor B)", ["Boolean algebra", "XOR identity", "a'&b+a&b'", "simplified"])
    require("bool(A^B)", ["Boolean algebra", "XOR identity", "a'&b+a&b'", "simplified"])
    require("bool(A nand B)", ["truth table", "simplified = A'+B'"])
    require("bool(A&B'+A'&B)", ["minterms: 1,2", "simplified = A'B+AB'"])
    require("bool(A'B+AB')", ["minterms: 1,2", "simplified = A'B+AB'"])
    require("bool(A&B+A'&C+B&C)", ["Boolean algebra", "Consensus theorem", "a&b+a'&c", "simplified"])
    require("simplify A B + A' C + B C", ["Consensus theorem", "simplified"])
    require("minterms(A,B,1,2)", ["K-map/minterm method", "variables: A,B", "m1 = A'&B", "m2 = A&B'", "simplified = A'B+AB'"])
    require("kmap(A,B,C,1,3,5,7)", ["K-map/minterm method", "m1 = A'&B'&C", "simplified = C"])
    require("maxterms(A,B,0,3)", ["Maxterm/POS method", "M0 = (A+B)", "M3 = (A'+B')", "POS = (A+B)&(A'+B')", "simplified = A'B+AB'"])
    require("kmapdc(A,B,C,1,3,dc,5,7)", ["K-map/minterm method", "m1 = A'&B'&C", "don't-care rows: 5,7", "Use don't-cares only if they make larger groups", "simplified = C"])
    require("maxterms(A,B,C,0,2,dc,4,6)", ["Maxterm/POS method", "don't-care rows: 4,6", "Use don't-cares only if they make larger zero groups", "simplified POS = (C)"])
    require("posform(A+B)", ["Product-of-sums method", "zero rows: 0", "M0 = (A+B)", "simplified POS = (A+B)"])
    require("posform(A&B')", ["Product-of-sums method", "zero rows:", "POS =", "simplified POS"])
    require("truthbits(A,B,0110)", ["Truth-table output-column method", "variables: A,B", "1-cells/minterms: 1,2", "SOP = A'&B+A&B'", "simplified SOP = A'B+AB'", "simplified POS"])
    require("truth table output bits 0110", ["Truth-table output-column method", "variables: A,B", "simplified SOP = A'B+AB'"])
    require("simplify minterms 1 2 for A B", ["K-map/minterm method", "variables: A,B", "SOP = A'&B+A&B'", "simplified = A'B+AB'"])
    require("Karnaugh map ones 1 3 5 7 variables A B C", ["K-map/minterm method", "variables: A,B,C", "simplified = C"])
    require("maxterms zeros 0 3 for A B", ["Maxterm/POS method", "variables: A,B", "POS = (A+B)&(A'+B')"])
    require("product of sums form for A or B", ["Product-of-sums method", "zero rows: 0", "simplified POS = (A+B)"])
    require("CNF A and not B", ["Product-of-sums method", "simplified POS"])
    require("Karnaugh map ones 1 3 dont cares 5 7 variables A B C", ["K-map/minterm method", "variables: A,B,C", "don't-care rows: 5,7", "simplified = C"])
    require("maxterms zeros 0 2 dc 4 6 for A B C", ["Maxterm/POS method", "variables: A,B,C", "simplified POS = (C)"])
    require("minterms(1,2)", ["K-map/minterm method", "variables: A,B", "simplified = A'B+AB'"])
    out = require("bool(not(A and B)+A)", ["truth table", "simplified = 1"])
    if "(a&b)'&a'" in out:
        raise SystemExit(f"non-equivalent Boolean law step shown\n{out}")
    require("nandform(A+B)", ["Use NAND", "NAND form", "A NAND A"])
    require("nand form A or B", ["Use NAND", "NAND form", "A NAND A"])
    require("norform(A*B)", ["Use NOR", "NOR form", "A NOR A"])
    require("nor form A and B", ["Use NOR", "NOR form", "A NOR A"])
    require("boolprove(A+B,B+A)", ["Simplify both sides", "LHS simplifies to", "RHS simplifies to", "truth tables", "Same output rows"])
    require("boolprove(A+A'B,A+B)", ["LHS: a+a'&b -> a+b (Covering law)", "LHS simplifies to B+A", "RHS simplifies to B+A", "Same output rows"])
    require("prove A+B = B+A", ["Simplify both sides", "LHS output-1 rows", "Same output rows"])
    require("prove A and (B or C) equals A and B or A and C", ["Simplify both sides", "LHS simplifies to AC+AB", "RHS simplifies to AC+AB", "Same output rows"])
    require("show that A+B is equal to B+A", ["LHS simplifies to B+A", "RHS simplifies to B+A", "Same output rows"])
    require("show A xor B equivalent to A and not B or not A and B", ["XOR identity", "LHS simplifies to A'B+AB'", "RHS simplifies to A'B+AB'", "Same output rows"])
    require("prove A(A'+B)=AB", ["LHS: a&(a'+b) -> a&b (Covering law)", "LHS simplifies to AB", "RHS simplifies to AB", "Same output rows"])
    require("show that A and not B = A*B'", ["truth tables", "Same output rows"])
    print("OK cscalc engine")


if __name__ == "__main__":
    main()
