#!/usr/bin/env python3
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[1]
HOST = Path("/tmp/p3_engine_host")


def build():
    subprocess.check_call([
        "g++", "-std=c++11", "-Wall", "-Wextra", "-Itools",
        "tools/p3_engine.cpp", "tools/p3_engine_host.cpp",
        "-o", str(HOST),
    ], cwd=ROOT)


def run(expr):
    return subprocess.check_output([str(HOST), expr], cwd=ROOT, text=True)


def require(expr, needles):
    out = run(expr)
    for needle in needles:
        if needle not in out:
            raise SystemExit(f"{expr!r} missing {needle!r}\n{out}")
    for bad in ["Verified", "not checked", "syntax error", "Bad Argument"]:
        if bad in out:
            raise SystemExit(f"{expr!r} contains banned {bad!r}\n{out}")


def main():
    build()
    require("suvat(u=2,a=3,t=4)", ["SUVAT", "v = u + at", "v = 14"])
    require("suvat u=2 a=3 t=4", ["SUVAT", "v = u + at", "v = 14"])
    require("constant acceleration u=2 a=3 t=4 find final velocity", ["SUVAT", "v = u + at", "v = 14"])
    require("suvat(u=2,a=3,s=10)", ["v^2 = u^2 + 2as", "v = 8"])
    require("suvat u=2 a=3 s=10", ["v^2 = u^2 + 2as", "v = 8"])
    require("motion with initial velocity u=2 acceleration a=3 displacement s=10", ["v^2 = u^2 + 2as", "v = 8"])
    require("projectile(20,30)", ["Resolve", "u_x", "range"])
    require("proj(20,30)", ["Resolve", "u_x", "range"])
    require("projectile speed 20 angle 30", ["Resolve", "u_x", "range"])
    require("projectileh(20,30,5)", ["vertical motion", "-h = u_y t", "range = u_x t"])
    require("projectile speed 20 angle 30 from height 5", ["vertical motion", "h=5", "range"])
    require("force(12,3)", ["Newton", "36 N"])
    require("newton(12,3)", ["Newton", "36 N"])
    require("force mass 12 acceleration 3", ["Newton", "36 N"])
    require("weight(5)", ["Weight", "49 N"])
    require("friction(0.4,25)", ["F = mu R", "10 N"])
    require("moment(30,2.5)", ["perpendicular", "75 Nm"])
    require("incline(5,30,0.2)", ["parallel = mg sin", "friction", "net down plane"])
    require("plane(5,30,0.2)", ["parallel = mg sin", "friction"])
    require("connected(2,3,10)", ["one system", "a = 2", "tension"])
    require("connected particles mass 2 mass 3 force 10", ["one system", "a = 2", "tension"])
    require("pulley(2,3)", ["same acceleration", "T ="])
    require("varacct(3,2,4,6,2)", ["Variable acceleration with a(t)", "v = u + integral", "at t=2, v = 31", "s = s0 + integral", "s = 23.333"])
    require("variable acceleration u=3 c0=2 c1=4 c2=6 t=2", ["Variable acceleration with a(t)", "at t=2, v = 31", "s = 23.333"])
    require("varaccx(4,3,2,0,5)", ["a = v dv/dx", "v^2 = 4^2", "v = 9.797"])
    require("variable acceleration u=4 c0=3 c1=2 c2=0 x=5", ["a = v dv/dx", "v = 9.797"])
    require("impulse(0.5,4,-2)", ["change in momentum", "-3 Ns"])
    require("impulse mass 0.5 initial velocity 4 final velocity -2", ["change in momentum", "-3 Ns"])
    require("momentum(2,5,3,-1,1)", ["conservation of linear momentum", "m1u1 + m2u2", "v2 ="])
    require("conservation of momentum m1=2 u1=5 m2=3 u2=-1 v1=1", ["conservation of linear momentum", "2*5", "1.666"])
    require("commonvelocity(2,5,3,-1)", ["Particles move together", "(m1+m2)v", "1.4"])
    require("collision conservation particles stick together 2 5 3 -1", ["Particles move together", "v = 1.4"])
    require("work(12,5)", ["Work done", "60 J"])
    require("power(120,3)", ["Power", "40 W"])
    require("power when work done is 120 and time is 3", ["Power", "40 W"])
    require("energy(2,5,3)", ["KE = 1/2", "25 J", "GPE"])
    require("kinetic energy mass 2 speed 5 height 3", ["KE = 1/2", "25 J", "GPE"])
    require("restitution(5,-2,1,3)", ["restitution", "speed of separation"])
    require("collision restitution u1 5 u2 -2 v1 1 v2 3", ["restitution", "speed of separation"])
    require("impactsolve(2,5,3,1,0.5)", ["momentum and Newton", "v2 - v1 = e(u1-u2) = 2", "v1 = 1.4, v2 = 3.4"])
    require("collision find velocities m1=2 u1=5 m2=3 u2=1 e=0.5", ["momentum and Newton", "substitute into momentum", "v1 = 1.4"])
    require("vector(3,4)", ["sqrt", "|R|", "5"])
    require("resolve(20,30)", ["Resolve the force", "20 cos(30)", "20 sin(30)", "components"])
    require("resolve force 20 angle 30 into components", ["Resolve the force", "20 cos(30)", "20 sin(30)"])
    require("equilibrium(3,4,-3,-4)", ["sum Fx = 0", "sum Fy = 0", "result: equilibrium"])
    require("equilibrium force components 3 4 -3 -4", ["sum Fx = 0", "result: equilibrium"])
    require("equilibrium(3,4,1,-2)", ["sum Fx = 4", "sum Fy = 2", "resultant imbalance"])
    require("equilpolar(10,0,10,180)", ["Resolve each force", "sum Fx", "result: equilibrium"])
    require("balance forces with angle 10 0 10 180", ["Resolve each force", "result: equilibrium"])
    require("varacc(2,3,4,5)", ["integrate", "v =", "s ="])
    require("variable acceleration 2 3 initial velocity 4 time 5 integrate", ["integrate", "v =", "s ="])
    require("normal(65,50,10)", ["Standardise", "1.5"])
    require("zscore(65,50,10)", ["Standardise", "1.5"])
    require("standardise 65 mean 50 sd 10", ["Standardise", "1.5"])
    require("normalvar(65,50,100)", ["Convert variance", "sigma = sqrt(100) = 10", "z = (65-50)/10 = 1.5"])
    require("standardise 65 mean 50 variance 100", ["Convert variance", "sigma = sqrt(100) = 10", "1.5"])
    require("binom(10,0.3,4)", ["X ~ B", "10C4"])
    require("binomial(10,0.3,4)", ["X ~ B", "10C4"])
    require("binomcdf(10,0.3,4)", ["P(X<=4)", "0.849"])
    require("binomial n 10 p 0.3 at least 4", ["P(X>=4)", "sum from 4 to 10"])
    require("binomial n 10 p 0.3 more than 4", ["P(X>4)", "sum from 5 to 10"])
    require("binomial n 10 p 0.3 less than 4", ["P(X<4)", "sum from 0 to 3"])
    require("binomnorm(100,0.4,35,45)", ["normal approximation", "mu = np = 40", "continuity correction", "34.5 < Y < 45.5", "NormalCD"])
    require("normal approximation to binomial n 100 p 0.4 between 35 and 45", ["normal approximation", "continuity correction", "NormalCD"])
    require("poissonapprox(200,0.01,3,-1)", ["Poisson approximation", "lambda = np = 200*0.01 = 2", "Use P(Y<=3)", "approx probability"])
    require("poisson approximation to binomial n 200 p 0.01 at most 3", ["Poisson approximation", "lambda = np", "Use P(Y<=3)"])
    require("critbinom(20,0.4,0.05,-1)", ["critical region", "alpha"])
    require("binomial critical region n 20 p 0.4 alpha 0.05 lower", ["critical region", "alpha"])
    require("hypbinom(20,0.4,4,0.05,-1)", ["H0", "Compare", "context"])
    require("binomial hypothesis test n 20 p 0.4 x 4 alpha 0.05 lower", ["H0", "Compare", "context"])
    require("normalprob(40,60,50,10)", ["standardise", "NormalCD"])
    require("normal distribution between 40 and 60 mean 50 sd 10", ["standardise", "NormalCD"])
    require("normal distribution between 40 and 60 mean 50 variance 100", ["Convert variance", "sigma = sqrt(100) = 10", "NormalCD"])
    require("normaltail(65,50,10,1)", ["correct tail", "P(X>=65)", "NormalCD(lower=65"])
    require("normal more than 65 mean 50 sd 10", ["correct tail", "P(X>=65)", "NormalCD(lower=65"])
    require("normal less than 65 mean 50 variance 100", ["Convert variance", "sigma = sqrt(100) = 10", "P(X<=65)"])
    require("hypnormal(53,50,12,36,0.05,1)", ["H0: mu = 50", "standard error", "Reject H0 if"])
    require("normal hypothesis test xbar 53 mu 50 sigma 12 n 36 alpha 0.05 upper", ["H0: mu = 50", "standard error", "compare with alpha"])
    require("invnormal(0.95,100,15)", ["inverse normal", "InvNorm(0.95, 15, 100)"])
    require("normal critical value area 0.95 mean 100 sd 15", ["inverse normal", "InvNorm(0.95, 15, 100)"])
    require("normal critical value area 0.95 mean 100 variance 225", ["Convert variance", "sigma = sqrt(225) = 15", "InvNorm(0.95, 15, 100)"])
    require("cond(0.18,0.3)", ["P(A|B)", "0.6"])
    require("conditional probability with p intersection 0.18 given p b 0.3", ["P(A|B)", "0.6"])
    require("probor(0.4,0.5,0.2)", ["P(A or B)", "0.7"])
    require("union probability pa 0.4 pb 0.5 intersection 0.2", ["P(A or B)", "0.7"])
    require("bayes(0.8,0.3,0.5)", ["Bayes", "0.8*0.3/0.5=0.48"])
    require("bayes reverse conditional 0.8 0.3 0.5", ["Bayes", "0.48"])
    require("independent(0.2,0.3,0.06)", ["independence", "0.2*0.3", "independent"])
    require("test independence 0.2 0.3 0.07", ["independence", "not independent"])
    require("poisson(3,2)", ["Po(lambda)", "P(X=2)"])
    require("poisson(64,60)", ["Po(lambda)", "P(X=60)", "0.045266"])
    require("poisson mean 3 exactly 2", ["Po(lambda)", "P(X=2)"])
    require("poisson mean 3 at most 2", ["cumulative", "P(X<=2)"])
    require("poisson mean 3 at least 2", ["cumulative", "P(X>=2)"])
    require("poissonnorm(64,55,70)", ["normal approximation", "mu = lambda = 64", "continuity correction", "NormalCD"])
    require("normal approximation to poisson mean 64 between 55 and 70", ["normal approximation", "sigma = sqrt(lambda)", "NormalCD"])
    require("critpoisson(3,0.05,1)", ["X ~ Po(3)", "Upper tail", "critical region"])
    require("poisson critical region lambda 3 alpha 0.05 upper", ["X ~ Po(3)", "Upper tail", "critical region"])
    require("hyppoisson(4,8,0.05,1)", ["H0: lambda = 4", "Use P(X>=8)", "Compare with alpha", "context"])
    require("poisson hypothesis test lambda 4 x 8 alpha 0.05 upper", ["H0: lambda = 4", "Use P(X>=8)", "Compare with alpha"])
    require("regress(2,0.5,10)", ["regression line", "y=7"])
    require("regresscalc(5,20,30,10,18,8)", ["least-squares", "xbar", "b = Sxy/Sxx", "regression line", "when x=8"])
    require("regression n=5 sx=20 sy=30 sxx=10 sxy=18 x=8", ["least-squares", "xbar = Sx/n", "regression line", "when x=8"])
    require("regresss(4,6,10,18,8)", ["least-squares", "b = Sxy/Sxx", "a = ybar", "when x=8"])
    require("regression xbar=4 ybar=6 sxx=10 sxy=18 x=8", ["least-squares", "b = Sxy/Sxx", "regression line", "when x=8"])
    require("pmcc(5,20,30,140,90,220)", ["product moment", "top =", "r ="])
    require("correlation n 5 sx 20 sy 30 sxy 140 sx2 90 sy2 220", ["product moment", "r ="])
    require("correlation n=5 sx=20 sy=30 sxy=140 sx2=90 sy2=220", ["product moment", "top =", "r ="])
    require("pmcc sxx=10 syy=40 sxy=18", ["PMCC from summary", "Sxy/sqrt"])
    require("spearman(8,12)", ["Spearman", "r_s = 1 - 6*sum(d^2)/(n(n^2-1))", "0.857142"])
    require("spearman rank correlation n=8 sumd2=12", ["Spearman", "r_s = 0.857142"])
    require("meanvar(5,20,90)", ["mean = Sx/n", "variance"])
    require("mean variance n 5 sx 20 sx2 90", ["mean = Sx/n", "variance"])
    require("groupmean(10,2,20,3,30,5)", ["grouped data", "sum f = 10", "sum fx", "mean = sum fx / sum f = 23", "sd ="])
    require("grouped data mean sd midpoints 10 20 30 frequencies 2 3 5", ["grouped data", "sum f = 10", "mean = sum fx / sum f = 23"])
    require("discrete(0,0.2,1,0.5,2,0.3)", ["discrete random variable", "sum p = 1", "E(X) = 0*0.2+1*0.5+2*0.3 = 1.1", "Var(X)"])
    require("discrete random variable values 0 1 2 probabilities 0.2 0.5 0.3", ["E(X)", "1.1", "E(X^2)", "Var(X)"])
    require("stratified(200,50,40)", ["stratified sampling", "50/200 * 40", "10"])
    require("stratified sample population 200 group 50 sample 40", ["stratified sampling", "10"])
    require("groupmedian(20,15,10,5,50)", ["linear interpolation", "position = n/2", "median = 20 + ((25-15)/10)*5 = 25"])
    require("grouped median 20 cf before 15 frequency 10 class width 5 n 50", ["linear interpolation", "position = n/2", "median = 20"])
    require("groupquantile(20,15,10,5,50,0.75)", ["linear interpolation", "position = 0.75*n", "value ="])
    require("histdensity(12,4)", ["frequency density = frequency / class width", "12/4 = 3"])
    require("histfreq(3,4)", ["frequency = frequency density * class width", "3*4 = 12"])
    require("histogram frequency density 12 width 4", ["frequency density", "12/4 = 3"])
    require("uncode(3,2,20,5)", ["Y=(X-a)/b", "mean X = 20 + 5*3 = 35", "sd X = |b|*sd Y = 5*2 = 10"])
    require("coded data y=(x-20)/5 mean 3 sd 2", ["Y=(X-a)/b", "mean X = 20 + 5*3 = 35", "sd X"])
    require("code(35,10,20,5)", ["For coded data Y=(X-a)/b", "mean Y = (35-20)/5 = 3", "sd Y = sd X/|b| = 10/5 = 2"])
    print("OK p3 engine")


if __name__ == "__main__":
    main()
