#!/usr/bin/env python3
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[1]
HOST = Path("/tmp/p3_engine_host")


def build():
    subprocess.check_call([
        "g++", "-std=c++11", "-Wall", "-Wextra", "-Itools",
        "tools/p3_engine.cpp", "tools/p3_engine_host.cpp",
        "-o", str(HOST),
    ], cwd=ROOT)


def run(expr):
    return subprocess.check_output([str(HOST), expr], cwd=ROOT, text=True)


def require(expr, needles):
    out = run(expr)
    for needle in needles:
        if needle not in out:
            raise SystemExit(f"{expr!r} missing {needle!r}\n{out}")
    for bad in ["Verified", "not checked", "syntax error", "Bad Argument"]:
        if bad in out:
            raise SystemExit(f"{expr!r} contains banned {bad!r}\n{out}")


def main():
    build()
    require("suvat(u=2,a=3,t=4)", ["SUVAT", "v = u + at", "v = 14"])
    require("suvat u=2 a=3 t=4", ["SUVAT", "v = u + at", "v = 14"])
    require("constant acceleration u=2 a=3 t=4 find final velocity", ["SUVAT", "v = u + at", "v = 14"])
    require("constant acceleration initial velocity=2 acceleration=3 time=4 find final velocity", ["SUVAT", "v = u + at", "v = 14"])
    require("a particle starts from rest and accelerates at 3 for 4 seconds find distance travelled", ["From rest gives u = 0", "s = ut + 1/2 at^2", "s = 24"])
    require("A car starts from rest and accelerates uniformly at 2.4 m s^-2 for 8 seconds. Find the final speed and distance travelled.", ["v = u + at", "v = 0 + 2.4*8 = 19.2", "s = 76.8"])
    require("a car starts from rest reaches speed 20 in 5 seconds find acceleration and distance", ["a = (20-0)/5 = 4", "s = 50"])
    require("A car accelerates from rest to 30 m/s in 12 seconds find acceleration and distance", ["a = (30-0)/12 = 2.5", "s = 1/2(0+30)*12", "s = 180"])
    require("train accelerates uniformly from 10 to 30 m/s over 200 m find acceleration and time", ["Use SUVAT", "a = (v^2-u^2)/(2s)", "t = 2s/(u+v)"])
    require("A train travels 300 m accelerating uniformly from 4 m/s to 20 m/s, then decelerates uniformly to rest over the final 100 m. Find the total time.", ["Split the journey", "t1 = 2*200/(4+20)", "total time = 26.666"])
    require("particle thrown vertically upwards with speed 20 find maximum height and time to return", ["vertical SUVAT", "At maximum height", "time to return"])
    require("A ball is projected vertically upwards from a point 1.5m above the ground with speed 14. Find the time when it hits the ground.", ["Use vertical SUVAT", "-1.5 = 14 t", "t ="])
    require("initial velocity 2 acceleration 3 time 4 find distance", ["s = ut + 1/2 at^2", "s = 32"])
    require("suvat(v=14,a=3,t=4)", ["u = v - at", "u = 14 - 3*4 = 2"])
    require("suvat final velocity=14 acceleration=3 time=4 find initial velocity", ["u = v - at", "u = 14 - 3*4 = 2"])
    require("suvat(u=2,v=14,t=4)", ["s = 1/2(u+v)t", "s = 32"])
    require("suvat(u=2,s=32,t=4)", ["v = 2s/t - u", "v = 2*32/4 - 2 = 14"])
    require("suvat(v=14,s=32,t=4)", ["u = 2s/t - v", "u = 2"])
    require("suvat(u=2,a=3,s=10)", ["v^2 = u^2 + 2as", "v = 8"])
    require("suvat u=2 a=3 s=10", ["v^2 = u^2 + 2as", "v = 8"])
    require("motion with initial velocity u=2 acceleration a=3 displacement s=10", ["v^2 = u^2 + 2as", "v = 8"])
    require("suvat(v=8,a=3,s=10)", ["u^2 = v^2 - 2as", "u = 2"])
    require("suvat(u=2,v=8,s=10)", ["a=(v^2-u^2)/(2s)", "a = (8^2-2^2)/(2*10) = 3"])
    require("suvat(u=2,s=32,a=3)", ["quadratic in t", "t = 4"])
    require("suvat(u=2,s=8,a=0)", ["Here a=0", "t = s/u = 8/2 = 4"])
    require("suvat(s=32,a=3,t=4)", ["Use s = 1/2(u+v)t and v = u + at", "u = 2, v = 14"])
    require("suvat displacement=32 acceleration=3 time=4", ["Use s = 1/2(u+v)t and v = u + at", "u = 2, v = 14"])
    require("projectile(20,30)", ["Resolve", "u_x", "range"])
    require("proj(20,30)", ["Resolve", "u_x", "range"])
    require("projectile speed 20 angle 30", ["Resolve", "u_x", "range"])
    require("a particle is projected with speed 20 at 30 degrees find the range", ["Resolve", "u_x = 20 cos 30", "range"])
    require("projectile angle=30 speed=20 g=9.8", ["Resolve", "u_x = 20 cos 30", "range"])
    require("projectileh(20,30,5)", ["vertical motion", "-h = u_y t", "range = u_x t"])
    require("projectile speed 20 angle 30 from height 5", ["vertical motion", "h=5", "range"])
    require("projectile from height=5 speed=20 angle=30", ["vertical motion", "h=5", "range"])
    require("A ball is thrown from 2 metres above the ground with speed 18 at angle 35 find when it hits the ground and range", ["vertical motion", "h=2", "range = u_x t"])
    require("A particle is fired with speed 25 metres per second at 40 degrees to the horizontal. Find the greatest height and horizontal range.", ["Resolve", "u_x = 25 cos 40", "max height"])
    require("projectileat(20,30,10)", ["horizontal motion to find time", "Horizontal: x = u_x t", "Vertical: y = h + u_y t", "height at x=10"])
    require("projectile speed 20 angle 30 distance 10 find height", ["horizontal motion to find time", "height at x=10"])
    require("projectile find height distance=10 angle=30 speed=20", ["horizontal motion to find time", "height at x=10"])
    require("A projectile is fired with speed 20 at 30 degrees. Find the two times when it is 4 metres high.", ["requested height", "4 = 0 + 10 t", "times ="])
    require("projectileangle(20,20,5)", ["trajectory equation", "Let T=tan(theta)", "tan(theta)", "theta ="])
    require("projectile speed 20 find angle to pass through point 20 5", ["trajectory equation", "Let T=tan(theta)", "theta ="])
    require("projectile find angle speed=20 x=20 y=5", ["trajectory equation", "Let T=tan(theta)", "theta ="])
    require("A projectile is fired at 20 m/s and lands at same level 30m away. Find the angle of projection.", ["trajectory equation", "theta = 66.346", "23.653"])
    require("force(12,3)", ["Newton", "36 N"])
    require("newton(12,3)", ["Newton", "36 N"])
    require("force mass 12 acceleration 3", ["Newton", "36 N"])
    require("A car of mass 1200kg has driving force 2400N and resistance 600N find acceleration", ["resultant force = driving force - resistance", "F = 2400 - 600 = 1800 N", "a = F/m = 1800/1200 = 1.5"])
    require("a force of 20N acts at 30 degrees to horizontal find horizontal component", ["Resolve the force", "horizontal = F cos(theta) = 20 cos(30)", "components = 17.320"])
    require("A lift of mass 500kg accelerates upwards at 0.8 find tension in cable", ["Newton's second law vertically", "T = m(g+a)", "5300 N"])
    require("a particle of mass 4kg is pulled by force 20N on smooth horizontal plane find acceleration", ["Smooth horizontal plane", "resultant horizontal force = 20 - 0 = 20 N", "a = F/m = 20/4 = 5"])
    require("a box mass 5 on rough horizontal plane coefficient friction 0.3 pulled by 20N find acceleration", ["Rough horizontal plane", "friction = mu R = 0.3*49 = 14.7 N", "a = F/m = 5.3/5 = 1.06"])
    require("A particle mass 2kg is pulled along rough horizontal by force 10N at 30 degrees above horizontal mu 0.2 find acceleration", ["Rough horizontal plane", "horizontal component", "friction = mu R"])
    require("A box of mass 10kg is pulled by force 50N at 30 degrees above the horizontal. Coefficient of friction is 0.2. Find acceleration.", ["Rough horizontal plane", "horizontal component", "a = F/m = 28.701"])
    require("weight(5)", ["Weight", "49 N"])
    require("friction(0.4,25)", ["F = mu R", "10 N"])
    require("moment(30,2.5)", ["perpendicular", "75 Nm"])
    require("beam(10,30,4)", ["moments about the left support", "R_B*10 = 30*4", "R_B = 12", "R_A = 18"])
    require("beam(10,30,4,20)", ["R_B*10 = 30*4 + 20*(10/2)", "R_B = 22", "R_A = 28"])
    require("beam support reactions length=10 load=30 distance=4 beamweight=20", ["moments about the left support", "R_B = 22", "R_A = 28"])
    require("A uniform beam AB length 8m has weight 40N. A load of 60N is placed 3m from A. Find reactions at A and B.", ["R_B*8 = 60*3 + 40*(8/2)", "R_A = 57.5 N"])
    require("A beam of length 6m has a 20N load 2m from A and a 10N load 5m from A. Find support reactions.", ["R_B*6 = 20*2 + 10*5", "R_A = 15 N"])
    require("A rod length 6m weight 20N has forces 30N at 2m and 40N at 5m find reaction at supports", ["include its weight at the midpoint", "rod weight moment = 20*(6/2)", "R_B = 53.333", "R_A = 36.666"])
    require("ladder(5,100,60)", ["smooth wall, rough floor", "Vertical equilibrium", "Horizontal equilibrium", "Take moments about the foot", "limiting friction"])
    require("ladder(5,100,60,50,3)", ["wall reaction S", "100*(5/2 cos 60) + 50*(3 cos 60)", "mu = F/R"])
    require("ladder against smooth wall rough floor length=5 weight=100 angle=60", ["smooth wall, rough floor", "S = ", "limiting friction"])
    require("incline(5,30,0.2)", ["parallel = mg sin", "friction", "net down plane"])
    require("plane(5,30,0.2)", ["parallel = mg sin", "friction"])
    require("inclineacc(5,30,0.2)", ["Resolve along and perpendicular", "F=ma", "friction = mu R", "a = F/m"])
    require("rough plane acceleration mass 5 angle 30 mu 0.2", ["Resolve along and perpendicular", "net force down plane", "m/s^2"])
    require("particle on rough inclined plane mass 5 coefficient friction 0.2 angle 30 find acceleration", ["Resolve along and perpendicular", "friction = mu R", "a = F/m"])
    require("rough plane mass 5 coefficient friction 0.2 angle 30", ["Resolve along and perpendicular", "friction = mu R", "a = F/m"])
    require("A particle of mass 6kg is held in equilibrium on a rough plane inclined at 25 degrees by a force of 20N up the line of greatest slope. Find the friction and normal reaction.", ["Resolve parallel", "Normal reaction", "Equilibrium along the plane", "friction ="])
    require("A particle of mass 3kg rests on a rough plane inclined at 20 degrees. Find the least coefficient of friction for equilibrium.", ["limiting equilibrium", "mu R = mg sin(theta)", "least mu = tan(theta)"])
    require("A particle of mass 5kg is pulled up a rough plane angle 30 degrees by a force 40N at 20 degrees above the plane, coefficient friction 0.2. Find acceleration.", ["rough inclined plane", "Up-plane pull component", "a = F/m"])
    require("connected(2,3,10)", ["one system", "a = 2", "tension"])
    require("connected particles mass 2 mass 3 force 10", ["one system", "a = 2", "tension"])
    require("pulley(2,3)", ["same acceleration", "T ="])
    require("A particle of mass 4 kg is on a smooth plane inclined at 30 degrees connected over a pulley to a hanging mass 6 kg. Find the acceleration and tension.", ["Smooth inclined-plane pulley", "m2 g - m1 g sin(theta)", "a =", "T ="])
    require("A particle of mass 5 kg is on a rough plane inclined at 30 degrees coefficient of friction 0.2 connected over a pulley to a hanging mass 8 kg. Find acceleration and tension.", ["Rough inclined-plane pulley", "mu m1 g cos(theta)", "a = 3.493", "T ="])
    require("varacct(3,2,4,6,2)", ["Variable acceleration with a(t)", "v = u + integral", "at t=2, v = 31", "s = s0 + integral", "s = 23.333"])
    require("variable acceleration u=3 c0=2 c1=4 c2=6 t=2", ["Variable acceleration with a(t)", "at t=2, v = 31", "s = 23.333"])
    require("A particle moves in a straight line with acceleration a = 6t + 4. Initially it is at O and has velocity 3. Find its velocity and displacement after 5 seconds.", ["Variable acceleration", "a = 6 t +4", "initial velocity gives C = 3", "at t=5, v = 98", "at t=5, s = 190"])
    require("A particle moves with acceleration 4-2t. Initially its velocity is 5. Find the velocity and displacement after 3 seconds.", ["Variable acceleration", "a = -2 t +4", "at t=3, v = 8", "at t=3, s = 24"])
    require("A particle moves with acceleration a = 12t^2 - 6t. It starts from rest. Find velocity after 3 seconds.", ["Variable acceleration", "a = 12 t^2 -6 t", "initial velocity gives C = 0", "at t=3, v = 81"])
    require("A particle moves with acceleration a = 3t^2 + 2t - 1. Initially v=4 and s=2. Find v and s at t=3.", ["a = 3 t^2 +2 t -1", "initial velocity gives C = 4", "initial position gives C = 2", "at t=3, s = 38.75"])
    require("A particle has acceleration a=12*t^2-6*t and v=5 at t=0 find displacement from 0 to 2", ["Variable acceleration", "s(t) = 1 t^4 -1 t^3", "displacement = s(2)-s(0) = 18"])
    require("A particle moves along a line with velocity v = 9t^2 - 4t. Find acceleration at t=2 and displacement from t=1 to t=3.", ["a = dv/dt = 18 t -4", "at t=2, a = 32", "displacement = 63 - 1 = 62"])
    require("A particle moves with velocity v = 3t^2 - 12t + 5. Find the total distance travelled from t=0 to t=5.", ["Total distance", "Solve v=0", "total distance = 28.513"])
    require("A particle moves with velocity v = 4t^3 - 12t^2 + 9t. Find the displacement from t=0 to t=3.", ["v = 4 t^3", "s = integral(v)", "displacement = 13.5"])
    require("A particle moves with velocity v = t^4 - 2t^3 - 3t^2. Find the displacement from t=0 to t=3.", ["v = 1 t^4 -2 t^3 -3 t^2", "s = integral(v)", "displacement = -18.9"])
    require("A particle has velocity v = 2t^3 - 9t^2 + 12t. Find the total distance from t=0 to t=4.", ["v = 2 t^3 -9 t^2 +12 t", "total distance = 32"])
    require("A particle moves with displacement s = 2t^3 - 15t^2 + 36t. Find the total distance travelled between t=0 and t=4.", ["v = ds/dt", "distance on 0 to 2", "total distance = 34"])
    require("A particle has displacement s = t^4 - 8t^2. Find the total distance travelled between t=0 and t=3.", ["v = ds/dt = 4 t^3", "distance on 0 to 2", "total distance = 41"])
    require("A particle has velocity v = 12t - 3t^2. Find the maximum displacement from the origin.", ["Maximum displacement", "Solve v=0", "maximum displacement = 32"])
    require("A particle has displacement s = t^3 - 6t^2 + 9t. Find when it is stationary and its acceleration then.", ["v = ds/dt", "v=0 gives t = 1 or 3", "at t=1, a = -6", "at t=3, a = 6"])
    require("A particle moves with displacement s = t^4 - 4t^3 + 2t^2. Find when it is stationary between t=0 and t=4.", ["s = 1 t^4 -4 t^3", "v = ds/dt = 4 t^3", "t = 0.3819660115", "t = 2.618033989"])
    require("A particle has acceleration a = 6 - 4t and initial velocity 2. Find when it comes to rest and the distance travelled by then.", ["Variable acceleration", "comes to rest when v=0", "distance = 15.312"])
    require("varaccx(4,3,2,0,5)", ["a = v dv/dx", "v^2 = 4^2", "v = 9.797"])
    require("variable acceleration u=4 c0=3 c1=2 c2=0 x=5", ["a = v dv/dx", "v = 9.797"])
    require("impulse(0.5,4,-2)", ["change in momentum", "-3 Ns"])
    require("impulse mass 0.5 initial velocity 4 final velocity -2", ["change in momentum", "-3 Ns"])
    require("A particle P of mass 0.5 kg is moving with velocity 8 m/s when it receives an impulse of magnitude 3 Ns in the opposite direction. Find its speed after the impulse.", ["Impulse equals change", "opposite to the motion", "v = 2"])
    require("A particle of mass 2 kg has velocity 3i+4j and receives impulse -2i+j. Find its speed after the impulse.", ["component by component", "v = 2 i + 4.5 j", "speed = sqrt"])
    require("momentum(2,5,3,-1,1)", ["conservation of linear momentum", "m1u1 + m2u2", "v2 ="])
    require("conservation of momentum m1=2 u1=5 m2=3 u2=-1 v1=1", ["conservation of linear momentum", "2*5", "1.666"])
    require("commonvelocity(2,5,3,-1)", ["Particles move together", "(m1+m2)v", "1.4"])
    require("collision conservation particles stick together 2 5 3 -1", ["Particles move together", "v = 1.4"])
    require("work(12,5)", ["Work done", "60 J"])
    require("power(120,3)", ["Power", "40 W"])
    require("power when work done is 120 and time is 3", ["Power", "40 W"])
    require("energy(2,5,3)", ["KE = 1/2", "25 J", "GPE"])
    require("kinetic energy mass 2 speed 5 height 3", ["KE = 1/2", "25 J", "GPE"])
    require("workenergyforce(0.8,10,15,0,20)", ["work-energy", "gain in KE", "50 J", "F*20", "F = 2.5 N"])
    require("A variable force F=(3x^2+2x) N acts from x=0 to x=4. Find the work done.", ["variable force", "integral from 0 to 4", "W = 80 J"])
    require("A force F = 5x - 2 acts from x=1 to x=4. Find the work done.", ["variable force", "integral from 1 to 4", "W = 31.5 J"])
    require("A particle of mass 0.5 kg is moving at 6 m/s. A constant resistance of 2 N acts for 5 m. Find the final speed.", ["resistance doing negative work", "1/2*0.5*6^2 - 2*5", "v = 0 m/s"])
    require("A ball of mass 0.2 kg falls from rest through 3m against air resistance 0.4N. Find its speed.", ["loss of GPE", "mgh - Rd", "v = 6.841"])
    require("work energy driving force mass=5 u=0 v=4 height=2 distance=10 resistance=3", ["gain in KE", "gain in GPE", "work against resistance", "F = 16.8 N"])
    require("A car of mass 800 kg moves up a slope against resistance 200N. It gains speed from 5 to 15 over 100m and rises 8m. Find driving force.", ["work-energy", "gain in KE", "gain in GPE", "F ="])
    require("A cyclist of mass 70 kg moves along horizontal road against resistance 30N, speed increases from 4 to 10 over 50m. Find driving force.", ["work-energy", "gain in GPE = mgh = 70*9.8*0", "F = 88.8 N"])
    require("A car of mass 1000kg has engine power 20kW and travels at 10m/s against resistance 500N. Find acceleration.", ["Use P = Fv", "driving force = P/v = 20000/10 = 2000", "a = F/m = 1500/1000 = 1.5"])
    require("restitution(5,-2,1,3)", ["restitution", "speed of separation"])
    require("collision restitution u1 5 u2 -2 v1 1 v2 3", ["restitution", "speed of separation"])
    require("impactsolve(2,5,3,1,0.5)", ["momentum and Newton", "v2 - v1 = e(u1-u2) = 2", "v1 = 1.4, v2 = 3.4"])
    require("collision find velocities m1=2 u1=5 m2=3 u2=1 e=0.5", ["momentum and Newton", "substitute into momentum", "v1 = 1.4"])
    require("vectorkin(1,2,3,4,0,-2,5)", ["vector constant-acceleration", "r = r0 + ut", "position = (16, -3)", "velocity = (3, -6)", "speed ="])
    require("vector motion x0=1 y0=2 ux=3 uy=4 ax=0 ay=-2 t=5", ["vector constant-acceleration", "position = (16, -3)", "velocity = (3, -6)"])
    require("position vector motion 1 2 3 4 0 -2 5", ["vector constant-acceleration", "position = (16, -3)", "speed ="])
    require("vector(3,4)", ["sqrt", "|R|", "5"])
    require("A force 7i-24j N acts on a particle. Find its magnitude and direction.", ["|R| = sqrt(7^2+-24^2) = 25", "direction"])
    require("resolve(20,30)", ["Resolve the force", "20 cos(30)", "20 sin(30)", "components"])
    require("resolve force 20 angle 30 into components", ["Resolve the force", "20 cos(30)", "20 sin(30)"])
    require("equilibrium(3,4,-3,-4)", ["sum Fx = 0", "sum Fy = 0", "result: equilibrium"])
    require("equilibrium force components 3 4 -3 -4", ["sum Fx = 0", "result: equilibrium"])
    require("equilibrium(3,4,1,-2)", ["sum Fx = 4", "sum Fy = 2", "resultant imbalance"])
    require("equilpolar(10,0,10,180)", ["Resolve each force", "sum Fx", "result: equilibrium"])
    require("balance forces with angle 10 0 10 180", ["Resolve each force", "result: equilibrium"])
    require("A particle is in equilibrium under forces 10N at 0 degrees 10N at 120 degrees and 10N at 240 degrees", ["Resolve each force", "result: equilibrium"])
    require("varacc(2,3,4,5)", ["integrate", "v =", "s ="])
    require("variable acceleration 2 3 initial velocity 4 time 5 integrate", ["integrate", "v =", "s ="])
    require("A particle moves with acceleration a=6t-4 velocity initially 3 and position initially 2 find v and s", ["v = 3*t^2 -4*t +3", "s = 1*t^3 -2*t^2 +3*t +2"])
    require("normal(65,50,10)", ["Standardise", "1.5"])
    require("zscore(65,50,10)", ["Standardise", "1.5"])
    require("standardise 65 mean 50 sd 10", ["Standardise", "1.5"])
    require("normalvar(65,50,100)", ["Convert variance", "sigma = sqrt(100) = 10", "z = (65-50)/10 = 1.5"])
    require("standardise 65 mean 50 variance 100", ["Convert variance", "sigma = sqrt(100) = 10", "1.5"])
    require("binom(10,0.3,4)", ["X ~ B", "10C4"])
    require("binomial(10,0.3,4)", ["X ~ B", "10C4"])
    require("binom_work(10,0.3,4)", ["X ~ B", "10C4"])
    require("binom_work(10,0.3,4,1)", ["P(X>=4)", "sum from 4 to 10"])
    require("binomcdf(10,0.3,4)", ["P(X<=4)", "0.849"])
    require("binomial n 10 p 0.3 at least 4", ["P(X>=4)", "sum from 4 to 10"])
    require("binomial p=0.3 n=10 at least x=4", ["P(X>=4)", "sum from 4 to 10"])
    require("binomial n 10 p 0.3 more than 4", ["P(X>4)", "sum from 5 to 10"])
    require("binomial n 10 p 0.3 less than 4", ["P(X<4)", "sum from 0 to 3"])
    require("A biased coin has probability 0.42 of heads. It is tossed 30 times. Find the probability of fewer than 10 heads.", ["P(X<10)", "sum from 0 to 9"])
    require("A binomial random variable has n 20 and p 0.35 find P(X less than or equal to 6)", ["P(X<=6)", "0.4166254182"])
    require("The probability that a component is faulty is 0.03. In a sample of 80 find the probability that fewer than 4 are faulty.", ["X ~ B(80, 0.03)", "P(X<4)", "sum from 0 to 3"])
    require("The probability that a seed germinates is 0.7. Find the probability that in 20 seeds no more than 12 germinate.", ["X ~ B(20, 0.7)", "P(X<=12)"])
    require("a biased coin has probability 0.35 of heads find the probability of exactly 6 heads in 20 tosses", ["X ~ B(20, 0.35)", "P(X=6)"])
    require("a biased coin has probability 0.35 of heads find probability at least 6 heads in 20 tosses", ["X ~ B(20, 0.35)", "P(X>=6)", "sum from 6 to 20"])
    require("a random variable X follows B(30,0.2), find P(X is at least one)", ["X ~ B(30, 0.2)", "P(X>=1)", "0.99876206"])
    require("A disease affects 2 percent of plants. In 80 plants find the probability at least one is affected.", ["X ~ B(80, 0.02)", "P(X>=1)"])
    require("a random variable X follows B(30,0.2), find P(X equals 0)", ["X ~ B(30, 0.2)", "P(X=0)", "0.001237940039"])
    require("find P(X<=4) for X~B(10,0.3)", ["X ~ B(10, 0.3)", "P(X<=4)", "0.8497316674"])
    require("A random variable X has distribution B(40,0.15). Find P(3 < X <= 8).", ["Let X ~ B(40, 0.15)", "r=4..8"])
    require("find critical region for X~B(20,0.4) at 5 percent significance upper tail", ["Upper tail", "alpha = 0.05", "critical region: X >= 13"])
    require("Find the critical region for X~B(30,0.25) at 1 percent significance, upper tail.", ["alpha = 0.01", "critical region: X >= 14"])
    require("normal approximation X~B(200,0.1) find P(X<=25)", ["Use normal approximation", "25.5", "NormalCD"])
    require("Normal approximation to B(80,0.35), find P(25<=X<=35)", ["Use normal approximation", "24.5 < Y < 35.5", "NormalCD"])
    require("A shop owner knows 12% of customers buy ready salted crisps. On a day 65 customers bought crisps. Using a distributional approximation find the probability that more than 9 bought ready salted.", ["Poisson approximation", "lambda = np", "Use P(Y>9)"])
    require("60 rose bushes are planted and probability 0.25 exceeds 2 metres. Using a distributional approximation find the probability that more than 13 but no more than 18 exceed 2 metres.", ["Use normal approximation", "13.5 < Y < 18.5"])
    require("In a university 39% of students are female. A random sample of 80 is selected. Use a distributional approximation to find the probability that more than half are female.", ["Use normal approximation", "40.5 < Y < 80.5"])
    require("hypothesis test X~B(20,0.4), x=13, 5 percent upper tail", ["H0: p = 0.4", "Compare", "Reject H0"])
    require("In a hypothesis test X~B(40,p), observed x=18, test whether p is greater than 0.3 at 5 percent.", ["H0: p = 0.3", "tail probability", "Reject H0"])
    require("binomstats(50,0.2)", ["E(X)=np", "E(X) = 50*0.2 = 10", "Var(X) = 50*0.2*(1-0.2) = 8", "sd ="])
    require("binomial distribution n 50 p 0.2 mean variance sd", ["E(X)=np", "E(X) = 50*0.2 = 10", "Var(X)"])
    require("binomial distribution p=0.2 n=50 mean variance sd", ["E(X)=np", "E(X) = 50*0.2 = 10", "Var(X)"])
    require("A binomial distribution has mean 12 and variance 7.2. Find n and p.", ["mean = np = 12", "p = 1 - 0.6 = 0.4", "n = mean/p = 12/0.4 = 30"])
    require("binomnorm(100,0.4,35,45)", ["normal approximation", "mu = np = 40", "continuity correction", "34.5 < Y < 45.5", "NormalCD"])
    require("normal approximation to binomial n 100 p 0.4 between 35 and 45", ["normal approximation", "continuity correction", "NormalCD"])
    require("normal approximation to binomial p=0.4 n=100 lower=35 upper=45", ["normal approximation", "34.5 < Y < 45.5", "NormalCD"])
    require("Use a normal approximation for X binomial n 500 p 0.02 find probability X is at least 15", ["normal approximation", "mu = np = 10", "14.5 < Y < 500.5", "NormalCD"])
    require("poissonapprox(200,0.01,3,-1)", ["Poisson approximation", "lambda = np = 200*0.01 = 2", "Use P(Y<=3)", "approx probability"])
    require("poisson approximation to binomial n 200 p 0.01 at most 3", ["Poisson approximation", "lambda = np", "Use P(Y<=3)"])
    require("Using a distributional approximation, X is binomial n 1000 p 0.003. Find P(X at most 5).", ["Poisson approximation", "X ~ B(1000, 0.003)", "lambda = np = 1000*0.003 = 3", "Use P(Y<=5)"])
    require("Using a distributional approximation, X is binomial n 1000 p=0.003. Find P(X at most 5).", ["Poisson approximation", "X ~ B(1000, 0.003)", "lambda = np = 1000*0.003 = 3", "Use P(Y<=5)"])
    require("For X binomial n=80 p=0.04 use a suitable approximation to find P(X no more than 6).", ["Poisson approximation", "X ~ B(80, 0.04)", "lambda = np = 80*0.04 = 3.2", "Use P(Y<=6)"])
    require("A component has probability 0.02 of being defective. In 300 components use a suitable approximation to find P(X=4).", ["Poisson approximation", "Use P(Y=4)"])
    require("Calls arrive at mean rate 4 per hour. Find probability exactly 2 calls in an hour.", ["For X~Po(lambda)", "P(X=2)=e^-4*4^2/2!"])
    require("Poisson arrivals happen at rate 12 per day. Find the probability of exactly 3 in 6 hours.", ["P(X=3)=e^-3*3^3/3!", "0.224041"])
    require("X has Poisson mean 6. Find P(2<X<7).", ["P(3<=X<=6)", "0.544333978"])
    require("critbinom(20,0.4,0.05,-1)", ["critical region", "alpha"])
    require("binomial critical region n 20 p 0.4 alpha 0.05 lower", ["critical region", "alpha"])
    require("binomial critical region p=0.4 n=20 alpha=0.05 lower", ["critical region", "alpha"])
    require("hypbinom(20,0.4,4,0.05,-1)", ["H0", "Compare", "context"])
    require("hyp_test(20,0.4,4,0.05,-1)", ["H0", "Compare", "context"])
    require("binomial hypothesis test n 20 p 0.4 x 4 alpha 0.05 lower", ["H0", "Compare", "context"])
    require("binomial hypothesis test p=0.4 x=4 alpha=0.05 n=20 lower", ["H0", "Compare", "context"])
    require("hypothesis test coin tossed 20 times heads 15 test at 5 percent significance", ["H0: p = 0.5", "alpha = 0.05", "Reject H0"])
    require("A company claims 30 percent of customers prefer A. In a sample of 50, 22 prefer A. Test at the 5 percent level whether the proportion has increased.", ["H0: p = 0.3", "H1: p is greater", "Compare"])
    require("A test has significance level 5 percent. A coin is tossed 30 times and heads occurs 22 times. Test whether the coin is biased.", ["H0: p = 0.5", "two-tailed probability", "alpha = 0.05"])
    require("normalprob(40,60,50,10)", ["standardise", "NormalCD"])
    require("normal_work(40,60,50,10)", ["standardise", "NormalCD"])
    require("normal_work(65,50,10)", ["Standardise", "1.5"])
    require("normal distribution between 40 and 60 mean 50 sd 10", ["standardise", "NormalCD"])
    require("normal distribution lower=40 upper=60 sd=10 mean=50", ["standardise", "NormalCD"])
    require("a random variable X is normally distributed with mean 80 and standard deviation 12 find P 70 less than X less than 95", ["standardise both bounds", "NormalCD(lower=70, upper=95, sigma=12, mu=80)"])
    require("X~N(50,10^2), find P(X<65)", ["sigma = sqrt(100) = 10", "P(X<=65)", "NormalCD(lower=-1E99, upper=65, sigma=10, mu=50)"])
    require("find P(40<X<60) for X~N(50,100)", ["sigma = sqrt(100) = 10", "NormalCD(lower=40, upper=60, sigma=10, mu=50)"])
    require("normal distribution mean 50 standard deviation squared 100 find P(X less than 65)", ["sigma = sqrt(100) = 10", "P(X<=65)"])
    require("A normal random variable has mean 20 and variance 9. Find P(18<X<25).", ["Convert variance", "sigma = sqrt(9) = 3", "NormalCD(lower=18, upper=25"])
    require("A random variable is normal with mean 100 and variance 25. Find P(X<93).", ["Convert variance", "sigma = sqrt(25) = 5", "P(X<=93)", "NormalCD(lower=-1E99, upper=93, sigma=5, mu=100)"])
    require("sample mean 52 population mean 50 sd 8 n 25 test if mean increased at 5 percent", ["H0: mu = 50", "standard error", "Reject H0 if p <= alpha 0.05"])
    require("A sample of 12 has mean 54 and standard deviation 6 test whether mean is greater than 50 at 5 percent significance", ["H0: mu = 50", "6/sqrt(12)", "Reject H0"])
    require("A large sample has mean 24, standard deviation 5 and n 64. Test at 1 percent whether population mean is less than 25.", ["H0: mu = 25", "standard error", "Reject H0 if p <= alpha 0.01"])
    require("The lifetime of batteries is normally distributed with mean 18 hours and standard deviation 2.5 hours. Find the probability that the mean lifetime of a sample of 16 is more than 19 hours.", ["sample mean", "standard error", "P(Xbar>=19)"])
    require("The masses of bags are normally distributed with mean 500g and standard deviation 12g. Find the probability that the total mass of 4 bags is more than 2040g.", ["total of independent normal", "mean = 4*500 = 2000", "sd = sqrt(4)*12 = 24", "NormalCD(lower=2040"])
    require("normal distribution between 40 and 60 mean 50 variance 100", ["Convert variance", "sigma = sqrt(100) = 10", "NormalCD"])
    require("normal distribution lower=40 upper=60 mean=50 variance=100", ["Convert variance", "sigma = sqrt(100) = 10", "NormalCD"])
    require("normaltail(65,50,10,1)", ["correct tail", "P(X>=65)", "NormalCD(lower=65"])
    require("normal more than 65 mean 50 sd 10", ["correct tail", "P(X>=65)", "NormalCD(lower=65"])
    require("normal more than x=65 mean=50 sd=10", ["correct tail", "P(X>=65)", "NormalCD(lower=65"])
    require("normal distribution mean 50 standard deviation 8 find probability x greater than 60", ["z=(60-50)/8", "P(X>=60)", "sigma=8, mu=50"])
    require("normal less than 65 mean 50 variance 100", ["Convert variance", "sigma = sqrt(100) = 10", "P(X<=65)"])
    require("normalcond(65,60,50,10,1)", ["P(A|B)=P(A and B)/P(B)", "A: X>=65, B: X>=60", "P(B)=P(X>=60)", "P(A|B)="])
    require("normal conditional probability more than 65 given more than 60 mean 50 sd 10", ["P(A|B)=P(A and B)/P(B)", "A: X>=65, B: X>=60", "conditional probability"])
    require("X is normally distributed with mean 60 and standard deviation 8. Find P(X>70 given X>55).", ["X~N(60, 8^2)", "A: X>=70, B: X>=55", "conditional probability"])
    require("A random variable has normal distribution mean 50 standard deviation 6. Find probability 45<X<55 given X<60.", ["A: 45<X<55", "A and B gives 45<X<55", "conditional probability"])
    require("hypnormal(53,50,12,36,0.05,1)", ["H0: mu = 50", "standard error", "Reject H0 if"])
    require("hyp_test(53,50,12,36,0.05,1)", ["H0: mu = 50", "standard error", "Reject H0 if"])
    require("normal hypothesis test xbar 53 mu 50 sigma 12 n 36 alpha 0.05 upper", ["H1: mu is greater", "p = P(Z>=", "Reject H0"])
    require("normal hypothesis test sigma=12 alpha=0.05 xbar=53 n=36 mu=50 upper", ["H1: mu is greater", "p = P(Z>=", "Reject H0"])
    require("normal hypothesis test xbar 53 mu 50 sigma 12 n 36 alpha 0.05 two tailed", ["H1: mu is different", "two-tailed p", "Reject H0 if p <= alpha"])
    require("normal hypothesis test n=36 sigma=12 alpha=0.05 mu=50 xbar=53 two tailed", ["H1: mu is different", "two-tailed p", "Reject H0 if p <= alpha"])
    require("A random sample of 25 from a normal population has sample mean 102, population standard deviation 15. Test at 5 percent whether the population mean is greater than 100.", ["H0: mu = 100", "standard error = sigma/sqrt(n) = 15/sqrt(25) = 3", "Do not reject H0"])
    require("invnormal(0.95,100,15)", ["inverse normal", "InvNorm(0.95, 15, 100)"])
    require("A random variable X is normally distributed with mean 100 and standard deviation 15. Find the interquartile range.", ["Q1 = mu - 0.67448975*sigma", "Q3 = mu + 0.67448975*sigma", "IQR = Q3 - Q1"])
    require("normal critical value area 0.95 mean 100 sd 15", ["inverse normal", "InvNorm(0.95, 15, 100)"])
    require("normal critical value area=0.95 sd=15 mean=100", ["inverse normal", "InvNorm(0.95, 15, 100)"])
    require("normal critical value area 0.95 mean 100 variance 225", ["Convert variance", "sigma = sqrt(225) = 15", "InvNorm(0.95, 15, 100)"])
    require("A normal variable has mean 30 and standard deviation 4. Find the value exceeded by 10 percent of observations.", ["Area to the left = 0.9", "InvNorm(0.9, 4, 30)"])
    require("A normal variable has mean 50 and P(X>70)=0.2. Find the standard deviation.", ["Use z=(x-mu)/sigma", "area to the left = 0.8", "sigma = 23.763"])
    require("find k such that P(X less than k)=0.95 for X normal mean 100 sd 15", ["inverse normal", "Area to the left = 0.95", "InvNorm(0.95, 15, 100)"])
    require("find k such that P(X greater than k)=0.05 for X normal mean 100 sd 15", ["inverse normal", "Area to the left = 0.95", "InvNorm(0.95, 15, 100)"])
    require("A normal random variable has mean unknown and sd 4. Given P(X<10)=0.2 find the mean.", ["Use z=(x-mu)/sigma", "area to the left = 0.2", "mu = 13.366"])
    require("normalparams(40,0.1,70,0.9)", ["Use z=(x-mu)/sigma", "P(X<=40)=0.1", "(40-mu)/sigma", "sigma = (70-40)", "mean = 55"])
    require("normal find mean and sd P X less than 40 is 0.1 and P X less than 70 is 0.9", ["Use z=(x-mu)/sigma", "P(X<=40)=0.1", "P(X<=70)=0.9", "mean = 55"])
    require("For a normal distribution, P(X<30)=0.2 and P(X<70)=0.9. Find the mean and standard deviation.", ["Use z=(x-mu)/sigma", "P(X<=30)=0.2", "mean = 45.855"])
    require("cond(0.18,0.3)", ["P(A|B)", "0.6"])
    require("conditional probability with p intersection 0.18 given p b 0.3", ["P(A|B)", "0.6"])
    require("prob_work(0.18,0.3)", ["P(A|B)", "0.6"])
    require("probor(0.4,0.5,0.2)", ["P(A or B)", "0.7"])
    require("prob_work(0.4,0.5,0.2)", ["P(A or B)", "0.7"])
    require("union probability pa 0.4 pb 0.5 intersection 0.2", ["P(A or B)", "0.7"])
    require("bayes(0.8,0.3,0.5)", ["Bayes", "0.8*0.3/0.5=0.48"])
    require("bayes reverse conditional 0.8 0.3 0.5", ["Bayes", "0.48"])
    require("independent(0.2,0.3,0.06)", ["independence", "0.2*0.3", "independent"])
    require("Events A and B have P(A)=0.4, P(B)=0.7 and P(A and B)=0.3. Find P(A given B) and decide if independent.", ["P(A|B)=0.3/0.7", "A and B are not independent"])
    require("test independence 0.2 0.3 0.07", ["independence", "not independent"])
    require("poisson(3,2)", ["Po(lambda)", "P(X=2)"])
    require("poisson(64,60)", ["Po(lambda)", "P(X=60)", "0.045266"])
    require("poisson mean 3 exactly 2", ["Po(lambda)", "P(X=2)"])
    require("poissonstats(4)", ["E(X)=lambda", "E(X) = 4", "Var(X) = 4", "sd = sqrt(lambda) = 2"])
    require("poisson distribution mean variance sd lambda 4", ["E(X)=lambda", "Var(X) = 4", "sd = sqrt(lambda) = 2"])
    require("poisson mean 3 at most 2", ["cumulative", "P(X<=2)"])
    require("poisson mean 3 at least 2", ["cumulative", "P(X>=2)"])
    require("poisson mean 4.2 fewer than 3", ["P(X<3)", "0.210237987"])
    require("A random variable X follows Poisson distribution with mean 4.2. Find P(X is fewer than 3).", ["P(X<3)", "0.210237987"])
    require("Calls arrive at a rate of 2.5 per minute. Find the probability of at least 8 calls in 3 minutes.", ["X~Po(7.5)", "P(X>=8)"])
    require("Defects occur at average rate 1.6 per metre. Find probability of no more than 5 defects in 3 metres.", ["X~Po(4.8)", "P(X<=5)"])
    require("Calls arrive at a rate of 3 per hour. Find P(2 <= X <= 5) in 1 hour.", ["X~Po(3)", "P(2<=X<=5)", "P(X<=5)-P(X<=1)"])
    require("Cars arrive at mean rate 4 per minute. Find probability more than 6 arrive in a minute.", ["X~Po(4)", "P(X>6)=1-P(X<=6)"])
    require("find P(X=2) for X~Po(3)", ["P(X=2)=e^-3*3^2/2!", "0.2240418077"])
    require("X~Po(3), find P(X>=2)", ["P(X>=2)=1-P(X<=1)", "0.8008517265"])
    require("X~Poisson(4), test at 5 percent whether lambda has increased when x=9", ["H0: lambda = 4", "Compare with alpha = 0.05", "Reject H0"])
    require("poissonnorm(64,55,70)", ["normal approximation", "mu = lambda = 64", "continuity correction", "NormalCD"])
    require("normal approximation to poisson mean 64 between 55 and 70", ["normal approximation", "sigma = sqrt(lambda)", "NormalCD"])
    require("critpoisson(3,0.05,1)", ["X ~ Po(3)", "Upper tail", "critical region"])
    require("poisson critical region lambda 3 alpha 0.05 upper", ["X ~ Po(3)", "Upper tail", "critical region"])
    require("hyppoisson(4,8,0.05,1)", ["H0: lambda = 4", "Use P(X>=8)", "Compare with alpha", "context"])
    require("poisson hypothesis test lambda 4 x 8 alpha 0.05 upper", ["H0: lambda = 4", "Use P(X>=8)", "Compare with alpha"])
    require("regress(2,0.5,10)", ["regression line", "y=7"])
    require("regress_work(2,0.5,10)", ["regression line", "y=7"])
    require("regresscalc(5,20,30,10,18,8)", ["least-squares", "xbar", "b = Sxy/Sxx", "regression line", "when x=8"])
    require("regress_work(5,20,30,10,18,8)", ["least-squares", "xbar", "b = Sxy/Sxx", "when x=8"])
    require("regression n=5 sx=20 sy=30 sxx=10 sxy=18 x=8", ["least-squares", "xbar = Sx/n", "regression line", "when x=8"])
    require("A large sample gives n=50, sum x=400, sum y=300, Sxx=120, Sxy=-48. Find the regression line of y on x.", ["xbar = Sx/n = 400/50 = 8", "b = Sxy/Sxx = -48/120", "regression line: y = 9.2 + -0.4 x"])
    require("regresss(4,6,10,18,8)", ["least-squares", "b = Sxy/Sxx", "a = ybar", "when x=8"])
    require("regression xbar=4 ybar=6 sxx=10 sxy=18 x=8", ["least-squares", "b = Sxy/Sxx", "regression line", "when x=8"])
    require("A regression line of y on x is y = 2.4x + 5. Estimate y when x=8 and explain why interpolation is safer than extrapolation.", ["Use the regression line", "y = 5 + 2.4 x", "when x=8, y=24.2"])
    require("pmcc(5,20,30,140,90,220)", ["product moment", "top =", "r ="])
    require("correlation n 5 sx 20 sy 30 sxy 140 sx2 90 sy2 220", ["product moment", "r ="])
    require("correlation n=5 sx=20 sy=30 sxy=140 sx2=90 sy2=220", ["product moment", "top =", "r ="])
    require("pmcc sxx=10 syy=40 sxy=18", ["PMCC from summary", "Sxy/sqrt"])
    require("spearman(8,12)", ["Spearman", "r_s = 1 - 6*sum(d^2)/(n(n^2-1))", "0.857142"])
    require("spearman rank correlation n=8 sumd2=12", ["Spearman", "r_s = 0.857142"])
    require("Use Spearman rank for x 1 2 3 4 5 y 5 6 6 9 10", ["average ranks for ties", "n = 5", "sum d^2 = 0.5", "r_s = 0.975"])
    require("corrtest(0.65,0.549,0)", ["H0: rho = 0", "Compare |r|", "Reject H0", "evidence of correlation"])
    require("correlation hypothesis test r=0.65 critical=0.549", ["H0: rho = 0", "Compare |r|", "Reject H0"])
    require("Given Sxx=25 Syy=16 Sxy=18 test whether correlation is significant at 5 percent with critical value 0.497.", ["r = 18 / sqrt(25*16)", "Reject H0"])
    require("The product moment correlation coefficient for a sample of 12 is r=0.62. The critical value at 5 percent is 0.497. Test whether there is positive correlation.", ["H1: rho > 0", "critical value 0.497", "Reject H0"])
    require("spearman rank correlation test r=-0.72 critical value 0.648 negative", ["H1: rho < 0", "negative tail", "Reject H0"])
    require("meanvar(5,20,90)", ["mean = Sx/n", "variance"])
    require("mean variance n 5 sx 20 sx2 90", ["mean = Sx/n", "variance"])
    require("groupmean(10,2,20,3,30,5)", ["grouped data", "sum f = 10", "sum fx", "mean = sum fx / sum f = 23", "sd ="])
    require("grouped data mean sd midpoints 10 20 30 frequencies 2 3 5", ["grouped data", "sum f = 10", "mean = sum fx / sum f = 23"])
    require("A grouped frequency table has midpoints 5, 15, 25 with frequencies 2, 3, 5. Estimate the mean and variance.", ["mean = sum fx / sum f = 18", "variance = sum fx^2/sum f - mean^2 = 61"])
    require("The grouped frequency table has classes 0-10 10-20 20-30 with frequencies 4 9 7. Estimate the mean and standard deviation.", ["For grouped data", "sum f = 20", "mean = sum fx / sum f = 16.5", "sd ="])
    require("discrete(0,0.2,1,0.5,2,0.3)", ["discrete random variable", "sum p = 1", "E(X) = 0*0.2+1*0.5+2*0.3 = 1.1", "Var(X)"])
    require("discrete random variable values 0 1 2 probabilities 0.2 0.5 0.3", ["E(X)", "1.1", "E(X^2)", "Var(X)"])
    require("discrete random variable values 1 2 3 with probabilities 0.2 0.5 0.3 find mean and variance", ["For a discrete random variable", "E(X) = 1*0.2+2*0.5+3*0.3 = 2.1", "Var(X)=E(X^2)-E(X)^2"])
    require("X has distribution x 0 1 2 3 with probabilities 0.1 0.2 0.3 0.4. Find E(X) and Var(X).", ["sum p = 1", "E(X) = 0*0.1+1*0.2+2*0.3+3*0.4 = 2", "Var(X)=E(X^2)-E(X)^2 = 1"])
    require("A discrete random variable has P(X=0)=0.2 P(X=1)=0.5 P(X=2)=0.3. Find the mean and variance.", ["E(X) = 0*0.2+1*0.5+2*0.3 = 1.1", "Var(X)=E(X^2)-E(X)^2 = 0.49"])
    require("A random variable X has cumulative distribution function F(x)=0 for x<0, x^2/9 for 0<=x<=3, 1 for x>3. Find the median.", ["F(m)=0.5", "m^2/9 = 0.5", "m = sqrt(9/2)"])
    require("The probability density function is f(x)=kx for 0<x<4. Find k and the mean.", ["total area under f(x) is 1", "k = 0.125", "mean = 2.666"])
    require("A continuous random variable has density f(x)=c*x*(4-x) for 0<x<4. find c and mean", ["f(x)=c*x*(4-x)", "c = 0.09375", "mean = 2"])
    require("The pdf is f(x)=k(x+1) for 0<x<2 find P(X>1)", ["first normalise", "k = 0.25", "P(X>1) = 0.625"])
    require("For a continuous random variable with pdf f(x)=3x^2/8 for 0<x<2 find P(X>1).", ["integral from 1 to 2", "P(X>1) = 0.875"])
    require("A continuous random variable has pdf f(x)=kx^2 for 0<x<3. Find k and P(X<1).", ["kx^2", "k = 0.111111", "P(X<1) = 0.037037"])
    require("A random variable X has pdf f(x)=kx^2 for 0<x<3. Find k and P(1<X<2).", ["k = 0.1111111111", "P(1<X<2)", "0.2592592593"])
    require("A random variable has distribution P(X=x)=kx for x=1,2,3,4. Find k and E(X).", ["k(10) = 1", "E(X)=sum xP(X=x)", "= 3"])
    require("stratified(200,50,40)", ["stratified sampling", "50/200 * 40", "10"])
    require("stratified sample population 200 group 50 sample 40", ["stratified sampling", "10"])
    require("A sample of 80 is taken from a population of 500. A stratum contains 125 people. How many should be sampled from this stratum?", ["125/500 * 80", "= 20"])
    require("groupmedian(20,15,10,5,50)", ["linear interpolation", "position = n/2", "median = 20 + ((25-15)/10)*5 = 25"])
    require("grouped median 20 cf before 15 frequency 10 class width 5 n 50", ["linear interpolation", "position = n/2", "median = 20"])
    require("For grouped data with classes 0-20 20-40 40-60 and frequencies 5 12 3 estimate the median.", ["total frequency n = 20", "median class is 20 to 40", "28.333"])
    require("groupquantile(20,15,10,5,50,0.75)", ["linear interpolation", "position = 0.75*n", "value ="])
    require("histdensity(12,4)", ["frequency density = frequency / class width", "12/4 = 3"])
    require("histfreq(3,4)", ["frequency = frequency density * class width", "3*4 = 12"])
    require("histogram frequency density 12 width 4", ["frequency density", "12/4 = 3"])
    require("histogram frequency density 4 class width 5 find frequency", ["frequency = frequency density * class width", "4*5 = 20"])
    require("A histogram has class width 5 and frequency density 3.2. Find the frequency.", ["frequency = frequency density * class width", "3.2*5 = 16"])
    require("A histogram class 10 to 20 has frequency density 3.5. Find frequency.", ["frequency = frequency density * class width", "3.5*10 = 35"])
    require("In a histogram, frequency density is 2.4 and frequency is 36 find class width", ["class width = frequency / frequency density", "36/2.4 = 15"])
    require("outliers(10,20,0,15,40)", ["1.5*IQR", "IQR = Q3 - Q1 = 20 - 10 = 10", "lower fence = -5", "upper fence = 35", "40 is an outlier"])
    require("outlier check q1=10 q3=20 values 0 15 40", ["lower fence = -5", "15 is not an outlier", "40 is an outlier"])
    require("A box plot has Q1=12 median=18 Q3=30 min=5 max=50. Check for outliers using 1.5 IQR.", ["IQR = Q3 - Q1 = 30 - 12 = 18", "5 is not an outlier", "50 is not an outlier"])
    require("For data 1,2,2,4,9,10,11 find quartiles and outliers", ["Q1 = 2, Q3 = 10", "IQR = 8", "No outliers"])
    require("uncode(3,2,20,5)", ["Y=(X-a)/b", "mean X = 20 + 5*3 = 35", "standard deviation X = |b|*standard deviation Y = 5*2 = 10"])
    require("coded data y=(x-20)/5 mean 3 sd 2", ["Y=(X-a)/b", "mean X = 20 + 5*3 = 35", "standard deviation X"])
    require("Given coded data y=(x-20)/5 has mean 3 and standard deviation 2. Find the mean and sd of x.", ["Y=(X-a)/b", "mean X = 20 + 5*3 = 35", "standard deviation X"])
    require("A random sample of 50 has coded variable y=(x-12)/3. The mean of y is 4 and standard deviation of y is 1.5. Find mean and standard deviation of x.", ["Y=(X-a)/b", "mean X = 12 + 3*4 = 24", "standard deviation X = |b|*standard deviation Y = 3*1.5 = 4.5"])
    require("Find the mean and sd of y when y=(x-10)/2, mean of x is 30 and standard deviation of x is 6.", ["For coded data Y=(X-a)/b", "mean Y = (30-10)/2 = 10", "sd Y = sd X/|b| = 6/2 = 3"])
    require("code(35,10,20,5)", ["For coded data Y=(X-a)/b", "mean Y = (35-20)/5 = 3", "sd Y = sd X/|b| = 10/5 = 2"])
    print("OK p3 engine")


if __name__ == "__main__":
    main()
