#!/usr/bin/env python3
from __future__ import annotations

KEPT_COMMANDS = [
    "abs",
    "acos",
    "approx",
    "asin",
    "atan",
    "ceil",
    "coeff",
    "cos",
    "cosec",
    "cot",
    "degree",
    "desolve",
    "diff",
    "domain",
    "dot",
    "exact",
    "energy",
    "exp",
    "factor",
    "floor",
    "connected",
    "force",
    "friction",
    "fsolve",
    "gcd",
    "integrate",
    "int",
    "implicit_diff",
    "impulse",
    "incline",
    "lcm",
    "lcoeff",
    "lift",
    "limit",
    "ln",
    "log",
    "moment",
    "partfrac",
    "power",
    "pulley",
    "product",
    "range",
    "resultant",
    "rewrite",
    "resolve",
    "round",
    "sec",
    "series",
    "simplify",
    "sin",
    "solve",
    "sqrt",
    "subst",
    "sum",
    "suvat",
    "tan",
    "taylor",
    "tcollect",
    "texpand",
    "varacc",
    "xform",
    "projectile",
    "weight",
    "work",
]

REMOVED_GROUPS = {
    "statistics_probability": [
        "stats", "stat", "statistics", "prob", "probability", "proba",
        "normalcdf", "binomcdf", "binompdf", "mean", "median", "stddev",
        "variance", "normald", "poisson", "uniformd", "comb", "perm",
        "rand", "randint", "random", "randperm", "srand",
    ],
    "matrices": [
        "matrix", "det", "trace", "transpose", "cholesky", "jordan",
        "gaussjord", "pivot", "randmatrix",
    ],
    "programs_variables_options": [
        "program", "python", "for", "while", "return", "input", "output",
        "assume", "sto", "purge", "about", "options", "option",
    ],
    "plot_graph_turtle": [
        "plot", "plotlist", "plotparam", "plotpolar", "plotseq", "funcplot",
        "graphe", "graph", "densityplot", "plotmatrix", "plot3d", "turtle",
    ],
    "crypto_and_outside_pure": [
        "crypto", "odesolve", "fft", "ifft", "read", "write",
        "cfactor", "cpartfrac", "csolve", "evalc", "egcd",
        "interp", "curl", "cross", "extend", "map", "append",
    ],
    "hidden_legacy_aliases": [
        "ceiling", "collect", "expand", "pcoeff", "proot", "trigcos",
        "trigsin", "trigtan",
    ],
}

REMOVED_COMMANDS = sorted({name for names in REMOVED_GROUPS.values() for name in names})

MENU_SIGNATURES = {
    "texpand": "texpand(e)",
    "tcollect": "tcollect(e)",
    "diff": "diff(f,var)",
    "integrate": "integrate(f,x)",
    "solve": "solve(e,x)",
    "xform": "xform(e,t)",
}
