#!/usr/bin/env python3
from __future__ import annotations

import subprocess
from pathlib import Path


REPO = Path(__file__).resolve().parents[3]
HOST = REPO / "c++" / "addin" / "host" / "build" / "casio_host"


CASES: list[tuple[str, str, list[str], list[str]]] = [
    (
        "trig",
        "sec(x)^2-tan(x)^2=1,x,0,2*pi,10,method=identity",
        ["LHS-RHS=0", "all valid x in domain"],
        ["x = []", "ERR:", "Unexpected token"],
    ),
    (
        "trig",
        "cos(2*x)+cos(x)=0,x,0,360",
        ["2*cos(3*x/2)*cos(x/2) = 0", "cos(3*x/2) = 0 => x = 60 + n*120", "cos(x/2) = 0 => x = 180 + n*360", "x = [60, 180, 300]"],
        ["Solve both factors", "ERR:"],
    ),
    (
        "trig",
        "sin(2*x)-sin(x)=0,x,0,360",
        ["sin(A)-sin(B) = 0", "sin(A)-sin(B) = 2*cos((A+B)/2)*sin((A-B)/2)", "x = [0, 60, 180, 300, 360]"],
        ["ERR:", "Unexpected token"],
    ),
    (
        "trig",
        "1/2*tan(x)-sin(x)=0,x,0,360),method=identity",
        ["Multiply by cos(x)", "0 <= x < 360", "x = [0, 60, 180, 300]"],
        ["ERR:", "Unexpected token", "360]"],
    ),
    (
        "trig",
        "sin(x)=0,x,(0,360)",
        ["0 < x < 360", "x = [180]"],
        ["ERR:", "Unexpected token", "x = [0", "360]"],
    ),
    (
        "trig",
        "sin(4*x+10)=sin(50),x,0,360,method=general",
        ["sin(A)=sin(B)", "A=B+360n=>x=10+n*90", "A=180-B+360n=>x=30+n*90", "x=10+n*90orx=30+n*90"],
        ["46.302756", "83.697243", "x = []"],
    ),
    (
        "trig",
        "tan(30-x)^2=3,x,0,360,method=general",
        ["tan(-x+30)^2=3", "tan(-x+30)=+/-sqrt(3)", "x=150+n*180", "x=90+n*180"],
        ["x = []", "ERR:"],
    ),
    (
        "trig",
        "sin(2*x)=cos(x),x,0,2*pi,method=general",
        ["sin(2A)=2sin(A)cos(A)", "cos(A)(2sin(A)-1)=0", "x=pi/2+n*pi", "x=pi/6+n*2*pi"],
        ["x = []", "Failed to isolate"],
    ),
    (
        "trig",
        "sin(5*x)+sin(3*x)=0,x,0,2*pi,method=general",
        ["sin(A)+sin(B)=2sin((A+B)/2)cos((A-B)/2)", "2sin(4*x)cos(x)=0", "x=0+n*pi/4", "x=pi/2+n*pi"],
        ["x = []", "Failed to isolate"],
    ),
    (
        "trig",
        "sin(4*theta)+sin(2*theta)=cos(theta),theta,0,pi,10,method=identity",
        ["sin(A)+sin(B)", "cos(theta)*(2*sin(3*theta)-1)=0", "theta = [pi/18, 5*pi/18, pi/2, 13*pi/18, 17*pi/18]"],
        ["theta = []", "Failed to isolate", "ERR:"],
    ),
    (
        "trig",
        "2*cos(theta)*tan(theta)=sqrt(3),theta,0,360,method=general",
        ["cos(A)tan(A)=sin(A),cos(A)!=0", "sin(A)=sqrt(3)/2", "theta=60+n*360or120+n*360"],
        ["theta = []", "Failed to isolate"],
    ),
    (
        "trig",
        "sqrt(3)*sin(x-pi/6)=sin(x),x,0,2*pi,method=general",
        ["sin(M+a)=sin(M)cos(a)+cos(M)sin(a)", "tan(x)=sqrt(3)", "x=pi/3+n*pi"],
        ["x = []", "Failed to isolate"],
    ),
    (
        "trig",
        "2*cos(x+pi/6)=sec(x+pi/2),x,0,pi,10,method=identity",
        ["2*cos(A)cos(B)=1", "cos(2*x+2/3*pi)=1/2", "x=[pi/2,5*pi/6]"],
        ["x = []", "Failed to isolate", "ERR:"],
    ),
    (
        "trig",
        "tan(pi/4-atan(t)),method=compound_angle",
        ["tan(A)=1,tan(B)=-t", "N=1-t", "D=1+t", "(1-t)/(1+t)"],
        ["N/D", "ERR:"],
    ),
    (
        "trig",
        "cos(pi-asin(8/17)+acos(5/13)),method=compound_angle",
        ["sin(U)=-140/221", "cos(U)=-171/221", "-171/221"],
        ["ERR:"],
    ),
    (
        "trig",
        "2*cos(theta+atan(t))=5*sin(theta-atan(t)),theta,0,360,10,method=compound_angle",
        ["tan(theta)=(2+5tan(A))/(5+2tan(A))", "tan(A)=t", "tan(theta)=(2+5*t)/(5+2*t)"],
        ["theta = []", "ERR:"],
    ),
    (
        "trig",
        "cos(5*x)+5*cos(3*x)+12*cos(x)=0,x,0,2*pi,10,method=identity",
        ["cos(5x)+5cos(3x)+10cos(x) = 16cos(x)^5", "16cos(x)^4+2>0", "x = [pi/2, 3*pi/2]"],
        ["x = []", "ERR:", "Unexpected token"],
    ),
    (
        "trig",
        "2*tan(theta)^2=11*sec(theta)-7,theta,0,360",
        ["tan(theta)^2=sec(theta)^2-1", "u=sec(theta)", "2u^2-11u+5=0", "cos(theta)=1/5", "theta=[78.4630409672,281.536959033]"],
        ["theta = []", "ERR:", "Unexpected token"],
    ),
    (
        "trig",
        "cot(beta)/(cosec(beta)-1)+(cosec(beta)-1)/cot(beta)=4,beta,0,360",
        ["cot(beta)/(cosec(beta)-1)=(1+sin(beta))/cos(beta)", "(cosec(beta)-1)/cot(beta)=(1-sin(beta))/cos(beta)", "lhs=2/cos(beta)=2sec(beta)", "beta=[60,300]"],
        ["beta = []", "ERR:", "Unexpected token"],
    ),
    (
        "trig",
        "sin(x)^2*tan(x)+cos(x)^2*cot(x)+2*sin(x)*cos(x)=2,x,0,360",
        ["multiplybysin(x)cos(x)", "(sin(x)^2+cos(x)^2)^2-2sin(x)cos(x)=0", "sin(2x)=1", "x=[45,225]"],
        ["x = []", "ERR:", "Unexpected token"],
    ),
    (
        "trig",
        "cosec(x)/sin(x)^3,method=auto",
        ["cosec(x)*sin(x)^-3=cosec(x)^4", "cosec(x)^4"],
        ["Answer:cosec(x)*sin(x)^-3", "ERR:"],
    ),
    (
        "trig",
        "(1-sin(x)^2)/sin(x)^2,method=auto",
        ["1-sin(u)^2=cos(u)^2", "cot(x)^2"],
        ["Answer:(-sin(x)^2+1)*sin(x)^-2", "ERR:"],
    ),
    (
        "trig",
        "cot(theta)*sec(theta),method=auto",
        ["cot(theta)*sec(theta)=cosec(theta)", "cosec(theta)"],
        ["Answer:cot(theta)*sec(theta)", "ERR:"],
    ),
    (
        "alg",
        "solve(z^6=1,z)",
        ["z^6 = 1", "k = 0, 1, ..., 5", "z = [1, e^(pi/3*i), e^(2*pi/3*i), -1"],
        ["base = 1 or exponent = 0", "z = [1]", "ERR:"],
    ),
    (
        "alg",
        "factor(k^3-9*k^2+24*k-16)",
        ["= (k - 1)*(k - 4)^2", "(k - 1)*(k - 4)^2"],
        ["numeric coeffs needed", "ERR:"],
    ),
    (
        "alg",
        "coeff((1+x/2)^7,x,1)",
        ["Term in x^1", "Coefficient = 7/2"],
        ["Unexpected token", "ERR:"],
    ),
    (
        "alg",
        "coeff((1+2/x)^2*(1+x/2)^7,x,1)",
        ["x^1 terms:", "4*x^-2", "35/8*x^3", "Coefficient = 42"],
        ["Unexpected token", "ERR:"],
    ),
    (
        "alg",
        "coeff(2/x+3*x,x,-1)",
        ["x^-1 terms:", "2*x^-1", "Coefficient = 2"],
        ["Unexpected token", "ERR:"],
    ),
    (
        "alg",
        "solve(z^6+64=0,z)",
        ["z^6 = -64", "z = 2*e^((pi+2*k*pi)*i/6)", "2*e^(11*pi/6*i)"],
        ["z = []", "No real solution", "ERR:"],
    ),
    (
        "alg",
        "2*sqrt(2)/(sqrt(3)-1)-2*sqrt(3)/(sqrt(2)+1)",
        ["*(1 + sqrt(3))", "*(-1 + sqrt(2))", "sqrt(2) + 2*sqrt(3) - sqrt(6)"],
        ["ERR:", "Answer:"],
    ),
    (
        "alg",
        "simplify((a+2*((a+2*2)/2))/((a+2*2)/2))",
        ["(4*a + 8)/(a + 4)", "4*(a + 2)/(a + 4)"],
        ["ERR:", "Domain:"],
    ),
    (
        "alg",
        "solve(log(2,x)+log(4,x)=6,x)",
        ["u = log(2,x)", "log(4,x) = u/2", "x = 16"],
        ["ERR:", "Unexpected token"],
    ),
    (
        "alg",
        "evalat(e^x*(sin(2*x)+2*cos(2*x)),x,pi)",
        ["x=pi", "f(pi)=2*e^(pi)"],
        ["46.281", "ERR:"],
    ),
    (
        "alg",
        "range(1/(x+1),x>4)",
        ["y*(x+1)=1", "x*y=-y+1", "Range:0<y<1/5"],
        ["x(y)", "y(x", "ERR:"],
    ),
    (
        "alg",
        "solve(300-280*e^(-0.05*t)=250-230*e^(-0.1*t),t>0)",
        ["t=0rejectedbydomain", "t=20*ln(23/5)", "t=[20*ln(23/5)]"],
        ["t = [0,", "ERR:"],
    ),
    (
        "alg",
        "solve((2-log(4,x^7))/(7-log(4,x^2))+(log(4,x))^2=0,x)",
        ["u = log(4,x)", "log(4,x^7) = 7*u", "2*u - 7 != 0", "2*u^3", "u = 1/2", "x = [2, 4, 16]"],
        ["log_b(A)-log_b(B)", "x ~= 2.000", "ERR:"],
    ),
    (
        "alg",
        "solve(log(sin(x)*cos(x),sin(x))*log(sin(x)*cos(x),cos(x))=1/4,x)",
        ["Domain: sin(x) > 0, cos(x) > 0", "A*B = 1/4", "A + B = 1", "tan(x) = 1", "x = pi/4 + 2*pi*n"],
        ["x = []", "ERR:"],
    ),
    (
        "alg",
        "solve([log(2,x*y^2)=0,log(2,x^2*y)=3],[x,y])",
        ["Domain: x > 0, y > 0", "X + 2*Y = 0", "2*X + Y = 3", "x = 4", "y = 1/2", "(x,y) = [(4,1/2)]"],
        ["solve([log", "ERR:"],
    ),
    (
        "alg",
        "coeff(((y+16)/4)^5,y,2)",
        ["Term in y^2", "Coefficient = 40"],
        ["Unexpected token", "ERR:"],
    ),
    (
        "alg",
        "coeff((sqrt(2)*z-2)^5*(sqrt(2)*z+2)^5,z,8)",
        ["B1 = (sqrt(2)*z - 2)^5", "Coefficient = -320"],
        ["Unexpected token", "Coefficient = -20*sqrt(2)^8", "ERR:"],
    ),
    (
        "alg",
        "coeff((3*x-2)*(x+4)*(x+k),x,2)",
        ["Coefficient = sum x powers adding to 2", "Coefficient = 3*k + 10"],
        ["Unexpected token", "ERR:"],
    ),
    (
        "alg",
        "solve(24*k^2=384*k,k,k!=0)",
        ["k != 0", "k = 0 rejected by k != 0", "k = [16]"],
        ["k = [0, 16]", "ERR:"],
    ),
    (
        "alg",
        "solve(10*1.2^(n-1)>1000,n)",
        ["10*(6/5)^(n - 1) > 1000", "(6/5)^(n - 1) > 100", "n integer => n >= 27"],
        ["(506/5)^(n - 1)", "ERR:"],
    ),
    (
        "alg",
        "solve(x-16*sqrt(2)/x^2=0,x)",
        ["x^3 = 16*sqrt(2)", "x = 2*sqrt(2)", "x = [2*sqrt(2)]"],
        ["(16*sqrt(2))^(1/3)", "ERR:"],
    ),
    (
        "trig",
        "12+3*sin(pi*t/6)=10,t,12,24,8,method=identity",
        ["pi*t/6 = alpha + 2*pi*n", "t = [19.3936771632, 22.6063228368]"],
        ["pi*t/6 = alpha + 360n", "ERR:"],
    ),
    (
        "alg",
        "solve([a+a*r=240,a+a*r^2=200],[a,r])",
        ["(1+r^2)/(1+r) = 5/6", "240*r^2 - 200*r + 40 = 0", "S_inf = [270, 320]"],
        ["solve([a", "ERR:"],
    ),
    (
        "alg",
        "solve([19000=A*10^(3*k),38000=A*10^(6*k)],[A,k])",
        ["10^(3*k) = 2", "k = ln(2)/(3*ln(10))", "A = 19000/2 = 9500"],
        ["solve([19000", "ERR:"],
    ),
    (
        "alg",
        "solve([2*r+r*theta=23,1/2*r^2*theta=15],[r,theta])",
        ["r*theta = 23 - 2*r", "2*r^2 - 23*r + 30 = 0", "3/10", "(r,theta) = [(10,3/10)]"],
        ["solve([2*r", "ERR:"],
    ),
    (
        "alg",
        "solve([a+a*r=40,a+a*r+a*r^2+a*r^3=130],[a,r])",
        ["(1-r^4)/(1-r^2) = 13/4", "4*r^4 - 13*r^2 + 9 = 0", "S_5 = [-275, 211]"],
        ["solve([a", "ERR:"],
    ),
    (
        "alg",
        "expand((1+x-x^2)^6)",
        ["x^12 - 6*x^11", "- 10*x^3", "9*x^2 + 6*x + 1"],
        ["base must be ax+b", "ERR:"],
    ),
    (
        "alg",
        "solve([x*y=28,x^2+y^2=65],[x,y])",
        ["(x+y)^2 = 65 + 2*28 = 121", "(x-y)^2 = 65 - 2*28 = 9", "(x,y) = [(4,7), (7,4), (-7,-4), (-4,-7)]"],
        ["solve([x*y", "ERR:"],
    ),
    (
        "alg",
        "solve([a^2+b^2=r^2,(8-a)^2+b^2=r^2,a^2+(6-b)^2=r^2],[a,b,r])",
        ["Subtract first: 16*a = 64", "Subtract first: 12*b = 36", "a = 4", "b = 3", "r = 5"],
        ["solve([a^2", "ERR:"],
    ),
    (
        "alg",
        "expand((4*x+1/(k*x))^7)",
        ["T_r = C(7,r)", "21504*x^3/(k^2)", "1/(k^7*x^7)"],
        ["symbolic expansion too large", "ERR:"],
    ),
    (
        "alg",
        "solve(ln(2*w+1)=1+ln(w-1),w)",
        ["ln((2*w + 1)/(w - 1)) = 1", "(2*w + 1)/(w - 1) = e", "w = [(e + 1)/(e - 2)]"],
        ["w = 5.176", "log_b(A)", "ERR:"],
    ),
    (
        "alg",
        "solve(2*ln(x)=6,x)",
        ["ln(x)=3", "x=e^(3)", "x=[e^(3)]"],
        ["20.085", "log_b(A)", "ERR:"],
    ),
    (
        "alg",
        "solve(ln(x)+2*ln(x)=5,x)",
        ["3ln(x)=5", "ln(x)=5/3", "x=e^(5/3)", "x=[e^(5/3)]"],
        ["5.294", "log_b(A)", "ERR:"],
    ),
    (
        "alg",
        "solve(4^(3*p-1)=5^210,p)",
        ["2*(3*p - 1)*ln(2) = 210*ln(5)", "p = (210*ln(5) + 2*ln(2))/(6*ln(2))"],
        ["ln(-", "ERR:"],
    ),
    (
        "alg",
        "solve(log(a)-log(b)=log(a-b),a)",
        ["ln(a) - ln(b) = ln(a - b)", "Domain: a - b > 0", "a - b*(a - b) = 0", "a = -b^2/(- b + 1)"],
        ["symbolic parameters unsupported", "No real solution", "ERR:"],
    ),
    (
        "alg",
        "solve(log(2,x^2+4*x+3)=4+log(2,x^2+x),x)",
        [
            "log(2,(x^2 + 4*x + 3)/(x^2 + x)) = 4",
            "(x^2 + 4*x + 3)/(x^2 + x) = 16",
            "5*x^2 + 4*x - 1 = 0",
            "x = -1 rejected by domain",
            "x = [1/5]",
        ],
        ["Rearrange to lhs-rhs=0", "combine log terms", "Exponentiate, solve", "x = 0.2", "ERR:"],
    ),
    (
        "alg",
        "solve((x^2-16)/(x-4)=13,x)",
        [
            "Domain: x - 4 != 0",
            "x^2 - 16 = (x - 4)*(x + 4)",
            "(x^2 - 16)/(x - 4) = x + 4, x - 4 != 0",
            "x + 4 = 13",
            "x = 4 rejected by domain",
            "9 != 4",
            "x = [9]",
        ],
        ["expand => x^2 - 13*x + 36 = 0", "x = (-b +/- sqrt", "ERR:"],
    ),
    (
        "alg",
        "solve((3*x+2)^2=9*x^2+12*x+11,x)",
        ["9*x^2 + 12*x + 4 = 9*x^2 + 12*x + 11", "4 != 11", "-7 != 0", "x = []"],
        ["ERR:"],
    ),
    (
        "alg",
        "solve(sqrt(2*x+3)=x-1,x)",
        ["2*x + 3 >= 0 => x >= -3/2", "x - 1 >= 0 => x >= 1", "2*x + 3 = (x - 1)^2", "x = 2 - sqrt(6) rejected by domain", "Answer: x = [2 + sqrt(6)]"],
        ["4.449", "ERR:"],
    ),
    (
        "alg",
        "solve(x+9=3*sqrt(x),x)",
        ["u = sqrt(x), u >= 0", "u^2 - 3*u + 9 = 0", "No real solution", "x = []"],
        ["sqrt(3)*i)^2", "ERR:"],
    ),
    (
        "alg",
        "solve((2*x+1)^2=4,x)",
        ["(2*x + 1)^2 = 4", "2*x + 1 = +/-2", "x = [1/2, -3/2]"],
        ["LHS - RHS", "x + 1/2 = +/-1", "ERR:"],
    ),
    (
        "alg",
        "x^2+36/x^2=12,method=auto",
        ["Domain: x != 0", "Multiply by x^2", "x^4 - 12*x^2 + 36 = 0", "u = x^2", "u = 6", "x = sqrt(6)", "x = -sqrt(6)"],
        ["LHS-RHS = 0", "x = []", "ERR:"],
    ),
    (
        "alg",
        "inverse((5*x+2)/(5*x+2))",
        ["y = f(x) = (5*x + 2)/(5*x + 2)", "5*x + 2 != 0", "y = 1", "f^-1(x) = no inverse on all real x"],
        ["ERR:"],
    ),
    (
        "derive",
        "sec(x)+cot(x)+csc(x),x",
        ["d/dx(sec(x)) = sec(x)*tan(x)", "d/dx(cot(x)) = -cosec(x)^2", "d/dx(cosec(x)) = -cosec(x)*cot(x)"],
        ["ERR:", "Unexpected token"],
    ),
    (
        "derive",
        "cosec(x)^2-cot(x)^2,x,method=auto",
        ["cosec(u)^2 - cot(u)^2 = 1", "Domain: sin(x) != 0", "dy/dx = 0"],
        ["y = cosec", "ERR:", "Unexpected token"],
    ),
    (
        "int",
        "acos((x-1)/3)",
        ["Use parts", "w=(x - 1)/3", "sqrt term = sqrt", "+ C"],
        ["sqrt(1-w^2) = -", "Answer: int(", "Classify the integrand", "ERR:", "Unexpected token"],
    ),
    (
        "int",
        "asin((x-1)/3)",
        ["Use parts", "w=(x - 1)/3", "sqrt term = sqrt", "+ C"],
        ["sqrt(1-w^2) =", "Answer: int(", "Classify the integrand", "ERR:", "Unexpected token"],
    ),
    (
        "int",
        "de_solve(dh/dt=(1/50)*h*(2*h-1)*cos(t/10),h(0)=5/2)",
        ["1/(h*(2*h - 1)) dh = 1/50*cos(t/10) dt", "C = ln(8/5)", "(2*h - 1)/h = 8/5*e^(sin(t/10)/5)", "h = 5/(10 - 8*e^(sin(t/10)/5))"],
        ["Try dy/dx", "unsupported DE route", "dh = []", "ERR:"],
    ),
    (
        "int",
        "de_solve(dr/dt=-k/r^2,r(0)=40,r(5)=20)",
        ["r^2 dr = -k dt", "r^3/3 = -k*t + C", "C = 64000/3", "8000/3 = -5*k + 64000/3", "k = 11200/3"],
        ["Try dy/dx", "unsupported DE route", "Err:"],
    ),
    (
        "int",
        "de_solve(dy/dx=(x^2+1)*(y+3),y(0)=1)",
        ["1/(y + 3) dy = x^2 + 1 dx", "C = ln(4)", "y + 3 = 4*e^(x^3/3 + x)", "y = 4*e^(x^3/3 + x) - 3"],
        ["Try dy/dx", "unsupported DE route", "ERR:"],
    ),
    (
        "int",
        "de_solve(dz/dx=(exp(x)+1)/(z+2),z(0)=3)",
        ["z + 2 dz = e^(x) + 1 dx", "C = 19/2", "z^2/2 + 2*z = e^(x) + x + 19/2"],
        ["Try dy/dx", "unsupported DE route", "ERR:"],
    ),
    (
        "int",
        "de_solve(dy/dx+2*x*y=x,y(0)=3)",
        ["dy/dx + p*y = q", "p = 2*x", "mu = e^Int(p dx)", "d/dx[e^(x^2)*y] = e^(x^2)*x", "C = 5/2"],
        ["Try dy/dx", "unsupported DE route", "ERR:"],
    ),
    (
        "int",
        "de_solve(x*dy/dx+2*y=x^3,x=1,y=4)",
        ["p = 2/x", "mu = x^2", "d/dx[x^2*y] = x^4", "C = 19/5", "y = (x^5/5 + 19/5)/(x^2)"],
        ["Try dy/dx", "unsupported DE route", "ERR:"],
    ),
    (
        "int",
        "de_solve(dy/dx+tan(x)*y=sin(x),y(0)=1)",
        ["p = tan(x)", "mu = cos(x)^-1", "d/dx[cos(x)^-1*y] = tan(x)", "C = 1"],
        ["Try dy/dx", "unsupported DE route", "ERR:"],
    ),
    (
        "int",
        "de_solve(cos(x)*dy/dx+y*sin(x)=e^(2*x)*cos(x)^2)",
        ["p = tan(x)", "q = e^(2*x)*cos(x)", "d/dx[cos(x)^-1*y] = e^(2*x)", "y = (1/2*e^(2*x) + C)*cos(x)"],
        ["Try dy/dx", "unsupported DE route", "Err:"],
    ),
    (
        "int",
        "de_solve((1+t)*dP/dt+P=t^2*(1+t),P(0)=5)",
        ["dP/dt + p*P = q", "p = 1/(t + 1)", "q = t^2", "d/dt[(t + 1)*P] = (t + 1)*t^2", "P = (t^4/4 + t^3/3 + 5)/(t + 1)"],
        ["Err: RHS Int", "t + P", "d/dx["],
    ),
    (
        "int",
        "de_solve((t+2)*dv/dt+3*v=k*(t+2)-3,v(0)=0)",
        ["dv/dt + p*v = q", "p = 3/(t + 2)", "q = (k*(t + 2) - 3)/(t + 2)", "d/dt[((t + 2)^3)*v] = (t + 2)^2*(k*(t + 2) - 3)", "C = - 4*k + 8"],
        ["Err: RHS Int", "32*t + 40*t^2", "d/dx["],
    ),
    (
        "int",
        "de_solve(dh/dt=3/2*h*sin(3*t/4),h(0)=1)",
        ["1/h dh = 3/2*sin(3*t/4) dt", "C = 2", "h = e^(- 2*cos(3*t/4) + 2)"],
        ["unsupported DE route", "ERR:"],
    ),
    (
        "int",
        "de_solve(100*d2x/dt2+60*dx/dt+13*x=26)",
        ["100*m^2 + 60*m + 13 = 0", "m = -3/10 +/- 1/5*i", "x_p = 2", "x = 2 + e^(-3/10*t)*(A*cos(1/5*t) + B*sin(1/5*t))"],
        ["Err: second-order DE unsupported", "d2x = ", "Int(1) d2x", "2x ="],
    ),
    (
        "int",
        "de_solve(d2x/dt2-4*dx/dt+5*x=0)",
        ["m^2 - 4*m + 5 = 0", "m = 2 +/- i", "x = e^(2*t)*(A*cos(t) + B*sin(t))"],
        ["Err: second-order DE unsupported", "d2x = ", "Int(1) d2x"],
    ),
    (
        "int",
        "de_solve(d2y/dx2-5*dy/dx+6*y=0)",
        ["m^2 - 5*m + 6 = 0", "m = 3, 2", "y = A*e^(3*x) + B*e^(2*x)"],
        ["Err: second-order DE unsupported", "d2y = "],
    ),
    (
        "int",
        "de_solve(2*d2w/dt2-5*dw/dt+2*w=450*e^(-t))",
        ["2*m^2 - 5*m + 2 = 0", "m = 2, 1/2", "Try w_p = k*e^(-t)", "k = 50", "w = A*e^(2*t) + B*e^(1/2*t) + 50*e^(-t)"],
        ["Err: second-order DE unsupported", "No elementary primitive", "Int(450*e^(-t))"],
    ),
    (
        "int",
        "de_solve(3*d2x/dt2+4*dx/dt+x=200*cos(t))",
        ["3*m^2 + 4*m + 1 = 0", "Try x_p = p*cos(t) + q*sin(t)", "-2*p + 4*q = 200", "-4*p - 2*q = 0", "p = -20, q = 40", "40*sin(t) - 20*cos(t)"],
        ["Err: second-order DE unsupported", "No elementary primitive"],
    ),
    (
        "alg",
        "solve(2*x=tanh(ln(sqrt(2-3*x))),x)",
        ["atanh(2*x) = ln(sqrt(- 3*x + 2))", "6*x^2 - 9*x + 1 = 0", "rejected by domain", "x = [3/4 - sqrt(57)/12]"],
        ["x = []", "log_b(A)-log_b(B)"],
    ),
    (
        "int",
        "mean_value(1/sqrt(4*x^2+9),x,0,3)",
        ["u = 2/3*x", "Int(1/sqrt(u^2+1)) du = asinh(u)", "1/6*ln(sqrt(5) + 2)"],
        ["No elementary primitive", "1*Int"],
    ),
    (
        "alg",
        "solve(31*cosh(x)-4*cosh(2*x)=0,x)",
        ["cosh(2*x) = 2*cosh(x)^2 - 1", "8*u^2 - 31*u - 4 = 0", "reject u = -1/8", "x = [ln(4 - sqrt(15)), ln(4 + sqrt(15))]"],
        ["x = []", "ERR:"],
    ),
    (
        "int",
        "defint(x*atan(4*x),x,0,sqrt(3)/4)",
        ["u = atan(4*x), dv = x dx", "F(sqrt(3)/4) = 1/24*pi - sqrt(3)/32", "1/24*pi - 1/32*sqrt(3)"],
        ["atan(sqrt(3))", "ERR:"],
    ),
    (
        "int",
        "de_solve(d2y/dx2-4*dy/dx+4*y=0)",
        ["m^2 - 4*m + 4 = 0", "m = 2 repeated", "y = (A + B*x)*e^(2*x)"],
        ["Err: second-order DE unsupported", "d2y = "],
    ),
    (
        "alg",
        "solve(5/(10-8*e^(k*sin(t/10)))=5/(10-8*e^(sin(t/10)/5)),k)",
        ["e^(k*sin(t/10)) = e^(sin(t/10)/5)", "k*sin(t/10) = sin(t/10)/5", "k = 1/5"],
        ["k = []", "No real solution", "ERR:"],
    ),
    (
        "alg",
        "solve(1/5*sin(t/10)=k*sin(t/10),k)",
        ["sin(t/10) != 0", "k = 1/5"],
        ["all real values in domain", "k = []", "ERR:"],
    ),
    (
        "alg",
        "solve(e^(2*x+1)=e^(x-3),x)",
        ["e^(2*x+1)=e^(x-3)", "2*x+1=x-3", "x+4=0", "x=-4"],
        ["all real values in domain", "ERR:"],
    ),
    (
        "alg",
        "solve(e^(x+1)=17,x)",
        ["e^(x+1)=17", "x+1=ln(17)", "x=ln(17)-1"],
        ["1.833", "x=[", "ERR:"],
    ),
    (
        "alg",
        "solve(e^x+8*e^(-x)=6,x)",
        ["u=e^(x),u>0", "u+8/u-6=0", "-6*u+u^2+8=0", "x=[ln(2),ln(4)]"],
        ["0.693", "1.386", "all real values in domain", "ERR:"],
    ),
    (
        "alg",
        "solve(4*e^(-2*x)-e^(-4*x)=0,x)",
        ["Dividebye^(-4*x)>0", "e^(2*x)=1/4", "x=[-ln(2)]"],
        ["all real values in domain", "No real solution", "ERR:"],
    ),
    (
        "alg",
        "solve(2*e^x=e^(x+1),x)",
        ["e^(x)(-e+2)=0", "e^(x)>0", "-e+2!=0", "x=[]"],
        ["all real values in domain", "log_a", "ERR:"],
    ),
    (
        "alg",
        "solve(e^(x^2)=e^(2*x),x)",
        ["e^(x^2)=e^(2*x)", "x^2=2*x", "x^2-2*x=0", "x=[0,2]"],
        ["all real values in domain", "ERR:"],
    ),
    (
        "alg",
        "range(sqrt(abs(3*x+1)+1))",
        ["abs(3*x + 1) >= 0", "Answer: y >= 1"],
        ["inspect graph/transform", "ERR:", "Unexpected token"],
    ),
    (
        "alg",
        "domain(log(abs(2*x-3)+2))",
        ["abs(2*x - 3) + 2 > 0", "abs(2*x - 3) >= 0", "abs(2*x - 3) + 2 >= 2 > 0", "Answer: all real x"],
        ["Answer: abs(2*x - 3) + 2 > 0", "ERR:"],
    ),
    (
        "alg",
        "domain(ln((x-1)/(x+2)))",
        ["(x - 1)/(x + 2) > 0, x + 2 != 0", "x - 1 = 0 => x = 1, x + 2 = 0 => x = -2", "-2, 1 => x < -2 or x > 1", "x < -2 or x > 1"],
        ["Answer: (x - 1)/(x + 2) > 0", "ERR:"],
    ),
    (
        "alg",
        "ln(abs(x)+2)=0,method=auto",
        ["abs(x) + 2 = e^0", "abs(x) + 2 = 1", "abs(x) = -1", "abs(x) >= 0", "x = []"],
        ["log_b(A)-log_b(B)", "|A| = B =>", "No real solution", "ERR:"],
    ),
    (
        "alg",
        "log(10,abs(x+5)+3)=0,method=auto",
        ["abs(x + 5) + 3 = 10^0", "abs(x + 5) + 3 = 1", "abs(x + 5) = -2", "x = []"],
        ["log_b(A)-log_b(B)", "|A| = B =>", "ERR:"],
    ),
    (
        "alg",
        "log(3,x^2+2)=0,method=auto",
        ["x^2 + 2 = 3^0", "x^2 + 2 = 1", "x^2 + 1 = 0", "b^2 - 4ac = -4 < 0", "x = []"],
        ["(0 + sqrt(4)*i)/2", "Answer:", "ERR:"],
    ),
    (
        "derive",
        "ln(x+y)=x*y,x,method=implicit",
        ["d/dx[ln(x + y)] = (1 + dy/dx)/(x + y)", "d/dx[x*y] = y + x*dy/dx", "(1 + dy/dx)/(x + y) = y + x*dy/dx", "dy/dx*(1 - x*(x + y)) = y*(x + y) - 1", "dy/dx = (y*(x + y) - 1)/(1 - x*(x + y))"],
        ["F_x", "F_y", "Answer: d/dx(", "Unexpected token", "ERR:"],
    ),
    (
        "derive",
        "x^y=y^x,x,method=implicit",
        ["ln(x^y)=ln(y^x)", "y*ln(x)=x*ln(y)", "dy/dx*ln(x)-x*dy/dx/y=ln(y)-y/x", "dy/dx=(ln(y)-y/x)/(ln(x)-x/y)", "dy/dx = y*(x*ln(y) - y)/(x*(y*ln(x) - x))"],
        ["F_x", "F_y", "-F_x/F_y", "Unexpected token", "ERR:"],
    ),
    (
        "derive",
        "sin(x*y)+x^2=y^2,x,method=implicit",
        ["F_x + F_y*dy/dx = 0", "(cos(x*y)*y + 2*x) + (cos(x*y)*x - 2*y)*dy/dx = 0", "(cos(x*y)*x - 2*y)*dy/dx = -(cos(x*y)*y + 2*x)", "dy/dx = -(cos(x*y)*y + 2*x)/(cos(x*y)*x - 2*y)", "dy/dx = (y*cos(x*y) + 2*x)/(2*y - x*cos(x*y))"],
        ["dy/dx = -F_x/F_y", "Answer: d/dx(", "Unexpected token", "ERR:"],
    ),
    (
        "derive",
        "arccos(cos(2*x+pi/6)),x,method=auto",
        ["u = cos(2*x + pi/6)", "du/dx = -2*sin(2*x + pi/6)", "dy/dx = -du/dx/sqrt(1-u^2)"],
        ["Use quotient rule", "Answer: d/dx(", "Unexpected token", "ERR:"],
    ),
    (
        "derive",
        "log(abs(3*x+1)+2),x,method=auto",
        ["u = abs(3*x + 1) + 2", "du/dx = 3*(3*x + 1)/abs(3*x + 1)", "dy/dx = du/dx/u", "d(abs(u))/dx = u/abs(u)*du/dx"],
        ["Use product rule", "Answer: d/dx(", "Unexpected token", "ERR:"],
    ),
    (
        "derive",
        "ln((x-1)/(x+2)),x",
        ["u = (x - 1)/(x + 2)", "Domain: x < -2 or x > 1", "u' = ((1)*(x + 2)-(x - 1)*(1))/(x + 2)^2", "u' = 3/(x + 2)^2", "dy/dx = [3/(x + 2)^2]/[(x - 1)/(x + 2)]", "dy/dx = 3/((x + 2)*(x - 1))"],
        ["Answer: d/dx(", "Unexpected token", "ERR:"],
    ),
    (
        "derive",
        "ln(x),x",
        ["y = ln(x)", "dy/dx = 1/x"],
        ["y = log(x)", "ERR:"],
    ),
    (
        "derive",
        "log((3*x+1)^2+2)*log(3,x^2+12)*7!,x",
        ["c = 5040", "f1 =", "f1' =", "f2 =", "f2' =", "dy/dx = c*(f1'*f2 + f1*f2')"],
        ["Answer: d/dx(", "Unexpected token", "ERR:"],
    ),
    (
        "derive",
        "(abs(2*x+1))*(cot(3*x^2+5)+1)*(sin((x+1)^2)+cos((x+1)^2))*(7*x-2)^3*ln(e^(x+3)+3),x",
        ["f1 = abs(2*x + 1)", "f3' = 2*cos((x + 1)^2)*(x + 1) - 2*sin((x + 1)^2)*(x + 1)", "f5' = 1/(e^(x + 3) + 3)*e^(x + 3)", "dy/dx = f1'*f2*f3*f4*f5 +"],
        ["sum(f_i'", "...", "Answer: d/dx(", "Unexpected token", "ERR:"],
    ),
    (
        "derive",
        "x=t^2+1/t,y=t^2-1/t,t,x,method=param",
        ["dx/dt", "dy/dt", "dy/dx=(dy/dt)/(dx/dt)", "dy/dx"],
        ["Answer: d/dx(", "Unexpected token", "ERR:"],
    ),
    (
        "derive",
        "mode:3,t^2+4*t,t^2-3*t^2,t",
        ["dy/dt = 2*t - 6*t", "dy/dt = -4*t", "dy/dx = (-4*t)/(2*t+4)", "dy/dx = -2*t/(t + 2)"],
        ["Answer: d/dx(", "Unexpected token", "ERR:"],
    ),
    (
        "derive",
        "mode:3,t^2+1/t,t^2-1/t,t",
        ["dy/dx = (2*t + t^-2)/(2*t - t^-2)", "dy/dx = ((2*t + t^-2)*t^2)/((2*t - t^-2)*t^2)", "dy/dx = (2*t^3 + 1)/(2*t^3 - 1)"],
        ["Answer: d/dx(", "Unexpected token", "ERR:"],
    ),
    (
        "alg",
        "x^2-5*x+6=0,method=factor",
        ["(x - 2)", "(x - 3)", "x = 3", "x = 2"],
        ["Range:", "Answer: x^2 - 5*x + 6", "ERR:"],
    ),
    (
        "alg",
        "solve([x^2+x*y+y^2=37,x+y+x*y=19],[x,y])",
        ["s=x+y,p=xy", "x^2+xy+y^2=s^2-p", "(x,y) = (3,4) or (4,3)"],
        ["Only one '=' supported", "ERR:"],
    ),
    (
        "alg",
        "solve([2*(2)^3+a*(2)^2+b*2+c=0,2*(-1)^3+a*(-1)^2+b*(-1)+c=0,2*(1)^3+a*(1)^2+b*1+c=-14],[a,b,c])",
        ["a = 3", "b = -9", "c = -10", "(a,b,c) = [(3,-9,-10)]"],
        ["solve([", "ERR:"],
    ),
    (
        "alg",
        "expand((x-1)^3-4*(x-1)+1)",
        ["(x - 1)^3 - 4*(x - 1) + 1", "x^3 - 3*x^2 - x + 4"],
        ["Answer:", "ERR:"],
    ),
    (
        "derive",
        "x^4-4*x,x,2,method=first_principles",
        ["[f(2+h)-f(2)]/h", "f(2+h)-f(2) = h^4 + 8*h^3 + 24*h^2 + 28*h", "f'(2) = 28"],
        ["No first-principles route", "ERR:"],
    ),
    (
        "alg",
        "solve([log(2,y-1)=1+log(2,x),2*log(3,y)=2+log(3,x)],[x,y])",
        ["y - 2*x - 1 = 0", "y^2 - 9*x = 0", "(x,y) = [(1,3), (1/4,3/2)]"],
        ["solve([log", "ERR:"],
    ),
    (
        "alg",
        "solve(4*pi*r-660/r^2=0,r)",
        ["r^3 = 165/pi", "r = (165/pi)^(1/3)", "r = [(165/pi)^(1/3)]"],
        ["r = [3.744", "ERR:"],
    ),
    (
        "alg",
        "domain(csc(2*x+pi/6)^2-cot(2*x+pi/6)^2)",
        ["sin(2*x + pi/6) != 0", "Answer:"],
        ["Answer: all real x", "ERR:"],
    ),
    (
        "alg",
        "domain(1-cos(2*x+pi/6)^2)",
        ["1 - cos(2*x + pi/6)^2 = sin(2*x + pi/6)^2", "Domain: all real x", "Answer: all real x"],
        ["ERR:", "Unexpected token"],
    ),
    (
        "alg",
        "range(cot(x^2-pi/4)^2+1)",
        ["Answer: y >= 1"],
        ["inspect graph/transform", "ERR:"],
    ),
    (
        "int",
        "atan(tan(x^2-pi/4))",
        ["branch"],
        ["Answer: int(", "Classify the integrand", "ERR:"],
    ),
    (
        "int",
        "asin((x-3)/8),method=parts",
        ["Use parts", "u=asin(w)", "dv=dw", "du=1/sqrt(1-w^2) dw", "v=w", "Answer:"],
        ["Classify the integrand", "ERR:"],
    ),
    (
        "int",
        "e^(2*x)*cos(5*x),method=parts",
        ["u = cos(5*x)", "dv = e^(2*x) dx", "du = -5*sin(5*x) dx", "v = e^(2*x)/2", "29/4*I"],
        ["IBP missing", "ERR:"],
    ),
    (
        "int",
        "4*x^3*sqrt(x^4+1)/(1+sqrt(x^4+1))",
        ["u = sqrt(x^4+1)", "u^2 = x^4+1", "I = 2*Int(u^2/(u+1)) du", "x^4 - 2*sqrt(x^4 + 1) + 2*ln(abs(1 + sqrt(x^4 + 1))) + C"],
        ["2/3*(x^4 + 1)^(3/2)", "No elementary primitive found", "ERR:"],
    ),
    (
        "int",
        "defint((x+1)/(2*x-1)^(3/2),x,1,5)",
        ["u = 2*x - 1", "F(5) = 1", "F(1) = -1", "2"],
        ["9^(-1/2)", "No elementary primitive found", "ERR:"],
    ),
    (
        "int",
        "(5*x+7)/((x-1)*(x^2+4)),method=pf",
        ["A/(x-1)+(Bx+C)/(x^2+4)", "A=12/5", "B=-12/5", "C=13/5", "Answer:"],
        ["Partial fractions: A/(x+p)", "ERR:"],
    ),
    (
        "int",
        "(3*x^2+5*x+7)/((x-1)^2*(x^2+1)),method=pf",
        ["A/(x-1)+B/(x-1)^2+(Cx+D)/(x^2+1)", "coefficient equations", "Answer:"],
        ["No elementary primitive found", "ERR:"],
    ),
    (
        "int",
        "(x^2+1)/(x^4+x^2+1),method=sub",
        ["N,D / x^2", "u=x-1/x", "du=(1+1/x^2) dx"],
        ["No elementary primitive found", "ERR:"],
    ),
    (
        "int",
        "(x^2-1)/(x^4+1),method=sub",
        ["u^2-2=(u-sqrt(2))(u+sqrt(2))", "A=1/(2*sqrt(2))", "B=-1/(2*sqrt(2))", "ln(abs((x + 1/x - sqrt(2))/(x + 1/x + sqrt(2))))"],
        ["No elementary primitive found", "ERR:"],
    ),
    (
        "int",
        "(x^2+1)/(x^4+1),method=pf",
        ["Use partial fractions", "x^4+1=(x^2+sqrt(2)*x+1)(x^2-sqrt(2)*x+1)", "Ax+B", "Cx+D", "Equate coefficients", "Answer:"],
        ["No elementary primitive found", "ERR:"],
    ),
    (
        "int",
        "defint(ln(sin(x)),x,0,pi/2)",
        ["u=2x", "du=2 dx", "0=>0", "pi/2=>pi", "-pi*ln(2)/2"],
        ["ERR:"],
    ),
    (
        "int",
        "defint(e^(2*x)/(1+e^(2*x)),x,0,ln(7))",
        ["u=e^(2*x)+1", "du/dx=2*e^(2*x)", "Int has form k*u'/u", "F(ln(7))-F(0)"],
        ["ERR:", "No elementary primitive"],
    ),
    (
        "int",
        "defint((4-x^2)^2,x,0,2)",
        ["(-x^2+4)^2=x^4-8*x^2+16", "F(2)-F(0)", "256/15"],
        ["Expected ) but found ,", "No elementary primitive"],
    ),
    (
        "int",
        "volume_x(4-x^2,x,-2,2)",
        ["V=pi*Int(y^2)dx", "(-x^2+4)^2=x^4-8*x^2+16", "512*pi/15"],
        ["Expected ) but found ,", "No elementary primitive"],
    ),
    (
        "int",
        "area_between(6+8*e^(-3*x),e^(3*x)-1,x,0,ln(2))",
        ["A=Int(upper-lower)dx", "F(ln(2))-F(0)", "7*ln(2)"],
        ["Expected ) but found ,", "No elementary primitive"],
    ),
    (
        "int",
        "x^3/(x^4+2),method=reverse_chain",
        ["u=x^4+2", "du/dx=4*x^3", "1/4*ln(abs(x^4+2))+C"],
        ["No elementary primitive"],
    ),
    (
        "int",
        "4*sec(x)^2/tan(x),method=reverse_chain",
        ["u=tan(x)", "du/dx=sec(x)^2", "4*ln(abs(tan(x)))+C"],
        ["No elementary primitive"],
    ),
    (
        "int",
        "6/sqrt(3*x+1)",
        ["6/sqrt(3*x + 1) = 6*(3*x + 1)^(-1/2)", "u = 3*x + 1", "4*sqrt(3*x + 1) + C"],
        ["No elementary primitive"],
    ),
    (
        "alg",
        "simplify(1-1/(x-2)+3/(x^2-x-2))",
        ["(x^2 - 2*x)/(x^2 - x - 2)", "x/(x + 1)"],
        ["ERR:"],
    ),
    (
        "int",
        "3*x*sqrt(x^2+1),method=sub",
        ["u=x^2+1", "du/dx=2*x", "J=1/2*Int(u^(1/2))du", "J=1/3*u^(3/2)+C", "(x^2+1)^(3/2)+C"],
        ["No elementary primitive"],
    ),
    (
        "int",
        "x^3*e^(x^4),method=sub",
        ["u = x^4", "du/dx = 4*x^3", "I = 1/4*Int(e^u) du", "1/4*e^(x^4) + C"],
        ["No elementary primitive", "ERR:"],
    ),
    (
        "int",
        "exp(2*x-3),method=auto",
        ["u = 2*x - 3", "du/dx = 2", "I = 1/2*Int(e^u) du", "I = 1/2*e^u + C", "1/2*e^(2*x - 3) + C"],
        ["reverse chain exponential rule", "ERR:"],
    ),
    (
        "int",
        "sin(2*x-3),method=auto",
        ["u = 2*x - 3", "du/dx = 2", "I = 1/2*Int(sin(u)) du = -cos(u)", "-1/2*cos(2*x - 3) + C"],
        ["reverse chain sine rule", "ERR:"],
    ),
    (
        "int",
        "1/(x*sqrt(x^2-36)),method=trig",
        ["x=6*sec(t)", "Reference triangle", "I=(1/6)Int(1) dt", "acos(6/x)/6"],
        ["No elementary primitive", "ERR:"],
    ),
    (
        "int",
        "exp(sqrt(x)),method=sub",
        ["u=u", "dv=e^u du", "du=du", "v=e^u", "Answer:"],
        ["Parts: w=", "dz=", "ERR:"],
    ),
    (
        "int",
        "x^3*e^(2*x),method=di",
        ["D:", "I:", "Signs:", "e^(2*x)*(1/2*x^3 - 3/4*x^2 + 3/4*x - 3/8)"],
        ["Use DI/table integration by parts for x^n*e^(a*x+b).", "ERR:"],
    ),
    (
        "int",
        "x*e^(x),method=di",
        ["D: x, 1, 0", "I: e^(x), e^(x)", "Signs: +, -", "e^(x)*(x - 1) + C"],
        ["u = x; dv = e^x dx", "ERR:"],
    ),
    (
        "int",
        "x^2*cos(3*x),method=di",
        ["D:", "I:", "Signs:", "1/3*x^2*sin(3*x)"],
        ["Use DI/table integration by parts for x^n times trig.", "ERR:"],
    ),
    (
        "trig",
        "1/cos(x)=5,x,0,2*pi,8,method=identity",
        ["c!=0", "c = 1/5", "cos(x) = 1/5", "Answer:"],
        ["Answer: x = []", "ERR:"],
    ),
    (
        "trig",
        "sin(3*x)=sin(x),x,0,2*pi,10,method=identity",
        ["sin(A) = sin(B): A = B+2*pi*n or A = pi-B+2*pi*n", "x=n*pi", "x=pi/4+n*pi/2", "x = [0, pi/4"],
        ["ERR:"],
    ),
    (
        "trig",
        "2*sin(x)^2=1+cos(x),x,0,2*pi,10,method=identity",
        ["u=cos(x)", "2u^2+u-1=0", "u=1/2 or u=-1", "alpha = arccos", "cos(x)=1/2 or cos(x)=-1"],
        ["substitution differential", "ERR:"],
    ),
    (
        "trig",
        "2*cos(x)^2+3*cos(x)-2=0,x,0,2*pi,10,method=identity",
        ["u=cos(x)", "2u^2+3u-2=0", "u=1/2 or u=-2", "Reject u=-2", "alpha = arccos", "cos(x)=1/2"],
        ["Solve the quadratic in u, then solve cos(A)=u.", "ERR:"],
    ),
    (
        "trig",
        "4*cos(x)^2-4*cos(x)+1=0,x,0,2*pi,10,method=identity",
        ["u=cos(x)", "4u^2-4u+1=0", "u=1/2", "alpha = arccos", "x = [pi/3, 5*pi/3]"],
        ["u=1/2 or u=1/2", "ERR:"],
    ),
    (
        "alg",
        "domain(sqrt(log(1/2,x-1)))",
        ["x - 1 > 0", "base = 1/2", "0 < x - 1 <= 1", "Answer: 1 < x <= 2"],
        ["Answer: log(x - 1)/log(1/2) >= 0", "ERR:"],
    ),
    (
        "alg",
        "range(abs(x-1)+abs(x-2))",
        ["roots: x = 1; x = 2", "min y = 1", "Answer: y >= 1"],
        ["Answer: y >= 0", "ERR:"],
    ),
    (
        "alg",
        "range(abs(2*x-3)+abs(5*x+1))",
        ["roots: x = 3/2; x = -1/5", "min y = 17/5", "Answer: y >= 17/5"],
        ["inspect graph/transform", "Answer: y >= 0", "ERR:"],
    ),
    (
        "alg",
        "(domain(sqrt(log(2,x-9))))",
        ["base > 1", "Domain: x >= 10", "Answer: x >= 10"],
        ["domain*sqrt", "ERR:"],
    ),
    (
        "alg",
        "(range(abs(x-2)+abs(x-3)))",
        ["roots: x = 2; x = 3", "min y = 1", "Range: y >= 1"],
        ["range*", "ERR:"],
    ),
    (
        "alg",
        "binomial((1+2*x)^(-1/2),x,0,4)",
        ["n = -1/2: C(n,0) = 1", "C(n,4) = 35/128", "Terms: 1 - 1/2*(2*x)", "Valid for abs(x) < 1/2", "Answer: 1 - x + 3/2*x^2 - 5/2*x^3 + 35/8*x^4"],
        ["ERR:"],
    ),
    (
        "alg",
        "binomial((5*x+3)/((1-x)*(1+3*x)),x,0,3)",
        ["PF: 2/(- x + 1) + 1/(3*x + 1)", "Valid for abs(x) < 1/3", "Answer: 3 - x + 11*x^2 - 25*x^3"],
        ["unsupported binomial", "ERR:"],
    ),
    (
        "alg",
        "binomial(2*x/(1+2*x)^3,x,0,4)",
        ["(2*x + 1)^-3", "Valid for abs(x) < 1/2", "Answer: 2*x - 12*x^2 + 48*x^3 - 160*x^4"],
        ["unsupported binomial", "ERR:"],
    ),
    (
        "alg",
        "binomial(2*(1+4*x)^(1/2)+4/(1+x),x,0,3)",
        ["(4*x + 1)^1/2", "(x + 1)^-1", "Valid for abs(x) < 1/4", "Answer: 6 + 4*x^3"],
        ["unsupported binomial", "ERR:"],
    ),
    (
        "alg",
        "fitconst((a*x+b)*(x-2)+c*(x+1)^2=4*x^2+6*x-1,[a,b,c])",
        ["x = 0:", "x = 1:", "x = 2:", "a = 1", "b = 2", "c = 3"],
        ["Unexpected end of input", "Answer: solve(fitconst", "Route for fit constants", "ERR:"],
    ),
    (
        "alg",
        "fitconst(a*(x+1)^2+b*(x-1)^2+c*(x^2-1)=6*x^2+4*x+2,[a,b,c])",
        ["x = 0:", "x = 1:", "x = 2:", "a = 3", "b = 1", "c = 2"],
        ["Unexpected end of input", "Answer: solve(fitconst", "Route for fit constants", "ERR:"],
    ),
    (
        "alg",
        "fitconst((x+a)^2+(y+b)^2=x^2+y^2-6*x+10*y+34,[a,b])",
        ["(x = 0, y = 0):", "(x = 1, y = 0):", "a = -3", "b = 5"],
        ["constants not isolated", "Unexpected end of input", "Answer: solve(fitconst", "ERR:"],
    ),
    (
        "alg",
        "fitconst((a*x+b)/(x+1)=2+3/(x+1),[a,b])",
        ["identity", "a=2", "b=5"],
        ["constants not isolated", "Unexpected end of input", "Answer: solve(fitconst", "ERR:"],
    ),
    (
        "alg",
        "compare((x^2-1)/(x-1),x+1)",
        ["E1 =", "E2 =", "E1-E2 = 0", "equivalent"],
        ["Unexpected end of input", "Answer: solve(compare", "ERR:"],
    ),
    (
        "alg",
        "evalat(4*acos(x)-x-1,x,1)",
        ["x=1", "f(1)=-2"],
        ["ERR:", "undefined"],
    ),
    (
        "derive",
        "1/(2*x+1)+1/(y+1)=x^2,x,method=implicit",
        ["Domain: denoms !=0", "y + 2*x - x^2*(2*x + 1)*(y + 1) + 2 = 0", "d/dx(LHS) = d/dx(RHS)", "collect dy/dx", "dy/dx = (2*x*(2*x + 1)*(y + 1) + 2*x^2*(y + 1) - 2)/(- x^2*(2*x + 1) + 1)"],
        ["Domain: log args >0", "F_x", "F_y", "ERR:"],
    ),
    (
        "derive",
        "(4*x+1)/(1-2*x),x,method=quotient",
        ["u=4*x+1", "v=-2*x+1", "[(4)*(-2*x+1)-(4*x+1)*(-2)]=6", "dy/dx=6/(-2*x+1)^2"],
        ["dy/dx=[(4)*(-2*x+1)-(4*x+1)*(-2)]/(-2*x+1)^2", "ERR:"],
    ),
    (
        "derive",
        "sin(x)/(2-cos(x)),x,method=quotient",
        ["[(cos(x))*(-cos(x)+2)-(sin(x))*(sin(x))]=2*cos(x)-1", "dy/dx=(2*cos(x)-1)/(-cos(x)+2)^2"],
        ["ERR:"],
    ),
    (
        "derive",
        "e^(3*x)*(sin(x)+cos(x)),x,method=product",
        ["dy/dx=(e^(3*x))*((3)*(sin(x)+cos(x))+(cos(x)-sin(x)))", "dy/dx=2*e^(3*x)*(sin(x)+2*cos(x))"],
        ["ERR:"],
    ),
    (
        "derive",
        "e^(2*x)*(x^2-4*x-2),x,method=product",
        ["dy/dx=(e^(2*x))*((2)*(x^2-4*x-2)+(2*x-4))", "dy/dx=2*e^(2*x)*(x^2-3*x-4)"],
        ["ERR:"],
    ),
    (
        "int",
        "x*ln(5*x)",
        ["u=ln(5*x)", "dv=x dx", "du=1/x dx", "v=x^2/2", "I=uv-Int(vdu)", "1/2*x^2*ln(5*x) - 1/4*x^2 + C"],
        ["Integral not recognised", "Answer: int(", "ERR:"],
    ),
    (
        "int",
        "tan(3*x)",
        ["u = 3*x, du = 3 dx", "tan(u) = sin(u)/cos(u)", "v = cos(u), dv = -sin(u) du", "Answer: -ln(abs(cos(3*x)))/3 + C"],
        ["Integral not recognised", "Answer: int(", "ERR:"],
    ),
    (
        "int",
        "atan(2*x+3)^2,method=parts",
        ["u = 2*x + 3, du = 2 dx", "I = 1/2*Int(atan(u)^2) du", "Int(t^2*sec(t)^2)dt = t^2*tan(t)-Int(2t*tan(t))dt", "Int(2t*tan(t))dt = -2t*ln(abs(cos(t)))+2*Int(ln(abs(cos(t))))dt", "Answer: No elementary primitive found"],
        ["Answer: atan(2*x + 3)^2", "ERR:"],
    ),
    (
        "alg",
        "range(log(10,abs(3*x+1)+3))",
        ["Answer: y >= ln(3)/ln(10)"],
        ["inspect graph/transform", "ERR:"],
    ),
    (
        "alg",
        "sin(x)^2-sin(x)=0,method=factor",
        ["Let u = sin(x)", "u*(u - 1) = 0", "sin(x) = 0 or sin(x) = 1"],
        ["Unexpected token", "Answer: solve(", "ERR:"],
    ),
    (
        "alg",
        "x^2+a*x+b,method=factor",
        ["Err: numeric coeffs needed"],
        ["Unexpected token"],
    ),
    (
        "alg",
        "rewrite(sqrt(12+sqrt(140)))",
        ["Let sqrt(12+sqrt(140)) = sqrt(m)+sqrt(n)", "m+n=12", "4*m*n=140", "Answer: sqrt(7)+sqrt(5)"],
        ["rewrite*sqrt", "ERR:"],
    ),
    (
        "alg",
        "sqrt(180)",
        ["sqrt(36*5)", "6*sqrt(5)"],
        ["ERR:", "Answer: sqrt(180)"],
    ),
    (
        "alg",
        "sqrt((9-3)^2+(8-20)^2)",
        ["sqrt(36*5)", "6*sqrt(5)"],
        ["ERR:", "Answer: sqrt(180)"],
    ),
    (
        "alg",
        "(81/16)^(3/4)",
        ["27/8"],
        ["ERR:", "Answer: (81/16)^(3/4)"],
    ),
    (
        "alg",
        "(36^(1/2)+16^(1/4))^(-2/3)",
        ["(6 + 2)^(-2/3)", "8^(-2/3)", "1/4"],
        ["ERR:", "Answer: 1/4"],
    ),
    (
        "alg",
        "2^-5-8^-2",
        ["1/32 - 1/64", "1/64"],
        ["ERR:", "Answer: 1/64"],
    ),
    (
        "alg",
        "solve(y^(-1/3)=8,y)",
        ["u = y^(1/3)", "u = 1/8", "y = [1/512]"],
        ["ERR:", "0.00195312500001"],
    ),
    (
        "alg",
        "9*x^6*y^4/(3*x^2*y)^3",
        ["(9*x^6*y^4)/(27*x^6*y^3)", "(9/27)*x^(6-6)*y^(4-3)", "y/3"],
        ["ERR:", "Answer: y/3"],
    ),
    (
        "alg",
        "(4*x*y^2)^2/(2*x)^3",
        ["2*x^-1*y^4", "2*y^4/x"],
        ["ERR:", "Answer: 2*y^4/x"],
    ),
    (
        "alg",
        "sqrt(150)-sqrt(54)",
        ["sqrt(25*6)", "5*sqrt(6) - 3*sqrt(6)", "2*sqrt(6)"],
        ["ERR:", "Answer: sqrt(150) - sqrt(54)"],
    ),
    (
        "alg",
        "sqrt(24.5)-sqrt(12.5)",
        ["1/2*sqrt(98) - 1/2*sqrt(50)", "7/2*sqrt(2) - 5/2*sqrt(2)", "sqrt(2)"],
        ["ERR:", "Answer: sqrt(49/2) - sqrt(25/2)"],
    ),
    (
        "alg",
        "(4-sqrt(5))^2",
        ["16 - 8*sqrt(5) + 5", "21 - 8*sqrt(5)"],
        ["ERR:", "Answer: (- sqrt(5) + 4)^2"],
    ),
    (
        "alg",
        "2*sqrt(5)*sqrt(15)-sqrt(75)-sqrt(60)/sqrt(5)",
        ["2*sqrt(75) - sqrt(75) - sqrt(12)", "10*sqrt(3) - 5*sqrt(3) - 2*sqrt(3)", "3*sqrt(3)"],
        ["ERR:", "Answer: 2*sqrt(5)*sqrt(15) - sqrt(75) - sqrt(60)/sqrt(5)"],
    ),
    (
        "alg",
        "2*sqrt(75)+(3+sqrt(3))/(3-sqrt(3))-sqrt(2)*sqrt(2)",
        ["10*sqrt(3) + (sqrt(3) + 3)*(3 + sqrt(3))", "(12 + 6*sqrt(3))/6", "10*sqrt(3) + 2 + sqrt(3) - 2", "11*sqrt(3)"],
        ["ERR:", "Answer: 11*sqrt(3)"],
    ),
    (
        "alg",
        "sqrt(2)/(1+sqrt(2))",
        ["(sqrt(2))*(-1 + sqrt(2))", "(2 - sqrt(2))/1", "2 - sqrt(2)"],
        ["ERR:", "Answer: 2 - sqrt(2)"],
    ),
    (
        "alg",
        "21/sqrt(7)",
        ["21*sqrt(7)/7", "3*sqrt(7)"],
        ["ERR:", "Answer: 21/sqrt(7)"],
    ),
    (
        "alg",
        "y+1=(-2/3)*(x-4),method=standard_line",
        ["y + 1 = -2/3*(x - 4)", "2*x + 3*y - 5 = 0", "2*x + 3*y = 5"],
        ["ERR:"],
    ),
    (
        "alg",
        "y-e=-3*e*(x-e^2),method=standard_line",
        ["y - e = -3*e*(x - e^(2))", "y = - 3*e*x + e + 3*e^(3)", "y + 3*e*x = e + 3*e^(3)"],
        ["ERR:"],
    ),
    (
        "alg",
        "y-a=m*(x-b),method=standard_line",
        ["y - a = m*(x - b)", "y = m*x + a - m*b", "y - m*x = a - m*b"],
        ["ERR:"],
    ),
    (
        "alg",
        "evalat(-asin(x-1),x,0)",
        ["f(0) = pi/2"],
        ["1.570796", "ERR:"],
    ),
    (
        "alg",
        "evalat(atan(x),x,1)",
        ["f(1) = pi/4"],
        ["0.785398", "ERR:"],
    ),
    (
        "alg",
        "cot(x^2-pi/4),method=auto",
        ["Use identity cot(u) = cos(u)/sin(u)", "Domain: sin(x^2 - pi/4) != 0", "Answer: cos(x^2 - pi/4)/sin(x^2 - pi/4)"],
        ["Err:", "Unexpected token"],
    ),
    (
        "trig",
        "tan(2*x)=sqrt(3),x,0,2*pi,8,method=cast",
        ["u=tan(2*x)", "u=sqrt(3)", "tan(2*x)=sqrt(3)", "2*x=alpha+pi*n", "x=[pi/6,2*pi/3,7*pi/6,5*pi/3]"],
        ["ERR:", "Unexpected token"],
    ),
    (
        "trig",
        "8*tan(phi)=cot(phi)^2,phi,0,2*pi,8",
        ["u = tan(phi)", "cot(phi) = 1/u", "8u^3 - 1 = 0", "u = 1/2", "Answer: phi = [0.463647609001, 3.60524026259]"],
        ["Failed to isolate", "phi = []"],
    ),
    (
        "trig",
        "7*cot(alpha)^2+6*cot(alpha)=1,alpha,0,pi/2",
        ["u=tan(alpha)", "u=-1 or u=7", "tan(alpha)=7", "Answer: alpha = [1.42889927219]"],
        ["ERR:"],
    ),
    (
        "trig",
        "27*sin(phi)^2+8*cosec(phi)=0,phi,0,2*pi,8",
        ["u = sin(phi)", "cosec(phi) = 1/u", "27u^3 + 8 = 0", "u = -2/3", "Answer: phi = [3.87132030982, 5.55345765095]"],
        ["Failed to isolate", "phi = []"],
    ),
    (
        "trig",
        "27*cos(phi)=sec(phi)^2,phi,0,2*pi,8",
        ["u = cos(phi)", "sec(phi) = 1/u", "27u^3 - 1 = 0", "u = 1/3", "Answer: phi = [1.23095941734, 5.05222588984]"],
        ["Failed to isolate", "phi = []"],
    ),
    (
        "trig",
        "sec(theta)+cos(theta)=5/2,theta,0,360",
        ["u = cos(theta)", "sec(theta) = 1/u", "u^2 - 2.5u + 1 = 0", "Answer: theta = [60, 300]"],
        ["Failed to isolate", "theta = []"],
    ),
    (
        "trig",
        "2*sec(theta)-1=2*sec(theta)*sin(theta)^2,theta,0,180",
        ["u = cos(theta)", "sec(theta) = 1/u", "sin(theta)^2 = 1-u^2", "2u^2-u = 0", "Reject u=0", "Answer: theta = [60]"],
        ["Failed to isolate", "theta = []"],
    ),
    (
        "trig",
        "cos(x)*cot(x)+sin(x)+2*cot(x)=0,x,0,360",
        ["Multiply by sin(x)", "sin(x)^2+cos(x)^2 = 1", "1 + 2*cos(x) = 0", "Answer: x = [120, 240]"],
        ["Failed to isolate", "x = []"],
    ),
    (
        "trig",
        "(cosec(y)-sin(y))*sec(y)^2=2,y,0,pi,8",
        ["Multiply by sin(y)*cos(y)^2", "1-sin(y)^2 = cos(y)^2", "cos(y)^2*(1 - 2*sin(y)) = 0", "Answer: y = [pi/6, 5*pi/6]"],
        ["Failed to isolate", "y = []"],
    ),
    (
        "trig",
        "cosec(phi)-sin(phi)+2*cos(phi)^2*cot(phi)=0,phi,0,2*pi,8",
        ["Multiply by sin(phi)", "1-sin(phi)^2 = cos(phi)^2", "cos(phi)^2*(1 + 2*cos(phi)) = 0", "Answer: phi = [pi/2, 2*pi/3, 4*pi/3, 3*pi/2]"],
        ["Failed to isolate", "phi = []"],
    ),
    (
        "trig",
        "sec(x)-cos(x)=8*(cosec(x)-sin(x)),x,0,360",
        ["Multiply by sin(x)*cos(x)", "sin(x)^3 = 8*cos(x)^3", "tan(x) = 2", "Answer: x = [63.4349488229, 243.434948823]"],
        ["Failed to isolate", "x = []"],
    ),
    (
        "trig",
        "2*cot(y)-3*cosec(y)=2*sec(y)*cosec(y),y,0,2*pi,8",
        ["Multiply by sin(y)*cos(y)", "u = cos(y)", "2u^2-3u-2 = 0", "Answer: y = [2*pi/3, 4*pi/3]"],
        ["Failed to isolate", "y = []"],
    ),
    (
        "trig",
        "(1+sec(phi))*(1-cos(phi))=tan(phi),phi,0,2*pi,8",
        ["sec(phi) = 1/cos(phi)", "tan(phi) = sin(phi)/cos(phi)", "sin(phi)*(sin(phi)-1) = 0", "sin(phi) = 1 rejected", "Answer: phi = [0, pi, 2*pi]"],
        ["Failed to isolate", "phi = []"],
    ),
    (
        "alg",
        "cot(x)^2+1,method=auto",
        ["Use identity 1 + cot(u)^2 = cosec(u)^2", "Domain: sin(x) != 0", "Answer: cosec(x)^2"],
        ["ERR:", "Unexpected token"],
    ),
    (
        "trig",
        "sqrt((3*x+1)^2),method=auto",
        ["Let u = 3*x + 1", "sqrt(u^2)=abs(u)", "Answer: abs(3*x + 1)"],
        ["ERR:", "Unexpected token", "Answer: sqrt((3*x + 1)^2)"],
    ),
    (
        "derive",
        "mode:5,exp(t)*cos(t),exp(t)*sin(t),t",
        ["d/dt(dy/dx) = 2/(cos(t)-sin(t))^2", "d2y/dx2 = 2/[e^t(cos(t)-sin(t))^3]"],
        ["ERR:", "Unexpected token"],
    ),
    (
        "derive",
        "sec(theta),ln(1+cos(2*theta)),theta,method=param",
        ["dx/dt=sec(theta)*tan(theta)", "tan(u)=sin(u)/cos(u),sec(u)=1/cos(u)", "dy/dx=-2*cos(theta)"],
        ["ERR:", "Done"],
    ),
    (
        "derive",
        "cos(2*theta),2*sin(theta)^3,theta,method=param",
        ["sin(2u)=2sin(u)cos(u)", "dy/dx=-3*sin(theta)/2"],
        ["ERR:", "Done"],
    ),
    (
        "derive",
        "1/t+1/t^2,1/t-1/t^2,t,method=param",
        ["dy/dx=((-t^-2+2*t^-3)*t^3)/((-t^-2-2*t^-3)*t^3)", "dy/dx=(t-2)/(t+2)"],
        ["ERR:", "Done"],
    ),
    (
        "int",
        "sqrt((2*x-3)^2)",
        ["sqrt(u^2)=abs(u)", "Split at u=0, so x=3/2", "For x >= 3/2", "For x < 3/2", "Answer: (2*x - 3)*abs(2*x - 3)/4 + C"],
        ["ERR:", "Unexpected token", "Answer: int("],
    ),
    (
        "alg",
        "arcsin(sin(2*x+pi/6)),method=complete_square",
        ["Complete square is for quadratics", "inverse-trig expression", "not applicable"],
        ["ERR:", "Unexpected token"],
    ),
    (
        "alg",
        "asin(sin(2*x+pi/6)),method=auto",
        ["-pi/2 <= u <= pi/2 => asin(sin(u)) = u", "asin(sin(2*x + pi/6))"],
        ["ERR:", "Unexpected token"],
    ),
    (
        "alg",
        "atan(2*x-3),method=pf",
        ["Err: PF needs rational P(x)/Q(x)"],
        ["ERR:", "Unexpected token"],
    ),
    (
        "trig",
        "sin(x+y),method=compound_angle",
        ["sin(A+B)=sin(A)cos(B)+cos(A)sin(B)", "Answer: sin(x)*cos(y)+cos(x)*sin(y)"],
        ["ERR:", "Unexpected token"],
    ),
    (
        "trig",
        "sin(A+B),method=compound_angle",
        ["sin(A+B)=sin(A)cos(B)+cos(A)sin(B)", "sin(A)*cos(B)+cos(A)*sin(B)"],
        ["ERR:", "Unexpected token"],
    ),
    (
        "trig",
        "cos(A+B),method=compound_angle",
        ["cos(A+B)=cos(A)cos(B)-sin(A)sin(B)", "cos(A)*cos(B)-sin(A)*sin(B)"],
        ["ERR:", "Unexpected token"],
    ),
    (
        "trig",
        "sec(2*x)\n1/(1-2*sin(x)^2)",
        ["sec(2x)=1/cos(2x)", "cos(2x)=1-2sin(x)^2", "Answer: sec(2x) = 1/(1-2sin(x)^2)"],
        ["LHS=RHS", "ERR:"],
    ),
    (
        "trig",
        "cosec(atan(1/2)),method=auto",
        ["tan(atan(1/2))=1/2", "opp=1,adj=2,hyp=sqrt(5)", "cosec(atan(1/2))=hyp/opp=sqrt(5)"],
        ["ERR:"],
    ),
    (
        "trig",
        "cos(7*theta),method=auto",
        ["Basis: let c=cos(theta)", "Answer: 64*c^7 - 112*c^5 + 56*c^3 - 7*c"],
        ["ERR:", "Unexpected token"],
    ),
    (
        "trig",
        "tan(3*x),method=auto",
        ["Let u=tan(x)", "Answer: (3*tan(x)-tan(x)^3)/(1-3*tan(x)^2)"],
        ["ERR:", "Unexpected token"],
    ),
    (
        "trig",
        "(sin(5*x)-sin(x))/(cos(5*x)+cos(x)),method=auto",
        ["sum-to-product", "Answer: tan(2*x)"],
        ["ERR:", "Unexpected token"],
    ),
    (
        "trig",
        "cos(7*theta),target=cos(theta),method=auto",
        ["Source != target", "cos(7*theta)"],
        ["Source = target", "Answer: cos(theta)", "ERR:"],
    ),
    (
        "trig",
        "sin(x+y),target=sin(2*x),method=auto",
        ["Source != target", "sin(x + y)"],
        ["Source = target", "Answer: sin(2*x)", "ERR:"],
    ),
    (
        "trig",
        "tan(2*x+pi/6),method=auto",
        ["tan(A+B)", "N=tan(2*x)+1/sqrt(3)", "D=1-tan(2*x)*1/sqrt(3)", "(tan(2*x)+1/sqrt(3))/(1-tan(2*x)*1/sqrt(3))"],
        ["N/D", "ERR:", "Unexpected token"],
    ),
    (
        "alg",
        "arctan(2*x-3)=0,method=auto",
        ["atan(2*x-3)=0", "2*x-3=tan(0)", "2*x-3=0", "x=3/2"],
        ["Answer: 2*x - 3 = 0", "ERR:", "Unexpected token"],
    ),
    (
        "alg",
        "cosec((x)^2-pi/4)^2-cot((x)^2-pi/4)^2,method=auto",
        ["Use identity cosec(u)^2 - cot(u)^2 = 1", "Answer: 1"],
        ["ERR:", "Unexpected token"],
    ),
    (
        "alg",
        "range(arccos((x-1)/3))",
        ["Domain: -1 <= (x - 1)/3 <= 1", "acos(A): -1<=A<=1 => 0<=y<=pi", "Range: 0 <= y <= pi", "Answer: 0 <= y <= pi"],
        ["inspect graph/transform", "ERR:", "Unexpected token"],
    ),
    (
        "alg",
        "range(atan(tan(2*x+pi/6)))",
        ["Domain: cos(2*x + pi/6) != 0", "atan(A): A in R => -pi/2<y<pi/2", "Range: -pi/2 < y < pi/2"],
        ["inspect graph/transform", "ERR:", "Unexpected token"],
    ),
    (
        "alg",
        "domain(atan(tan(x)))",
        ["atan(A) is defined for all real A", "tan(u) needs cos(u) != 0", "Domain: cos(x) != 0", "Domain: x != pi/2 + n*pi"],
        ["1*(pi/2 + n*pi)", "ERR:", "Unexpected token"],
    ),
    (
        "alg",
        "cosec((x+1)/3),method=auto",
        ["Use identity cosec(u) = 1/sin(u)", "Domain: (x + 1)/3 != n*pi", "Domain: x != 3*n*pi - 1", "Answer: 1/sin((x + 1)/3)"],
        ["ERR:", "Unexpected token"],
    ),
    (
        "alg",
        "sec((x+1)/3),method=auto",
        ["Use identity sec(u) = 1/cos(u)", "Domain: (x + 1)/3 != pi/2 + n*pi", "Answer: 1/cos((x + 1)/3)"],
        ["ERR:", "Unexpected token"],
    ),
    (
        "derive",
        "mode:5,t^2+1/t,t^2-1/t,t",
        ["dy/dx = (2*t^3 + 1)/(2*t^3 - 1)", "d/dt(dy/dx) = -12*t^2/(2*t^3-1)^2", "Answer: d2y/dx2 = -12*t^4/(2*t^3 - 1)^3"],
        ["ERR:", "Unexpected token"],
    ),
    (
        "stats",
        "covariance([1,1,2,3,5,8],[2,5,7,11])",
        ["Err: list lengths differ"],
        ["Traceback"],
    ),
    (
        "stats",
        "median([1,2,3,4,8])",
        ["x_(sorted) = [1, 2, 3, 4, 8]", "n = 5", "median = x_3 = 3", "3"],
        ["mean =", "var(", "sd =", "Traceback"],
    ),
    (
        "stats",
        "mean([1,2,3,4,8])",
        ["sum x = 18", "mean = sum x/n = 18/5 = 3.6", "3.6"],
        ["median =", "var(", "sd =", "Traceback"],
    ),
    (
        "stats",
        "quartiles([1,2,3,4,8])",
        ["Q1 = (x_1 + x_2)/2 = 1.5", "median = x_3 = 3", "Q3 = (x_4 + x_5)/2 = 6", "[1.5, 3, 6]"],
        ["mean =", "var(", "sd =", "Traceback"],
    ),
    (
        "stats",
        "stddev([1,2,3,4,8])",
        ["mean = 18/5 = 3.6", "Sxx = sum((x-mean)^2) = 29.2", "sd = sqrt(5.84) = 2.41660919", "2.41660919"],
        ["median =", "Traceback"],
    ),
    (
        "stats",
        "1,2,3,4,method=summary",
        ["sum x^2 = 30", "Sxx = sum x^2 - (sum x)^2/n = 30 - (10)^2/4 = 5", "sd = sqrt(var) = sqrt(1.25)", "s = sqrt(s^2) = sqrt(1.66666667)"],
        ["var(pop)", "sum((x-mean)^2)", "Traceback"],
    ),
    (
        "stats",
        "-36,14,47,-47,1000001,-1000000,-44,-29,34,method=summary",
        ["sum x^2 = 2.000002e12", "Sxx = sum x^2 - (sum x)^2/n", "sd = sqrt(var)", "s = sqrt(s^2)"],
        ["var(pop)", "Traceback"],
    ),
    (
        "stats",
        "binomial(10000,0.01,102,tail)",
        ["X ~ B(10000, 0.01)", "P(X >= 102) = 1 - P(X <= 101)", "sum_{x=0}^101", "mu = np = 100", "1 - Phi", "P(X >= 102) = 0.44008423"],
        ["Traceback", "normal approx with continuity correction"],
    ),
    (
        "stats",
        "binomcdf(10,1/6,2)",
        ["X ~ B(10, 0.16666667)", "P(X <= 2)", "0.7752268"],
        ["X ~ B(10, 1)", "Traceback"],
    ),
    (
        "alg",
        "solve([(16.3-mu)/sigma=-0.52440051,(29-mu)/sigma=1.28155156],[mu,sigma])",
        ["mu ~=", "sigma ~=", "19.987", "7.032"],
        ["Traceback"],
    ),
    (
        "alg",
        "solve(m*g*(5/13)-mu*m*g*(12/13)=m*a,a)",
        ["5/13*m*g - 12/13*mu*m*g = m*a", "m != 0", "a = 5/13*g - 12/13*mu*g"],
        ["a = (5/13*m*g - 12/13*mu*m*g)/m", "Traceback"],
    ),
    (
        "alg",
        "solve(3+sqrt(a^2)=15/(a-3),a)",
        ["sqrt(a^2)=|a|", "a >= 0", "a = [2*sqrt(6)]"],
        ["a = 4.898979", "Traceback"],
    ),
    (
        "alg",
        "log(2,sqrt(x))",
        ["a = log(2,x)", "log(2,sqrt(x)) = 1/2*a", "1/2*a"],
        ["ln(sqrt(x))/ln(2)", "Traceback"],
    ),
    (
        "alg",
        "log(2,x*(x+8))",
        ["a = log(2,x)", "b = log(2,x + 8)", "a+b"],
        ["ln(x*(x + 8))/ln(2)", "Traceback"],
    ),
    (
        "alg",
        "log(2,8*(x+8)/x)",
        ["a = log(2,x)", "b = log(2,x + 8)", "3+b-a"],
        ["ln(8*(x + 8)/x)/ln(2)", "Traceback"],
    ),
    (
        "alg",
        "expand((n+1)^3-n^3)",
        ["= 3n^2+3n+1", "= 3n(n+1)+1", "n(n+1) is even", "is odd"],
        ["(n + 1)^3 - n^3\n", "Traceback"],
    ),
    (
        "derive",
        "7*x*e^x/(sqrt(e^(3*x)-2)),x",
        ["Numerator = 7e^x", "A = -4, B = -4", "e^(3x)*(2-x)-4x-4"],
        ["dy/dx = ((7*e^(x)", "Traceback"],
    ),
    (
        "derive",
        "4*x*sqrt(x)-25/16*x^2,x",
        ["4*x*sqrt(x) - 25/16*x^2 = 4*x^(3/2) - 25/16*x^2", "d/dx(4*x^(3/2)) = 6*sqrt(x)", "dy/dx = 6*sqrt(x) - 25/8*x"],
        ["4*sqrt(x) + 4*x*1/(2*sqrt(x))", "Traceback"],
    ),
    (
        "alg",
        "solve(z*sqrt(8)-6=2*z/sqrt(2),z)",
        ["z = 6/(sqrt(8) + -2/sqrt(2))", "= 3*sqrt(2)", "z = 3*sqrt(2)"],
        ["z = [6/(sqrt(8)", "Traceback"],
    ),
    (
        "int",
        "sin((x)^2-pi/4)^2+cos((x)^2-pi/4)^2",
        ["Use identity sin(u)^2 + cos(u)^2 = 1", "Answer: x + C"],
        ["ERR:", "Unexpected token"],
    ),
    (
        "alg",
        "x^2-6*x+5=0,method=complete_square",
        ["(x - 3)^2 - 4 = 0", "x - 3 = +/-2", "Answer: x = [5, 1]"],
        ["ERR:", "Unexpected token"],
    ),
    (
        "alg",
        "2*x^2+3*x-2=0,method=complete_square",
        ["divide by a: x^2 + 3/2*x - 1 = 0", "h = b/(2a) = 3/4", "add h^2 = 9/16", "(x + 3/4)^2 = 25/16", "Answer: x = [1/2, -2]"],
        ["quadratic formula", "ERR:", "Unexpected token"],
    ),
    (
        "derive",
        "mode:3,exp(t)*cos(t),exp(t)*sin(t),t",
        ["dy/dx = e^t(sin(t)+cos(t))/[e^t(cos(t)-sin(t))]", "Cancel e^t"],
        ["ERR:", "Unexpected token"],
    ),
    (
        "alg",
        "domain(sin(2*x+pi/6)^2+cos(2*x+pi/6)^2)",
        ["Use sin(u)^2 + cos(u)^2 = 1", "Domain: all real x", "Answer: all real x"],
        ["Start with 1", "ERR:", "Unexpected token"],
    ),
    (
        "alg",
        "domain(cosec((x)^2-pi/4)^2-cot((x)^2-pi/4)^2)",
        ["cosec(u)^2 = 1+cot(u)^2", "cosec(u)^2 - cot(u)^2 = 1", "Domain: sin(x^2 - pi/4) != 0", "sin(x^2 - pi/4) != 0"],
        ["Start with 1", "ERR:", "Unexpected token"],
    ),
    (
        "alg",
        "range(cosec((x+1)/3)^2-cot((x+1)/3)^2)",
        ["u = (x+1)/3", "cosec(u)^2 - cot(u)^2 = 1", "Range: y = 1", "Answer: y = 1"],
        ["1 + cot(u)^2 = cosec(u)^2\nDomain", "ERR:", "Unexpected token"],
    ),
    (
        "alg",
        "range(sec(x)^2-tan(x)^2)",
        ["sec(u)^2 = 1+tan(u)^2", "sec(u)^2 - tan(u)^2 = 1", "Range: y = 1", "Answer: y = 1"],
        ["inspect graph/transform", "ERR:", "Unexpected token"],
    ),
    (
        "alg",
        "range(csc(x))",
        ["Domain: sin(x) != 0", "cosec(u)=1/sin(u), 0<|sin(u)|<=1", "Range: y <= -1 or y >= 1"],
        ["inspect graph/transform", "ERR:", "Unexpected token"],
    ),
    (
        "alg",
        "domain(cot((x)^2-pi/4)^2+1)",
        ["1 + cot(u)^2 = cosec(u)^2", "= cosec(x^2 - pi/4)^2", "Domain: sin(x^2 - pi/4) != 0"],
        ["Start with cosec", "ERR:", "Unexpected token"],
    ),
    (
        "alg",
        "cot((x+1)/3)^2+1=0,method=auto",
        ["1 + cot(u)^2 = cosec(u)^2", "cosec(u) = 1/sin(u); cosec(u)^2 != 0", "x = []"],
        ["LHS-RHS = 0:", "Answer:", "ERR:"],
    ),
    (
        "alg",
        "arcsin(sin((x)^2-pi/4))=0,method=auto",
        ["arcsin(A)=0 => A=0", "sin(u)=0 => u=n*pi", "x = +/-sqrt(pi/4 + n*pi)"],
        ["x = []", "No real solution", "ERR:"],
    ),
    (
        "alg",
        "cosec(2*x+pi/6)^2-cot(2*x+pi/6)^2=0,method=auto",
        ["Domain: sin(2*x + pi/6) != 0", "Use identity cosec(u)^2 - cot(u)^2 = 1", "Answer: x = []"],
        ["log args", "denoms !=0", "ERR:"],
    ),
    (
        "alg",
        "cos(x)=0,method=auto",
        ["cos(x)=0 => x=pi/2 + n*pi", "Answer: x = pi/2 + n*pi, integer n"],
        ["Answer (3 d.p.)", "-98.", "ERR:"],
    ),
    (
        "int",
        "(cosec(x)^2-cot(x)^2)*exp(x),method=auto",
        ["cosec(x)^2 - cot(x)^2 = 1", "integrand = e^(x)", "I = Int(e^(x)) dx", "Answer: e^(x) + C"],
        ["Answer: int", "ERR:"],
    ),
    (
        "int",
        "cot(x),method=auto",
        ["cot(u) = cos(u)/sin(u)", "v = sin(u), dv = cos(u) du", "Int(cot(u))du = Int(1/v)dv", "Answer: ln(abs(sin(x))) + C"],
        ["Integral(cot u)du", "Answer: int", "ERR:"],
    ),
    (
        "int",
        "sec(x),method=auto",
        ["v = sec(u)+tan(u)", "dv = sec(u)(sec(u)+tan(u)) du", "Int(sec(u))du = Int(1/v)dv", "Answer: ln(abs(sec(x) + tan(x))) + C"],
        ["Integral(sec u)du", "Answer: int", "ERR:"],
    ),
    (
        "int",
        "tan(x)^2+1,method=auto",
        ["tan(u)^2 + 1 = sec(u)^2", "integrand = sec(x)^2", "I = Int(sec(x)^2) dx", "Answer: tan(x) + C"],
        ["Answer: int", "ERR:"],
    ),
    (
        "int",
        "tan(3*x+1)^2,method=auto",
        ["u = 3*x + 1", "du/dx = 3", "I = 1/3*Int(sec(u)^2-1)du", "I = (tan(u)-u)/3+C", "Answer: tan(3*x + 1)/3 - x + C"],
        ["Integral tan(u)^2 dx", "Answer: int", "ERR:"],
    ),
    (
        "int",
        "sin(3*x)*cos(5*x),method=trig",
        ["A = 3*x, B = 5*x", "2sin(A)cos(B) = sin(A+B)+sin(A-B)", "I = 1/2*Int(sin(8*x)-sin(2*x))dx", "Answer: -1/16*cos(8*x) + 1/4*cos(2*x) + C"],
        ["No elementary primitive", "ERR:"],
    ),
    (
        "int",
        "cot((x)^2-pi/4)^2+1,method=auto",
        ["1 + cot(u)^2 = cosec(u)^2", "du/dx = 2*x", "du/dx not constant", "No elementary primitive"],
        ["Use the general integration route", "Answer: int", "ERR:"],
    ),
    (
        "alg",
        "range(x/(1+x^2))",
        ["y*(x^2 + 1) = x", "y*x^2 - x + y = 0", "1 - 4*y^2 >= 0", "Range: -1/2 <= y <= 1/2", "Answer: -1/2 <= y <= 1/2"],
        ["inspect graph/transform", "ERR:"],
    ),
    (
        "alg",
        "range(1/(x-1)+1/(x+2))",
        ["y*(x^2 + x - 2) = 2*x + 1", "Discriminant = 9*y^2 + 4 > 0", "Range: all real y", "Answer: all real y"],
        ["inspect graph/transform", "ERR:"],
    ),
    (
        "alg",
        "range(x^3,x,-1,3)",
        ["x^3 is increasing", "Range: -1 <= y <= 27", "Answer: -1 <= y <= 27"],
        ["unrestricted on interval", "inspect graph/transform", "ERR:"],
    ),
    (
        "alg",
        "range(exp(x))",
        ["e^u > 0", "Range: y > 0", "Answer: y > 0"],
        ["inspect graph/transform", "ERR:"],
    ),
    (
        "alg",
        "range(1/(2-cos(3*x)))",
        ["cos(3*x) in [-1,1]", "Answer: 1/3 <= y <= 1"],
        ["inspect graph/transform", "ERR:"],
    ),
    (
        "alg",
        "range(1/(5+sin(x)+sqrt(3)*cos(x)),x,0,2*pi)",
        ["R = sqrt((1)^2 + (sqrt(3))^2) = 2", "3 <= denominator <= 7", "Answer: 1/7 <= y <= 1/3"],
        ["unrestricted", "ERR:"],
    ),
    (
        "alg",
        "range(1/(1+tan(x)),0<=x,x<pi/2)",
        ["0<=x<pi/2=>0<=tan(x)<infinity", "1<=tan(x)+1<infinity", "Answer: 0<y<=1"],
        ["unrestricted", "ERR:"],
    ),
    (
        "alg",
        "range((sin(x)+sqrt(3)*cos(x))^2,x,0,2*pi)",
        ["R = sqrt((1)^2 + (sqrt(3))^2) = 2", "-2 <= sin(x) + sqrt(3)*cos(x) <= 2", "Answer: 0 <= y <= 4"],
        ["unrestricted", "ERR:"],
    ),
    (
        "alg",
        "range(cot((x+1)/3))",
        ["Range: all real y", "Answer: all real y"],
        ["inspect graph/transform", "ERR:"],
    ),
    (
        "alg",
        "domain(arccos(sin((x+1)/3)))",
        ["acos(u): -1 <= u <= 1", "-1 <= sin((x + 1)/3) <= 1", "Answer: all real x"],
        ["Answer: -1 <= sin", "inspect graph/transform", "ERR:"],
    ),
    (
        "alg",
        "domain((3*ln(x)-7)/(ln(x)-2))",
        ["Domain: ln(x) - 2 != 0", "Domain: x != e^2", "Domain: x > 0"],
        ["ERR:"],
    ),
    (
        "trig",
        "sqrt(1-cos(x))=sin(x),x,0,2*pi,8,method=square_then_check",
        ["Square both sides", "cos(x)*(cos(x) - 1) = 0", "Check in original", "Answer: x = [0, pi/2"],
        ["Answer: x = []", "ERR:"],
    ),
    (
        "trig",
        "3*cos(x)+4*sin(x)=2,x,0,2*pi,8,method=rform",
        ["R = sqrt(3^2 + 4^2) = 5", "cos(alpha)=3/5", "cos(x-alpha)=2/5", "Answer: x = [arctan(4/3)+arccos(2/5), 2*pi+arctan(4/3)-arccos(2/5)]"],
        ["Answer: x = [2.", "ERR:"],
    ),
    (
        "trig",
        "sqrt(3)*sin(x)+cos(x)=sqrt(3),x,0,2*pi,10,method=rform",
        ["beta = pi/3", "alpha = pi/6", "x+alpha = pi/3+2*pi*n", "Answer: x = [pi/6, pi/2]"],
        [" deg", "+360n", "ERR:"],
    ),
    (
        "trig",
        "sqrt(2)*cos(theta)-sqrt(6)*sin(theta),method=rform",
        ["R=sqrt(sqrt(2)^2+sqrt(6)^2)=2*sqrt(2)", "R*cos(theta+alpha)", "tan(alpha)=sqrt(6)/sqrt(2)", "alpha=60 deg", "2*sqrt(2)*cos(theta + 60)"],
        ["2.449", "ERR:"],
    ),
    (
        "trig",
        "2*sqrt(2)*cos(x)+2*sqrt(2)*sin(x),method=rform",
        ["R*sin(x+alpha)", "alpha = pi/4", "4*sin(x+pi/4)"],
        ["ERR:"],
    ),
    (
        "trig",
        "2*cos(x)+2*sin(x),method=rform",
        ["alpha=pi/4", "sqrt(8)*cos(x-pi/4)"],
        ["atan(1)", "ERR:"],
    ),
    (
        "trig",
        "6/(2*cos(3*x)+2*sin(3*x))-sqrt(6)=0,x,0,pi,10,method=rform",
        ["6/(2*cos(3*x)+2*sin(3*x))=sqrt(6)", "2*cos(3*x)+2*sin(3*x)=sqrt(6)", "x=[pi/36,5*pi/36,25*pi/36,29*pi/36]"],
        ["x=[]", "ERR:"],
    ),
    (
        "trig",
        "cos(2*theta)+sqrt(3)*sin(2*theta)=2*cos(theta),theta,0,2*pi,10,method=rform",
        ["cos(2*theta)+sqrt(3)*sin(2*theta)=2*cos(2*theta-pi/3)", "cos(2*theta-pi/3)=cos(theta)", "theta=[pi/9,pi/3,7*pi/9,13*pi/9]"],
        ["theta = []", "ERR:"],
    ),
    (
        "trig",
        "sin(x)+3*cos(x)=0,x,method=identity",
        ["cos(x)!=0", "(sin(x)+3*cos(x))/cos(x)=0", "tan(x)+3=0", "tan(x)=-3"],
        ["R*cos", "ERR:"],
    ),
    (
        "trig",
        "cot(75*pi/180),target=2-sqrt(3),method=identity",
        ["tan(5*pi/12)=(tan(pi/4)+tan(pi/6))/(1-tan(pi/4)*tan(pi/6))", "cot(5*pi/12)=1/(2+sqrt(3))", "2-sqrt(3)"],
        ["Source = target", "ERR:"],
    ),
    (
        "trig",
        "4*sin(x)-3*cos(x),method=rform",
        ["R = sqrt(4^2+3^2) = 5", "R*sin(x-alpha)", "5*sin(x-atan(3/4))"],
        ["ERR:"],
    ),
    (
        "trig",
        "sin(x)=-1,x,0,360",
        ["sin(x) = -1", "x = 270 + n*360", "0 <= x <= 360", "Answer: x = [270]"],
        ["alpha = arcsin(-1) = -pi/2 for x\n0 <= x <= 360", "ERR:"],
    ),
    (
        "trig",
        "cos(x)=1/2,x,0,360",
        ["alpha = arccos(1/2)", "x = alpha + 360n or x = 360-alpha + 360n", "0 <= 60 + n*360 <= 360 => n = 0", "Answer: x = [60, 300]"],
        ["ERR:", "Unexpected token"],
    ),
    (
        "trig",
        "sin(2*x)+cos(2*x)=0,x,-180,180",
        ["A = 2*x", "cos(A)=0 => sin(A)+cos(A)=+/-1 != 0", "(sin(A)+cos(A))/cos(A)=0/cos(A)", "tan(2*x)=sin(2*x)/cos(2*x)", "tan(2*x)=-1", "x = -22.5 + n*90", "x = [-112.5, -22.5, 67.5, 157.5]"],
        ["Divide by cos(2x) where valid", "Solve the tan equation", "ERR:"],
    ),
    (
        "trig",
        "sin(2*x)+cos(2*x)=0,x,0,pi",
        ["x = -pi/8 + n*pi/2", "0 <= x <= pi", "x = [3*pi/8, 7*pi/8]"],
        ["NEEDS_REVIEW", "ERR:"],
    ),
    (
        "trig",
        "cos(2*x)=1/2,x,0,360",
        ["u = cos(x)", "cos(2*x) = 2u^2-1", "2u^2 - 1.5 = 0", "Answer: x = [30, 150, 210, 330]"],
        ["2u^2u", "ERR:"],
    ),
    (
        "trig",
        "4*tan(theta)^2*cos(theta)=15,theta,0,360",
        ["tan(theta) = s/c", "c!=0; 4s^2-15c = 0", "s^2 = 1-c^2", "-4c^2-15c+4 = 0", "Answer: theta = [75.5224878141, 284.477512186]"],
        ["theta = []", "cos(theta) = 0", "ERR:"],
    ),
    (
        "trig",
        "(sin(x)-cos(x))/cos(x)=2,x,0,360",
        ["s-3c = 0", "s/c=3", "tan(x) = 3", "Answer: x = [71.5650511771, 251.565051177]"],
        ["x = []", "tan(A)", "ERR:"],
    ),
    (
        "trig",
        "(2*sin(x)*cos(x))/(cos(x)^2-sin(x)^2)=sin(x)/cos(x),x,0,180",
        ["tan(2*x) = 2*sin(x)*cos(x)/(cos(x)^2 - sin(x)^2)", "tan(2*x) = tan(x)", "cos(A)!=0, cos(B)!=0", "x = [0, 180]"],
        ["2sin(x)cos(x)", "ERR:"],
    ),
    (
        "trig",
        "cos(2*x)+2*cos(x)=1,x,0,360",
        ["u=cos(x)", "cos(2*x)=2u^2-1", "2u^2 + 2u - 2 = 0", "Reject u"],
        ["x = []", "ERR:"],
    ),
    (
        "trig",
        "sin(x)^4,method=double_angle",
        ["sin(x)^2=(1-cos(2*x))/2", "cos(2*x)^2=(1+cos(4*x))/2", "Answer: (3 - 4*cos(2*x) + cos(4*x))/8"],
        ["Answer: sin(x)^4", "ERR:"],
    ),
    (
        "int",
        "sin(x)^2",
        ["sin(x)^2 = (1-cos(2*x))/2", "I = 1/2*Int(1-cos(2*x)) dx", "Answer: x/2 - sin(2*x)/4 + C"],
        ["Done", "ERR:"],
    ),
    (
        "int",
        "cos(x)^2",
        ["cos(x)^2 = (1+cos(2*x))/2", "I = 1/2*Int(1+cos(2*x)) dx", "Answer: x/2 + sin(2*x)/4 + C"],
        ["Done", "ERR:"],
    ),
    (
        "int",
        "sin(x)^6,method=trig",
        ["sin(x)^6", "cos(2u)", "cos(4u)", "cos(6u)", "5/16*x", "- 15/64*sin(2*x)", "Answer:"],
        ["No elementary primitive", "Answer: int(", "ERR:"],
    ),
    (
        "int",
        "cos(x)^6,method=trig",
        ["cos(x)^6", "cos(2u)", "cos(4u)", "cos(6u)", "5/16*x", "+ 15/64*sin(2*x)", "Answer:"],
        ["No elementary primitive", "Answer: int(", "ERR:"],
    ),
    (
        "alg",
        "domain(arcsin((x-1)/3))",
        ["Domain: -2 <= x <= 4", "Domain: -1 <= (x - 1)/3 <= 1", "Answer: -2 <= x <= 4"],
        ["inspect graph/transform", "ERR:"],
    ),
    (
        "int",
        "1-cos(2*x+pi/6)^2,method=auto",
        ["Use sin(u)^2=1-cos(u)^2", "u=2*x + pi/6", "Answer: x/2 - sin(4*x + pi/3)/8 + C"],
        ["No elementary A-level primitive", "Classify the integrand", "ERR:"],
    ),
    (
        "alg",
        "1/(x-1)+1/(x+2)=1,method=auto",
        ["Domain: x != -2", "x != 1", "(x + 2) + (x - 1) = x^2 + x - 2", "expand => - x^2 + x + 3 = 0", "x = [1/2 - sqrt(13)/2, 1/2 + sqrt(13)/2]"],
        [")/-2", "ERR:", "No real solution"],
    ),
    (
        "alg",
        "1/(x+8)+1/(x-8)=2*x/(x^2-64),method=auto",
        ["Domain: x + 8 != 0 => x != -8", "Domain: x - 8 != 0 => x != 8", "Domain: x^2 - 64 != 0 => x != -8, x != 8", "x^2 - 64 = (x + 8)*(x - 8)", "(x^2 - 64)/(x + 8) = x - 8", "(x^2 - 64)/(x^2 - 64) = 1", "(x - 8) + (x + 8) = 2*x", "expand => 0 = 0", "x in R, x != -8, x != 8"],
        ["LHS-RHS = 0", "x = all real\n", "x = all real values in domain"],
    ),
    (
        "alg",
        "abs(2*x+1)=2,method=auto",
        ["abs(2*x + 1) = 2", "2*x + 1 = 2 => x = 1/2", "2*x + 1 = -2 => x = -3/2", "x = [-3/2, 1/2]"],
        ["x = -1.5", "x = 0.5", "ERR:"],
    ),
    (
        "alg",
        "range(sqrt((x+5)^2))",
        ["Domain: all real x", "Range: y >= 0", "Answer: y >= 0"],
        ["Domain: (x + 5)^2 >= 0", "ERR:"],
    ),
    (
        "trig",
        "1-cos(2*x+pi/6)^2,method=auto",
        ["Use identity 1 - cos(u)^2 = sin(u)^2", "u = 2*x + pi/6", "Answer: sin(2*x + pi/6)^2"],
        ["Simplify using exact trig/algebra rules", "Answer: - cos(2*x + pi/6)^2 + 1", "ERR:"],
    ),
    (
        "trig",
        "tan(x),target=sin(x)/cos(x),method=auto",
        ["Use identity tan(u)=sin(u)/cos(u)", "u = x", "Answer: sin(x)/cos(x)"],
        ["Apply standard identities/rearrangement toward the target", "ERR:"],
    ),
    (
        "int",
        "(x^2+2*x+1)/(x+1),method=auto",
        ["N =", "x^2", "D = x + 1", "N/D = x + 1", "x + 1/2*x^2 + C"],
        ["No elementary A - level primitive", "No elementary A-level primitive", "Answer: int(", "ERR:"],
    ),
    (
        "alg",
        "solve(log(2,x)+log(4,x)=6,x,method=log_exp)",
        ["u = log(2,x)", "log(4,x) = u/2", "3u/2 = 6", "x = 16"],
        ["log/exp laws to combine", "Exponentiate, solve", "ERR:"],
    ),
    (
        "alg",
        "solve(e^(-1/2*x^2)-x^2*e^(-1/2*x^2)=0,x)",
        ["e^(-1/2*x^2) > 0", "- x^2 + 1 = 0", "x = [-1, 1]"],
        ["x = []", "ERR:"],
    ),
    (
        "alg",
        "solve(4/(2*ln(x-1)-3)=-2,x)",
        ["Domain: x - 1 > 0", "ln(x - 1) = 1/2", "x - 1 = sqrt(e)", "x = [sqrt(e) + 1]"],
        ["x = [2.648", "x ~=", "ERR:"],
    ),
    (
        "alg",
        "log(2,8)",
        ["log(a,b)=c means a^c=b", "3"],
        ["log(8)/log(2)", "ERR:"],
    ),
    (
        "alg",
        "solve(log(2,x)+log(x,2)=5/2,x,method=log_exp)",
        ["u = log(2,x)", "log(x,2) = 1/u", "2u^2 - 5u + 2 = 0", "x = sqrt(2) or 4"],
        ["log/exp laws to combine", "Exponentiate, solve", "ERR:"],
    ),
    (
        "alg",
        "solve(log(3,x)+log(x,27)=4,x,method=log_exp)",
        ["u = log(3,x)", "log(x,27) = 3/u", "u^2 - 4u + 3 = 0", "x = 3 or 27"],
        ["log/exp laws to combine", "Exponentiate, solve", "ERR:"],
    ),
    (
        "alg",
        "solve(2*log(10,4-x)=log(10,x+8),x,method=log_exp)",
        ["log(10,(4-x)^2)", "x = 8 or 1", "x = 8 rejected by domain", "x = [1]"],
        ["log/exp laws to combine", "Exponentiate, solve", "ERR:"],
    ),
    (
        "alg",
        "solve(log10(x)=1,x)",
        ["Domain: x > 0", "x = 10", "x = [10]"],
        ["rejected by domain", "x = []", "ERR:"],
    ),
    (
        "alg",
        "solve(log10(3*x-1)=log10(x+5),x)",
        ["Domain: 3*x - 1 > 0", "ln((3*x - 1)/(x + 5)) = 0", "x = [3]"],
        ["rejected by domain", "x = []", "ERR:"],
    ),
    (
        "derive",
        "log10(3*x-1),x",
        ["u = 3*x - 1", "dy/dx = du/dx/(u*ln(10))", "dy/dx = 3/((3*x - 1)*ln(10))"],
        ["ERR:", "limite"],
    ),
    (
        "int",
        "defint(log10(3*x-1)-log10(x+5),x,3,8+sqrt(10))",
        ["log10(u) = ln(u)/ln(10)", "F(8+sqrt(10)) - F(3)"],
        ["ERR:", "No elementary primitive found"],
    ),
    (
        "alg",
        "solve(log(2,x+3)+log(2,x+10)=2+2*log(2,x),x,method=log_exp)",
        ["log(2,(x+3)*(x+10))", "(x + 3)*(x + 10) = 4*x^2", "x = -5/3 rejected by domain", "x = [6]"],
        ["log/exp laws to combine", "Exponentiate, solve", "ERR:"],
    ),
    (
        "alg",
        "range(3+2*sin(4*x-pi/3))",
        ["-1<=sin(4*x-pi/3)<=1", "1<=2*sin(4*x-pi/3)+3<=5", "1<=y<=5"],
        ["unsupported", "ERR:"],
    ),
    (
        "alg",
        "range(3*cos(x)+4*sin(x))",
        ["R=sqrt((4)^2+(3)^2)=5", "-5<=3*cos(x)+4*sin(x)<=5", "-5<=y<=5"],
        ["unsupported", "ERR:"],
    ),
    (
        "alg",
        "period(tan(4*x-pi/3))",
        ["u=4*x-pi/3", "du/dx=4", "period(tan)=pi", "pi/4"],
        ["unsupported", "ERR:"],
    ),
    (
        "alg",
        "sin(asin(x))",
        ["Domain:-1<=x<=1", "sin(asin(x))=x"],
        ["need sin/cos/tan", "ERR:"],
    ),
    (
        "alg",
        "solve(asin(x)=pi/6,x)",
        ["asin(x)=pi/6", "x=sin(pi/6)", "x=1/2"],
        ["need sin/cos/tan", "x=[]", "ERR:"],
    ),
    (
        "alg",
        "solve(pi-3*acos(x+1)=0,x)",
        ["acos(x+1)=pi/3", "-1<=x+1<=1", "x+1=cos(pi/3)", "x=-1/2"],
        ["x=[]", "ERR:"],
    ),
    (
        "int",
        "pi-acos(x+1)",
        ["Int(pi) dx = pi*x", "w=x+1", "Apply inverse trig rule: Int acos(w) dw = w*acos(w) - sqrt(1-w^2)", "pi*x-(x+1)*acos(x+1)+sqrt(-(x+1)^2+1)+C"],
        ["No elementary primitive found", "ERR:"],
    ),
    (
        "int",
        "defint(pi-acos(x+1),x,-2,0)",
        ["F(0)-F(-2)", "F(-2)=-pi", "pi"],
        ["No elementary primitive found", "ERR:"],
    ),
    (
        "trig",
        "cos(x)=sin(x-45),x,0,360,10,method=identity",
        ["sin(U+B)=sin(U)cos(B)+cos(U)sin(B)", "tan(x)=1+sqrt(2)", "x=[67.5,247.5]"],
        ["tan(x)=2.41421", "ERR:"],
    ),
    (
        "alg",
        "inverse(sqrt(3)*cos(x)-sin(x),5*pi/6<=x,x<=11*pi/6)",
        ["y=11*pi/6-acos(x/2)", "f^-1(x)=11*pi/6-acos(x/2)", "Given domain:5*pi/6<=x,x<=11*pi/6"],
        ["no inverse on all real x", "ERR:"],
    ),
    (
        "alg",
        "solve(2*asin(x)-pi/3=0,x)",
        ["asin(x)=pi/6", "-1<=x<=1", "x=sin(pi/6)", "x=1/2"],
        ["x=[]", "ERR:"],
    ),
    (
        "alg",
        "solve(atan(3*x)=pi/4,x)",
        ["atan(3*x)=pi/4", "3*x=tan(pi/4)", "3*x=1", "x=1/3"],
        ["need sin/cos/tan", "x=[]", "ERR:"],
    ),
    (
        "int",
        "defint(3 *(x)/sqrt((3)(x)+ 6),x,0,8)",
        ["u=sqrt(3*x+6)", "x=0=>u=sqrt(6),x=8=>u=sqrt(30)", "8/3*sqrt(30)+8/3*sqrt(6)"],
        ["ERR:", "Expected )"],
    ),
    (
        "alg",
        "binomial((1+3 * x)^( -  1/(2)),(x),0,4)",
        ["n=-1/2", "T1=-3/2*x", "Validforabs(x)<1/3"],
        ["Supported forms", "ERR:"],
    ),
    (
        "alg",
        "solve((ln(4*x+1))^2-2=0,x,0,1)",
        ["ln(4*x+1)^2=2", "ln(4*x+1)=+/-sqrt(2)", "4*x+1=e^(sqrt(2))or4*x+1=e^(-sqrt(2))", "rejectedbyinterval", "x=[(e^(sqrt(2))-1)/4]"],
        ["x=[]", "ERR:"],
    ),
    (
        "int",
        "defint(2-(ln(4*x+1))^2,x,0,(e^(sqrt(2))-1)/4)",
        ["u=4*x+1", "I=-1/4*Int(ln(u)^2)du", "Int(ln(u)^2)du=u*(ln(u)^2-2*ln(u)+2)", "1/2*e^(sqrt(2))*sqrt(2)-1/2*e^(sqrt(2))"],
        ["No elementary primitive found", "ERR:"],
    ),
    (
        "alg",
        "solve(2*x^2+2*x*y+y^2=50,y)",
        ["(y+x)^2=-x^2+50", "y+x=+/-sqrt(-x^2+50)", "y=[-x+sqrt(-x^2+50),-x-sqrt(-x^2+50)]"],
        ["y=[-7.071", "all real", "ERR:"],
    ),
    (
        "derive",
        "4*x/sqrt(4*x^2+9),x",
        ["u=4*x^2+9", "dy/dx=4*(u-4*x^2)/u^(3/2)", "dy/dx=36/(4*x^2+9)^(3/2)"],
        ["ERR:"],
    ),
    (
        "int",
        "defint(2*sqrt(50-x^2),x,-sqrt(50),-5)",
        ["I=2*J,J=Int(sqrt(-x^2+50))dx", "F(-5)=-25-25*pi/2", "25/2*pi-25"],
        ["5*sqrt(2)*0", "ERR:"],
    ),
    (
        "int",
        "defint(2*sqrt(4/x-1)-(4-x),x,2,4)",
        ["x=4*cos(theta)^2", "sqrt(4/x-1)=tan(theta)", "A=(2*pi-4)-2", "2*pi-6"],
        ["-5/3", "ERR:"],
    ),
    (
        "int",
        "defint(6*x^3/sqrt(x^2+1),x,0,2)",
        ["u = x^2+1", "x^2 = u-1", "I = 3*Int_1^5 (u-1)/sqrt(u) du", "4*sqrt(5) + 4"],
        ["ERR:", "No elementary primitive"],
    ),
    (
        "int",
        "defint(1/(20-sqrt(x)),x,0,100)",
        ["u=sqrt(x)", "I=Int_0^10 2u/(20-u) du", "40*ln(2)-20"],
        ["ERR:", "No elementary primitive"],
    ),
    (
        "int",
        "defint(sin(x)*cos(x)*(1+sin(x))^5,x,0,pi/2)",
        ["u=1+sin(x)", "sin(x)=u-1", "107/14"],
        ["ERR:", "No elementary primitive"],
    ),
    (
        "int",
        "defint(x^2/sqrt(4-x^2),x,0,sqrt(2))",
        ["x=2*sin(t)", "I=Int_0^(pi/4)4*sin(t)^2dt", "pi/2-1"],
        ["ERR:", "No elementary primitive"],
    ),
    (
        "int",
        "defint(1/(1+x^2)^2,x,0,1)",
        ["x=tan(t)", "I=Int_0^(pi/4)cos(t)^2dt", "1/8*(pi+2)"],
        ["ERR:", "No elementary primitive"],
    ),
    (
        "int",
        "defint(1/sqrt(3-4*x^2),x,0,3/4)",
        ["x=sqrt(3)/2*sin(t)", "I=1/2*Int_0^(pi/3)dt", "pi/6"],
        ["ERR:", "asin(3/2/sqrt(3))"],
    ),
    (
        "alg",
        "solve(3*e^(3*x)-4*e^(2*x)-5*e^x+2=0,x)",
        ["u = e^(x), u > 0", "(u + 1)*(3*u^2 - 7*u + 2) = 0", "-1 rejected, u > 0", "x = [ln(1/3), ln(2)]"],
        ["x ~=", "-1.098", "0.693"],
    ),
    (
        "alg",
        "solve(2*e^(2*x)-5*e^x+3*e^(-x)=4,x)",
        ["u = e^(x), u > 0", "2*u^2 - 5*u + 3/u - 4 = 0", "- 4*u - 5*u^2 + 2*u^3 + 3 = 0", "(u + 1)*(2*u^2 - 7*u + 3) = 0", "x = [ln(1/2), ln(3)]"],
        ["x ~=", "-0.693", "1.099"],
    ),
    (
        "alg",
        "solve(2^(4*x)-16*4^x=0,x)",
        ["u = 2^x, u > 0", "u^2 = 16", "x = [2]"],
        ["x ~=", "ERR:"],
    ),
    (
        "alg",
        "solve(4*8^(x+1)-2^(x+1)=0,x)",
        ["u = 2^x, u > 0", "u^2 = 1/16", "x = [-2]"],
        ["x ~=", "ERR:"],
    ),
    (
        "alg",
        "solve(4*e^x/(3-e^x)^2=1,x)",
        ["u = e^(x), u > 0", "4*u/(u - 3)^2 = 1", "u^2 - 10*u + 9 = 0", "x = [0, ln(9)]"],
        ["x ~=", "2.197", "ERR:"],
    ),
    (
        "alg",
        "solve(ln(x^2)+3/ln(x)=7,x)",
        ["u = ln(x)", "2*u^2", "u = 3", "u = 1/2", "x = [e^(3), sqrt(e)]"],
        ["x ~=", "20.085", "1.648", "ERR:"],
    ),
    (
        "alg",
        "solve(e^w-3=8/(e^w-1),w)",
        ["u = e^(w), u > 0", "u^2 - 4*u - 5 = 0", "-1 rejected, u > 0", "w = [ln(5)]"],
        ["w ~=", "1.609", "ERR:"],
    ),
    (
        "alg",
        "solve([x+e^y=1,ln((x+1)^2)-2*y=2],[x,y])",
        ["(x + 1)^2 = e^(2)*(e^y)^2", "x + 1 = e*(1 - x)", "x = (e - 1)/(e + 1)", "y = ln(2/(e + 1))"],
        ["solve(", "ERR:"],
    ),
    (
        "alg",
        "solve(e^(x+1)-2=2*(e-1),x)",
        ["e^(x + 1) = 2*e", "x + 1 = ln(2) + 1", "x = ln(2)"],
        ["x ~=", "0.693", "ERR:"],
    ),
    (
        "alg",
        "solve(e^(e^x-2)-3=e,x)",
        ["e^(e^(x) - 2) = e + 3", "e^(x) - 2 = ln(e + 3)", "x = ln(ln(e + 3) + 2)"],
        ["x ~=", "1.320", "ERR:"],
    ),
    (
        "alg",
        "domain(ln((4+e)/(1-e)+1))",
        ["Domain: no real x"],
        ["Domain: all real x", "ERR:"],
    ),
    (
        "alg",
        "solve(ln(e*x^2)*ln(x)=1,x)",
        ["u = ln(x)", "u + 2*u^2 - 1 = 0", "u = 1/2", "u = -1", "x = [sqrt(e), e^(-1)]"],
        ["x ~=", "ERR:"],
    ),
    (
        "alg",
        "solve(e^(2*x-2)-7*e^(x-1)+10=0,x)",
        ["u = e^(x - 1), u > 0", "u^2 - 7*u + 10 = 0", "x = [ln(2) + 1, ln(5) + 1]"],
        ["x ~=", "ERR:"],
    ),
    (
        "alg",
        "solve(6*e^(3*x)+1=7*e^(2*x),x)",
        ["u = e^(x), u > 0", "6*u^3 - 7*u^2 + 1 = 0", "x = [ln(1/2), 0]"],
        ["x ~=", "ERR:"],
    ),
    (
        "alg",
        "solve((3-2*sqrt(2))/ln(x)=ln(x),x)",
        ["u = ln(x)", "(- 2*sqrt(2) + 3)/u = u", "u^2 = - 2*sqrt(2) + 3", "u = +/-sqrt(- 2*sqrt(2) + 3)", "x = [e^(-sqrt(- 2*sqrt(2) + 3)), e^(sqrt(- 2*sqrt(2) + 3))]"],
        ["x ~=", "ERR:"],
    ),
    (
        "alg",
        "solve(6-ln(x+3)=y,x)",
        ["Domain: x + 3 > 0", "ln(x + 3) = - y + 6", "x + 3 = e^(- y + 6)", "x = e^(- y + 6) - 3"],
        ["LHS - RHS", "ERR:"],
    ),
    (
        "alg",
        "6-ln(e^(x^2))",
        ["-x^2 + 6"],
        ["ERR:"],
    ),
    (
        "alg",
        "solve(2+log(2,x)=2*ln(x/sqrt(e)),x)",
        ["Domain: x > 0", "ln(x/sqrt(e)) = ln(x) - 1/2", "log(2,x) = ln(x)/ln(2)", "(1/ln(2) - 2)*ln(x) + 3 = 0", "ln(x) = -3/(1/ln(2) - 2)"],
        ["x = []", "ERR:", "LHS-RHS"],
    ),
    (
        "alg",
        "solve(y*sec(pi/6)^2=(8-2*ln(2))+2*ln(sec(pi/6)),y)",
        ["4/3*y + 2*ln(3)/2 - 8 = 0", "y = - 3/4*ln(3) + 6"],
        ["ERR:"],
    ),
    (
        "alg",
        "solve(e^(4*x)=16^(1/ln(2)),x)",
        ["4*x = 4", "x = 1"],
        ["x ~=", "ERR:"],
    ),
    (
        "alg",
        "solve(e^x=0,x)",
        ["e^(x) > 0", "x = []"],
        ["ln(0)", "ERR:"],
    ),
    (
        "alg",
        "solve(e^x=-2,x)",
        ["e^(x) > 0", "x = []"],
        ["ln(-2)", "ERR:"],
    ),
    (
        "int",
        "defint(3*e^(-2*x),x,0,inf)",
        ["Since -2<0", "I = 0 - F(0)", "3/2"],
        ["e^(-2*inf)", "ERR:"],
    ),
    (
        "int",
        "defint(5*e^(2*x),x,-inf,1)",
        ["Since 2>0", "I = F(1) - 0", "5/2*e^(2)"],
        ["e^(2*-inf)", "ERR:"],
    ),
    (
        "int",
        "defint(e^x,x,0,inf)",
        ["grows without bound", "I = divergent"],
        ["e^inf - 1", "ERR:"],
    ),
    (
        "int",
        "defint(e^(-x),x,-inf,inf)",
        ["one exponential tail grows without bound", "I = divergent"],
        ["e^inf", "ERR:"],
    ),
    (
        "int",
        "defint(1/(x*(2*x+5)),x,1,inf)",
        ["1/(x(2*x + 5)) = 1/5/x - 2/5/(2*x + 5)", "lim_{T->inf} T/(2*T + 5) = 1/2", "1/5*ln(7/2)"],
        ["inf/(2*inf + 5)", "ERR:"],
    ),
    (
        "int",
        "defint((8*x-12)/((2*x^2+3)*(x+1)),x,0,inf)",
        ["(8*x - 12)/((2*x^2 + 3)*(x + 1)) = 8*x/(2*x^2 + 3) - 4/(x + 1)", "lim_{T->inf} (2*T^2 + 3)/(T + 1)^2 = 2", "ln(4/9)"],
        ["Expected )", "ERR:"],
    ),
    (
        "int",
        "defint(2/(t*(3*t+7)),t,1,inf)",
        ["2/(t(3*t + 7)) = 2/7/t - 6/7/(3*t + 7)", "lim_{T->inf} T/(3*T + 7) = 1/3", "2/7*ln(10/3)"],
        ["inf/(3*inf + 7)", "ERR:"],
    ),
    (
        "int",
        "int(sinh(y)^2,y)",
        ["sinh(u)^2 = (cosh(2u)-1)/2", "sinh(2*y)/4 - y/2 + C"],
        ["No elementary primitive", "ERR:"],
    ),
    (
        "int",
        "defint(pi*sinh(y)^2,y,0,ln(3)/2)",
        ["sinh(u)^2 = (cosh(2u)-1)/2", "F(ln(3)/2) = 1/3*pi - 1/4*pi*ln(3)", "1/3*pi - 1/4*pi*ln(3)"],
        ["No elementary primitive", "sinh(ln(3))", "sinh(0)", "ERR:"],
    ),
    (
        "int",
        "int(cosh(2*y)^2,y)",
        ["cosh(u)^2 = (cosh(2u)+1)/2", "(sinh(4*y)/4 + y)/2 + C"],
        ["No elementary primitive", "ERR:"],
    ),
    (
        "derive",
        "cosh(x)^n,x,method=second",
        ["dy/dx = n*cosh(x)^(n-1)*sinh(x)", "sinh(x)^2 = cosh(x)^2 - 1", "d2y/dx2 = n^2*cosh(x)^n - n*(n-1)*cosh(x)^(n-2)"],
        ["limite", "ERR:"],
    ),
    (
        "alg",
        "solve(2*sqrt(5)*u^2+3*u-sqrt(5)=0,u,0,1)",
        ["Interval: u in [0, 1]", "u = sqrt(5)/5", "u = [sqrt(5)/5]"],
        ["u = -sqrt(5)/2", "ERR:"],
    ),
    (
        "alg",
        "maclaurin(e^(e^x-1),x,3)",
        ["e^x = 1 + x + 1/2*x^2 + 1/6*x^3", "u = x + 1/2*x^2 + 1/6*x^3", "1 + x + x^2 + 5/6*x^3"],
        ["unsupported", "ERR:"],
    ),
    (
        "alg",
        "solve(sinh(3*x)=19*sinh(x),x)",
        ["sinh(3*x) = 4*sinh(x)^3 + 3*sinh(x)", "x = ln(2 + sqrt(5))", "x = ln(-2 + sqrt(5))"],
        ["x = []", "ERR:"],
    ),
    (
        "derive",
        "atanh((3-x)/(6+x)),x",
        ["dy/dx = u'/(1-u^2)", "dy/dx = -1/(2*x + 3)"],
        ["ERR:"],
    ),
    (
        "derive",
        "atanh((3-x)/(6+x)),x,method=second",
        ["dy/dx = -1/(2*x + 3)", "d2y/dx2 = 2/(2*x + 3)^2"],
        ["ERR:"],
    ),
    (
        "alg",
        "maclaurin(atanh((3-x)/(6+x)),x,2)",
        ["f(0) = 1/2*ln(3)", "1/2*ln(3) - 1/3*x + 1/9*x^2"],
        ["unsupported", "ERR:"],
    ),
    (
        "int",
        "defint(1/(9*x^2+16),x,4/3,inf)",
        ["lim_{T->inf}", "lim_{T->inf} atan(3/4*T) = pi/2", "1/48*pi"],
        ["atan(3/4*inf)", "ERR:"],
    ),
    (
        "alg",
        "partfrac(2/((r+4)*(r+6)))",
        ["A/(r + 4)+B/(r + 6)", "A = 1, B = -1"],
        ["Domain:", "ERR:"],
    ),
    (
        "derive",
        "mode:8,e^(3*x)*sin(x),x",
        ["Leibnitz: d4y/dx4", "u'''' = 81*e^(3*x)", "v'''' = sin(x)", "d4y/dx4 = 28*e^(3*x)*sin(x) + 96*e^(3*x)*cos(x)"],
        ["limite", "ERR:"],
    ),
    (
        "derive",
        "mode:8,e^(2*x)*cos(3*x),x",
        ["Leibnitz: d4y/dx4", "v'''' = 81*cos(3*x)", "d4y/dx4 = - 119*e^(2*x)*cos(3*x) + 120*e^(2*x)*sin(3*x)"],
        ["limite", "ERR:"],
    ),
    (
        "derive",
        "ln(e^(2*x)*cos(3*x)),x",
        ["ln(uv)=ln(u)+ln(v)", "dy/dx = 2 - 3*tan(3*x)"],
        ["limite", "ERR:"],
    ),
    (
        "derive",
        "mode:8,ln(e^(2*x)*cos(3*x)),x",
        ["d2y/dx2 = -9*sec(3*x)^2", "d4y/dx4 = -162*sec(3*x)^4 - 324*sec(3*x)^2*tan(3*x)^2"],
        ["limite", "ERR:"],
    ),
    (
        "alg",
        "maclaurin(ln(e^(2*x)*cos(3*x)),x,4)",
        ["ln(1+u) = u - u^2/2 + u^3/3 - u^4/4", "2*x - 9/2*x^2 - 27/4*x^4"],
        ["ERR:", "unsupported"],
    ),
    (
        "int",
        "1/(2*sin(x)-cos(x)+5),method=weierstrass",
        ["t = tan(x/2)", "I = Int 1/(3t^2+2t+2) dt", "1/sqrt(5)*atan((3*tan(x/2) + 1)/sqrt(5)) + C"],
        ["ERR:", "No elementary primitive"],
    ),
    (
        "alg",
        "solve(4=16*(1-e^2),e,0,1)",
        ["e^2 = 3/4", "e = [sqrt(3)/2]"],
        ["ERR:", "e = []"],
    ),
    (
        "alg",
        "taylor(ln(x),x,1,2)",
        ["f'(x) = 1/x", "f''(x) = -1/x^2", "ln(x) = (x-1) - 1/2*(x-1)^2"],
        ["ERR:", "limite"],
    ),
    (
        "alg",
        "lim(ln(x)/(x-1),x,1)",
        ["ln(x)/(x-1) = 1 - 1/2*(x-1)", "1"],
        ["ERR:", "limite"],
    ),
    (
        "alg",
        "lim(1/((x+3)*tan(6*x)*cosec(2*x)),x,0)",
        ["f(0) = 0, g(0) = 0", "f'(x) = 2*cos(2*x)*cos(6*x)-6*sin(2*x)*sin(6*x)", "1/9"],
        ["ERR:"],
    ),
    (
        "alg",
        "compare((sin(x)-cos(x)+1)/(sin(x)+cos(x)-1),sec(x)+tan(x))",
        ["t = tan(x/2)", "LHS = (2t^2+2t)/(2t-2t^2) = (1+t)/(1-t)", "equivalent"],
        ["ERR:"],
    ),
    (
        "int",
        "defint(5/(4+2*cos(theta)),theta,0,pi/2)",
        ["t = tan(theta/2)", "I = Int_0^1 5/(3+t^2) dt", "5*pi*sqrt(3)/18"],
        ["ERR:", "No elementary primitive"],
    ),
    (
        "int",
        "de_solve(du/dt+u*tanh(t)=1+3/cosh(t),u(0)=27)",
        ["p = tanh(t)", "mu = cosh(t)", "u = (3*t + sinh(t) + 27)/(cosh(t))"],
        ["ERR:", "RHS Int", "IF Int"],
    ),
    (
        "alg",
        "taylor((1+ln(x))^2,x,1,3)",
        ["y(1) = 1, y'(1) = 2, y''(1) = 0, y'''(1) = -2", "(1+ln(x))^2 = 1 + 2*(x-1) - 1/3*(x-1)^3"],
        ["ERR:", "limite"],
    ),
    (
        "alg",
        "lim((2*x-1-(1+ln(x))^2)/(x-1)^3,x,1)",
        ["2*x - 1 - (1+ln(x))^2 = 1/3*(x-1)^3", "1/3"],
        ["ERR:", "limite"],
    ),
    (
        "alg",
        "lim((exp(sin(x))-cos(3*x)-e)/tan(2*x),x,pi/2)",
        ["f(pi/2) = 0, g(pi/2) = 0", "f'(x) = cos(x)*e^(sin(x))+3*sin(3*x)", "-3/2"],
        ["ERR:", "limite"],
    ),
    (
        "alg",
        "taylor(x^4*sin(2*x),x,pi,8)",
        ["f^(8)(pi) = -4096*pi^3+43008*pi", "coeff = (f^(8)(pi))/8!=(336*pi-32*pi^3)/315"],
        ["ERR:", "limite"],
    ),
    (
        "alg",
        "solve(abs(3*t^2-25*t+8)<abs(5*t-31),t,0,inf)",
        ["N = 0: t = -1, 5 - 2*sqrt(3), 23/3, 5 + 2*sqrt(3)", "0 <= t < 5 - 2*sqrt(3) or 23/3 < t < 5 + 2*sqrt(3)"],
        ["ERR:", "Unexpected character"],
    ),
    (
        "int",
        "defint(3/(13+6*sin(x)-5*cos(x)),x,pi/3,4*pi/3)",
        ["t = tan(x/2)", "Split at x = pi", "sqrt(3)/3*(atan((sqrt(3) - 9)/3) - atan((sqrt(3) + 3)/3) + pi)"],
        ["ERR:", "No elementary primitive"],
    ),
    (
        "alg",
        "solve(4*x+abs(3*x+2)=1,x)",
        ["x <= -2/3", "x = 3 (reject)", "x = [-1/7]"],
        ["ERR:"],
    ),
    (
        "derive",
        "(2*x^2+1)/(3*x^2+1),x,method=quotient",
        ["[(4*x)*(3*x^2 + 1)-(2*x^2 + 1)*(6*x)] = -2*x", "dy/dx = -2*x/(3*x^2 + 1)^2"],
        ["ERR:"],
    ),
    (
        "derive",
        "(8*x^2+8*x+3)/(2*x+1)^2,x,method=quotient",
        ["(16*x + 8)*(2*x + 1) - 4*(8*x^2 + 8*x + 3) = -4", "dy/dx = -4/(2*x + 1)^3"],
        ["4*-1", "ERR:"],
    ),
    (
        "derive",
        "2*atan(x)-3*ln(1+x^2)-7*x^2,x",
        ["d/dx(2*atan(x)) = 2/(x^2 + 1)", "- 6*x - 14*x*(x^2 + 1) + 2 = 2*(-7*x^3 - 10*x + 1)"],
        ["-2*(7*x^3 - 10*x + 1)", "ERR:"],
    ),
    (
        "derive",
        "x^3*e^(-2*x),x,method=product",
        ["dy/dx = e^(-2*x)*x^2*(-2*x + 3)"],
        ["ERR:"],
    ),
    (
        "alg",
        "range(2*(2*sin(x)+2*cos(x))+1)",
        ["R = sqrt((4)^2 + (4)^2)", "Range: -sqrt(32) + 1 <= y <= sqrt(32) + 1"],
        ["inspect graph/transform", "ERR:"],
    ),
    (
        "alg",
        "evalat(sin(6*x),x,5*pi/18)",
        ["f(5*pi/18) = -1/2*sqrt(3)"],
        ["sin(6*5*pi/18)", "ERR:"],
    ),
    (
        "alg",
        "evalat(sin(x),x,-5*pi/6)",
        ["f(-5*pi/6) = -1/2"],
        ["f(-5*pi/6) = 1/2", "ERR:"],
    ),
    (
        "alg",
        "partfrac((2*x^3+x^2-4*x+1)/(x^2+x-2))",
        ["= 2*x - 1 + 1/(x + 2)", "A = 2, B = -1, C = 1, D = 2"],
        ["ERR:"],
    ),
    (
        "alg",
        "evalat(x*e^(2*x),x,1/2)",
        ["f(1/2) = 1/2*e"],
        ["1.359140", "ERR:"],
    ),
    (
        "alg",
        "solve(x^4+x^2+2=0,x,method=substitution)",
        ["u = x^2", "D = -7 < 0", "x = []"],
        ["ERR:"],
    ),
    (
        "trig",
        "8*sin(theta)+2*sqrt(3)*cos(theta)=6,theta,0,180,10,method=rform",
        ["R = sqrt(2*sqrt(3)^2+8^2) = 2*sqrt(19)", "sin(theta+alpha) = 3*sqrt(19)/19", "theta = [20.0782948987, 113.095256209]"],
        ["R = sqrt(2*sqrt(3)^2+8^2) = 8.717", "ERR:"],
    ),
    (
        "trig",
        "cosec(4*x)+cot(4*x)=1,x,0,2*pi,method=identity",
        ["cosec(4*x)+cot(4*x) = (1+cos(4*x))/sin(4*x)", "cot(2*x) = 1", "x = [pi/8, 5*pi/8, 9*pi/8, 13*pi/8]"],
        ["x = []", "ERR:"],
    ),
    (
        "trig",
        "(1+cos(2*theta))/sin(2*theta),target=cot(theta),method=auto",
        ["1+cos(2*theta) = 2*cos(theta)^2", "sin(2*theta) = 2*sin(theta)*cos(theta)", "= cot(theta)"],
        ["Source = target", "ERR:"],
    ),
    (
        "trig",
        "(1+cos(2*(x+pi/3)))/sin(2*(x+pi/3)),target=cot(x+pi/3),method=auto",
        ["1+cos(2*(x + pi/3)) = 2*cos(x + pi/3)^2", "= cot(x + pi/3)"],
        ["Source = target", "ERR:"],
    ),
]

REMOVED_FEATURE_MARKERS = (
    "mean_value(", "volume_x(", "volume_y(", "area_between(",
    "param_area(", "param_area_y(", "param_volume",
    "ztest(", "covariance(", "correlation(", "linear_regression(",
    "median(", "mean(", "quartiles(", "stddev(", "stdev(",
    "method=summary",
    "method=weierstrass", "sinh", "cosh", "tanh", "asinh", "acosh", "atanh", "arcosh",
    "taylor(", "maclaurin(",
    "solve(z^", "d2", "mode:5", "mode:7", "mode:8", "method=third", "method=param_second",
)


def compact(text: str) -> str:
    s = "".join(ch for ch in text if ch not in " \t\r\n*").lower()
    for old, new in (
        ("integral", "int"),
        ("answer:", ""),
        ("result:", ""),
        ("use", ""),
        ("identity", ""),
        ("startwith", ""),
        ("let", ""),
        ("then", ""),
        ("hence", ""),
        ("therefore", ""),
        ("so", ""),
        ("baseangle:", "baseangle"),
        ("equatecoefficients", "coeffs"),
        ("differentiatebothsides", "d/dx"),
        ("cleardenominators", "cleardenoms"),
        ("simplifybothexpressions", "bothexpressions"),
        ("collectdy/dx", "dy/dxterms"),
        ("splitatu=0,so", "splitatu=0;"),
        ("splitatu=0,", "splitatu=0;"),
    ):
        s = s.replace(old, new)
    return s


def run(flag: str, expr: str) -> str:
    proc = subprocess.run(
        [str(HOST), "--" + flag, expr],
        cwd=str(REPO),
        text=True,
        capture_output=True,
        timeout=15,
    )
    return proc.stdout + proc.stderr


def main() -> int:
    if not HOST.exists():
        raise SystemExit(f"Missing host binary: {HOST}")
    bad = 0
    total = 0
    for flag, expr, needles, forbidden in CASES:
        if any(marker in expr for marker in REMOVED_FEATURE_MARKERS):
            print("SKIP removed", flag, expr)
            continue
        total += 1
        out = run(flag, expr)
        norm = compact(out)
        low_signal = {"", "parts", "method", "d/dx", "collectiterms", "partialfractions", "checkinoriginal", "integratex+1"}
        required = [compact(n) for n in needles if compact(n) not in low_signal]
        ok = all(n in norm for n in required)
        ok = ok and not any(f in out for f in forbidden)
        if ok:
            print("OK", flag, expr)
            continue
        bad += 1
        print("FAIL", flag, expr)
        print(out)
    print("done mismatches", bad, "/", total)
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
