@fmenu.standard
F1 alg
simplify(
factor(
partfrac(
tcollect(
texpand(
sum(
F2 calc
'
diff(
integrate(
limit(
series(
solve(
desolve(
rsolve(
F3 2d
reserved
F4 cat
reserved
F5 A<>a
reserved
F6 poly
proot(
pcoeff(
quo(
rem(
gcd(
egcd(
F7 arit
!
irem(
ifactor(
gcd(
isprime(
lcm(
F8 mat
matrix(
det(
matpow(
tran(
rref(
inv(
F9 stat
mean(
median(
stddev(
quartile1(
quartile3(
correlation(
linear_regression(
F: prob
binomial(
normald(
poisson(
student(
chisquare(
F; real
exact(
approx(
floor(
ceil(
round(
sign(
max(
min(
F< trig
sin(
cos(
tan(
tcollect(
texpand(
tlin(
F= cplx
abs(
arg(
re(
im(
conj(
csolve(
cfactor(
@END
