#!/usr/bin/env python3
"""Emit host_port_exports.h from a linked host_port.elf (sh3eb-elf-nm)."""
from __future__ import annotations

import argparse
import re
import subprocess
from pathlib import Path

SYM_RE = re.compile(
    r"^([0-9a-f]+)\s+[TtWw]\s+(_?cascas_host_\w+|_rominram_vma_(?:start|end))\s*$"
)


def parse_nm(elf: Path) -> dict[str, int]:
    out = subprocess.check_output(["sh3eb-elf-nm", str(elf)], text=True, errors="replace")
    syms: dict[str, int] = {}
    for line in out.splitlines():
        m = SYM_RE.match(line.strip())
        if not m:
            continue
        addr = int(m.group(1), 16)
        name = m.group(2).lstrip("_")
        syms[name] = addr
    return syms


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("elf", type=Path)
    ap.add_argument("header", type=Path)
    args = ap.parse_args()

    syms = parse_nm(args.elf)
    base = syms.get("rominram_vma_start")
    end = syms.get("rominram_vma_end")
    if base is None or end is None or end <= base:
        raise SystemExit(f"missing rominram symbols in {args.elf}")

    diff = syms.get("cascas_host_diff_run")
    integrate = syms.get("cascas_host_integrate_run")
    if diff is None or integrate is None:
        raise SystemExit(f"missing cascas_host_* symbols in {args.elf}")

    size = end - base
    lines = [
        "#pragma once",
        "/* Generated by gen_host_port_exports.py - do not edit. */",
        f"#define HOST_PORT_RAM_BASE  0x{base:08x}u",
        f"#define HOST_PORT_RAM_SIZE  0x{size:08x}u",
        f"#define HOST_PORT_OFF_cascas_host_diff_run  0x{diff - base:08x}u",
        f"#define HOST_PORT_OFF_cascas_host_integrate_run  0x{integrate - base:08x}u",
        "",
    ]
    # Calculator runtime uses HOST_PORT_RAM_BASE; must match casio_host_ram.ld.
    args.header.write_text("\n".join(lines), encoding="ascii")
    print(f"wrote {args.header}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
