#!/usr/bin/env python3
from __future__ import annotations

import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "khicas/upstream/giac90_1addin"
RUNNER = ROOT / "tools/khicas_host_runner"

REMOVED = [
    "normalcdf",
    "binomcdf",
    "binompdf",
    "mean",
    "median",
    "stddev",
    "variance",
    "det",
    "plot",
    "plotlist",
    "plotparam",
    "plotpolar",
    "plotseq",
    "paramplot",
    "seqplot",
    "funcplot",
    "plotdensity",
    "plotmatrix",
    "densityplot",
    "graphe",
    "polarplot",
    "courbe_polaire",
    "plotimplicit",
    "implicitplot",
    "conic",
    "quadric",
    "reduced_conic",
    "reduced_quadric",
    "courbe_parametrique",
    "graphe_suite",
    "rand",
    "randint",
    "randperm",
    "ranv",
    "ranm",
    "mod",
    "irem",
    "smod",
    "permuorder",
    "concat",
    "extend",
    "select",
    "filter",
    "remove",
    "csolve",
    "cfactor",
    "cpartfrac",
    "complex",
    "abcuv",
    "iabcuv",
    "egcd",
    "iegcd",
    "interp",
    "jordan",
    "jordanblock",
    "gramschmidt",
    "hermite",
    "laguerre",
    "legendre",
    "tchebyshev1",
    "tchebyshev2",
    "residue",
    "resultant",
    "sinh",
    "cosh",
    "tanh",
    "asinh",
    "acosh",
    "atanh",
    "python",
    "program",
    "bloc",
    "ifte",
    "for",
    "while",
    "local",
    "return",
    "try_catch",
    "throw",
    "break",
    "continue",
    "inputform",
    "choosebox",
    "output",
    "input",
    "dialog",
    "pause",
    "sleep",
    "execute",
    "numpy",
    "pylab",
    "matplotlib",
    "crypto",
    "set_pixel",
    "draw_pixel",
    "matrix",
    "trace",
    "transpose",
    "cholesky",
    "about",
    "sign",
    "comb",
    "perm",
    "binomial_cdf",
    "binomial_icdf",
    "normald",
    "normal_cdf",
    "normal_icdf",
    "normald_cdf",
    "normald_icdf",
    "uniformd",
    "uniform_cdf",
    "uniform_icdf",
    "uniformd_cdf",
    "uniformd_icdf",
    "poisson",
    "poisson_cdf",
    "poisson_icdf",
    "randbinomial",
    "randpoisson",
    "randnormald",
    "normalvariate",
    "stdDev",
    "stddevp",
    "quartile1",
    "quartile3",
    "quartiles",
    "moustache",
    "histogram",
    "camembert",
    "covariance",
    "correlation",
    "laplace",
    "ilaplace",
    "fourier",
    "fourier_an",
    "fourier_bn",
    "fourier_cn",
    "odesolve",
    "desolve",
    "plotode",
    "plotfield",
    "fft",
    "ifft",
    "read",
    "write",
    "charpoly",
    "pcar",
    "gaussjord",
    "pivot",
    "keep_pivot",
    "minor_det",
    "rational_det",
    "assume",
    "asc",
    "char",
    "euler",
    "barplot",
    "bar_plot",
    "scatterplot",
    "listplot",
    "polygonplot",
    "polygonscatterplot",
    "halftan",
    "halftan_hyp2exp",
    "exp2trig",
    "trig2exp",
    "evalc",
    "mult_c_conjugate",
    "q2a",
    "a2q",
    "turtle",
    "denom",
    "numer",
    "comDenom",
    "getDenom",
    "curl",
    "ichinrem",
    "iquorem",
    "conj",
    "re",
    "im",
    "plotarea",
    "plotfunc",
    "plotcontour",
    "point",
    "point2d",
    "point3d",
    "polar_point",
    "line",
    "half_line",
    "line_inter",
    "single_inter",
    "segment",
    "circle",
    "bitmap",
    "bezier",
    "animation",
    "hyperplan",
    "hypersphere",
    "hypersurface",
    "frame_3d",
    "plot3d",
    "graphe3d",
    "plotinequation",
    "inequationplot",
    "envelope",
    "locus",
    "linetan",
    "tabvar",
    "gl_x",
    "gl_y",
    "draw_arc",
    "draw_circle",
    "draw_line",
    "draw_polygon",
    "draw_rectangle",
    "cone",
    "cube",
    "cylinder",
    "dodecahedron",
    "icosahedron",
    "octahedron",
    "sphere",
    "tetrahedron",
    "volume",
    "python_compat",
    "exponentiald",
    "exponentiald_cdf",
    "exponentiald_icdf",
    "betad",
    "betad_cdf",
    "betad_icdf",
    "cauchyd",
    "cauchyd_cdf",
    "cauchyd_icdf",
    "gammad",
    "gammad_cdf",
    "gammad_icdf",
    "geometric",
    "geometric_cdf",
    "geometric_icdf",
    "weibulld",
    "weibulld_cdf",
    "weibulld_icdf",
    "student",
    "studentd",
    "student_cdf",
    "studentd_cdf",
    "student_icdf",
    "studentd_icdf",
    "chisquare",
    "chisquared",
    "chisquare_cdf",
    "chisquared_cdf",
    "chisquare_icdf",
    "chisquared_icdf",
    "fisher",
    "fisherd",
    "fisher_cdf",
    "fisherd_cdf",
    "fisher_icdf",
    "fisherd_icdf",
    "snedecor",
    "snedecord",
    "snedecor_cdf",
    "snedecord_cdf",
    "snedecor_icdf",
    "snedecord_icdf",
    "cauchy",
    "cauchy_cdf",
    "cauchy_icdf",
    "weibull",
    "weibull_cdf",
    "weibull_icdf",
    "exponential",
    "exponential_cdf",
    "exponential_icdf",
    "uniform",
    "cdf",
    "icdf",
    "plotcdf",
    "cdfplot",
    "mgf",
    "kolmogorovd",
    "kolmogorovt",
    "wilcoxons",
    "wilcoxonp",
    "wilcoxont",
    "chisquaret",
    "normalt",
    "studentt",
    "multinomial",
    "randmultinomial",
    "randchisquare",
    "randchisquared",
    "randstudent",
    "randstudentd",
    "randfisher",
    "randfisherd",
    "randexp",
    "randgammad",
    "randbetad",
    "randweibulld",
    "randgeometric",
    "randvector",
    "randmatrix",
    "randMat",
    "random",
    "random_variable",
    "randvar",
    "hasard",
    "srand",
    "randpoly",
    "randPoly",
    "egv",
    "egvl",
    "eigenvals",
    "eigenvalues",
    "eigenvects",
    "eigenvectors",
    "svd",
    "ker",
    "kernel",
    "rank",
    "rat_jordan",
    "rat_jordan_block",
    "pcar_hessenberg",
    "det_minor",
    "basis",
    "image",
    "rref",
    "ref",
    "suvat",
    "projectile",
    "pulley",
    "incline",
    "force",
    "weight",
    "moment",
    "resolve",
    "friction",
]

BEHAVIOR_SAMPLES = [
    "plotparam([cos(t),sin(t)],t)",
    "plotseq(x^2,x=1..5)",
    "paramplot(cos(t),sin(t),t)",
    "seqplot(x^2,x=1..5)",
    "rand()",
    "randint(10)",
    "ranv(5,normald,0,1)",
    "ranm(2,2)",
    "randperm(5)",
    "15 mod 6",
    "irem(23,5)",
    "smod(8,3)",
    "permuorder([2,1,3])",
    "concat([1,2],[3])",
    "extend([1,2],[3])",
    "select(x->x>1,[1,2])",
    "filter(x->x>1,[1,2])",
    "remove(x->x>1,[1,2])",
    "normal_cdf(0,1,0)",
    "normal_icdf(0,1,0.5)",
    "perm(5,2)",
    "sign(-4)",
    "binomial_cdf(10,0.5,3)",
    "binomial_icdf(10,0.5,0.8)",
    "poisson_cdf(4,2)",
    "poisson_icdf(4,0.5)",
    "uniform_cdf(0,1,0.5)",
    "uniform_icdf(0,1,0.5)",
    "randbinomial(10,0.5)",
    "randpoisson(4)",
    "randnormald(0,1)",
    "normalvariate(0,1)",
    "stdDev([1,2,3])",
    "stddevp([1,2,3])",
    "quartile1([1,2,3])",
    "quartile3([1,2,3])",
    "quartiles([1,2,3])",
    "moustache([1,2,3])",
    "histogram([1,2,3])",
    "camembert([1,2,3])",
    "covariance([1,2,3],[1,2,3])",
    "correlation([1,2,3],[1,2,3])",
    "cfactor(x^2+1)",
    "cpartfrac(1/(x^2+1),x)",
    "csolve(x^2+1=0,x)",
    "complex(1,2)",
    "abcuv(x+1,x^2-2,x)",
    "iabcuv(23,13,15)",
    "egcd(x^2+3*x+1,x^2-5*x-1)",
    "iegcd(23,13)",
    "interp([1,2],[3,4])",
    "jordan([[1,2],[3,4]])",
    "JordanBlock(7,3)",
    "gramschmidt([[1,2],[3,4]])",
    "hermite(3)",
    "laguerre(3,0,x)",
    "legendre(3)",
    "tchebyshev1(3)",
    "tchebyshev2(3)",
    "residue(1/(x^2+1),x,i)",
    "resultant(x^2-1,x-1,x)",
    "sinh(x)",
    "asinh(x)",
    "matrix(2,2)",
    "trace([[1,2],[3,4]])",
    "transpose([[1,2],[3,4]])",
    "cholesky([[3,1],[1,4]])",
    "crypto",
    "about()",
    "det([[1,2],[3,4]])",
    "plot(x^2,x,0,1)",
    "plotlist([1,2,3])",
    "plotpolar(theta,theta,0,pi)",
    "fourier_an(x^2,x,2*pi,n,-pi)",
    "fourier_bn(x,x,2*pi,n,-pi)",
    "laplace(x,x,s)",
    "desolve(diff(y(x),x)=y(x),x,y)",
    "odesolve(y,[x,y],[0,1],2)",
    "ilaplace(1/(x^2+1),s,x)",
    "plotode(y,[x,y],[0,1])",
    "plotfield(y,[x,y])",
    "fft([1,2,3,4])",
    "ifft([1,2,3,4])",
    "read(\"session.xw\")",
    "write(\"session.xw\")",
    "charpoly([[1,2],[3,4]])",
    "pcar([[1,2],[3,4]])",
    "gaussjord([[1,2],[3,4]])",
    "pivot([[1,2],[3,4]],1,1)",
    "keep_pivot",
    "minor_det",
    "rational_det",
    "assume(x>0)",
    "asc(\"A\")",
    "char(65)",
    "euler(25)",
    "barplot([1,2,3])",
    "bar_plot([1,2,3])",
    "scatterplot([1,2,3],[1,4,9])",
    "listplot([1,2,3])",
    "polygonplot([[1,2],[3,4]])",
    "polygonscatterplot([[1,2],[3,4]])",
    "halftan(cos(x))",
    "halftan_hyp2exp(cos(x))",
    "exp2trig(exp(i*x))",
    "trig2exp(cos(x))",
    "evalc(1/(1+i))",
    "mult_c_conjugate(1+2*i)",
    "q2a(x^2+3*x*y,[x,y])",
    "a2q([[1,2],[2,3]],[x,y])",
    "turtle()",
    "denom(3/4)",
    "numer(3/4)",
    "comDenom([1/x,1/(x+1)])",
    "getDenom(3/4)",
    "curl([2*x*y,x*z,y*z],[x,y,z])",
    "ichinrem([3,13],[2,7])",
    "iquorem(23,5)",
    "conj(1+i)",
    "re(1+i)",
    "im(1+i)",
    "plotarea(x^2,x=0..1)",
    "plotfunc(x^2,[x,y])",
    "funcplot(x^2,x)",
    "plotdensity(x*y,[x,y])",
    "plotmatrix([[1,2],[3,4]])",
    "densityplot(x*y,[x,y])",
    "graphe(x^2)",
    "paramplot([cos(t),sin(t)],t)",
    "plotpolar(sin(t),t)",
    "polarplot(sin(t),t)",
    "courbe_polaire(sin(t),t)",
    "plotimplicit(x^2+y^2=1,x,y)",
    "implicitplot(x^2+y^2=1,x,y)",
    "conic(x^2+y^2=1)",
    "quadric(x^2+y^2+z^2=1)",
    "reduced_conic(x^2+y^2=1)",
    "reduced_quadric(x^2+y^2+z^2=1)",
    "point(1,2)",
    "point2d(A)",
    "point3d(A)",
    "polar_point(1,pi/4)",
    "line(y=x)",
    "half_line(0,1)",
    "line_inter(line(0,1),line(i,1+i))",
    "single_inter(line(0,1),line(i,1+i))",
    "segment(0,1)",
    "circle(0,1)",
    "bitmap([1,0])",
    "bezier(0,1,1+i)",
    "animation([point(0),point(1)])",
    "hyperplan([1,0,0],[0,0,0])",
    "hypersphere([0,0,0],1)",
    "hypersurface(x+y+z,[x,y,z])",
    "frame_3d()",
    "plot3d(x^2+y^2,x,y)",
    "graphe3d(x^2+y^2,x,y)",
    "plotinequation(x+y>0)",
    "inequationplot(x+y>0)",
    "envelope(y+x*tan(t),t)",
    "locus(point(0),point(1))",
    "linetan(sin(x),x,0)",
    "tabvar(x^2,x)",
    "gl_x=0..2",
    "gl_y=-1..1",
    "draw_circle(10,10,5,red)",
    "draw_line(0,0,1,1)",
    "set_pixel(1,1)",
    "cone([0,0,0],[0,0,1],pi/6)",
    "cube([0,0,0],[1,0,0],[0,1,0])",
    "cylinder([0,0,0],[0,1,0],2)",
    "dodecahedron([0,0,0],[0,2,sqrt(5)/2+3/2],[0,0,1])",
    "icosahedron([0,0,0],[sqrt(5),0,0],[1,2,0])",
    "octahedron([0,0,0],[1,0,0],[0,1,0])",
    "plane(x+y+z=0)",
    "sphere([0,0,0],1)",
    "tetrahedron([0,0,0],[1,0,0],[0,1,0])",
    "volume(cube([0,0,0],[1,0,0],[0,1,0]))",
    "python_compat(1)",
    "program()",
    "bloc(1,2)",
    "ifte(1,2,3)",
    "for(i:=1,i<3,i:=i+1,i)",
    "while(1,1)",
    "local(x,1)",
    "return(1)",
    "try_catch(1,e,2)",
    "throw(\"x\")",
    "break()",
    "continue()",
    "inputform(1)",
    "choosebox(1)",
    "output(1)",
    "input(x)",
    "Dialog(1)",
    "Pause(1)",
    "sleep(1)",
    "execute(\"1+1\")",
    "numpy()",
    "pylab()",
    "matplotlib()",
    "exponentiald(2,3)",
    "exponential(2,3)",
    "exponential_cdf(2,3)",
    "exponential_icdf(2,0.5)",
    "betad(1,1,0.5)",
    "cauchyd(0,1,0)",
    "cauchy(0,1,0)",
    "cauchy_cdf(0,1,0)",
    "cauchy_icdf(0,1,0.5)",
    "gammad(2,3)",
    "geometric(0.2,3)",
    "weibulld(2,1,0,3)",
    "weibull(2,1,0,3)",
    "weibull_cdf(2,1,0,3)",
    "weibull_icdf(2,1,0.5)",
    "student(2,0)",
    "student_cdf(2,0)",
    "student_icdf(2,0.5)",
    "chisquare(2,1)",
    "chisquare_cdf(2,1)",
    "chisquare_icdf(2,0.5)",
    "fisher(2,3,1)",
    "fisher_cdf(2,3,1)",
    "fisher_icdf(2,3,0.5)",
    "snedecor(2,3,1)",
    "snedecor_cdf(2,3,1)",
    "snedecor_icdf(2,3,0.5)",
    "uniform(0,1,0.5)",
    "cdf([1,2,3])",
    "icdf(normald(0,1),0.5)",
    "plotcdf([1,2,3])",
    "mgf(normald(0,1))",
    "kolmogorovd(1)",
    "kolmogorovt([1,2],[1,3])",
    "wilcoxons([1,2,3],0)",
    "wilcoxonp(3)",
    "wilcoxont([1,2,3],0)",
    "chisquaret([1,2,3],[0.2,0.3,0.5])",
    "normalt([1,2,3],0,1,>)",
    "studentt([1,2,3],0,>)",
    "multinomial(10,[0.5,0.5],[3,7])",
    "randmultinomial([0.5,0.5])",
    "randchisquare(2)",
    "randstudent(2)",
    "randfisher(2,3)",
    "randexp(2)",
    "randgammad(2,3)",
    "randbetad(2,3)",
    "randweibulld(2,3)",
    "randgeometric(0.2)",
    "randvector(3,normald,0,1)",
    "randmatrix(2,2)",
    "random(3)",
    "random_variable(normald,0,1)",
    "randvar(normald,0,1)",
    "hasard(3)",
    "srand(1)",
    "randpoly(3)",
    "egv([[1,0],[0,2]])",
    "egvl([[1,0],[0,2]])",
    "eigenvals([[1,0],[0,2]])",
    "eigenvalues([[1,0],[0,2]])",
    "eigenvects([[1,0],[0,2]])",
    "eigenvectors([[1,0],[0,2]])",
    "svd([[1,2],[3,4]])",
    "ker([[1,2],[2,4]])",
    "kernel([[1,2],[2,4]])",
    "rank([[1,2],[2,4]])",
    "rat_jordan([[0,1],[-2,3]])",
    "rat_jordan_block(x^2-3*x+2,x,2)",
    "pcar_hessenberg([[1,2],[3,4]])",
    "det_minor([[1,2],[3,4]])",
    "basis([[1,2],[2,4]])",
    "image([[1,2],[2,4]])",
    "rref([[1,2],[2,4]])",
    "ref([[1,2],[2,4]])",
    "suvat(u=3,a=2,t=4)",
    "projectile(20,30,2)",
    "pulley(4,2)",
    "incline(5,30)",
    "force(2,3)",
    "weight(4)",
    "moment(10,2)",
    "resolve(10,30)",
    "friction(0.2,40)",
]

BINARY_ABSENT = [
    "halftan",
    "halftan_hyp2exp",
    "exp2trig",
    "trig2exp",
    "evalc",
    "mult_c_conjugate",
    "q2a",
    "a2q",
    "turtle",
    "denom",
    "numer",
    "comDenom",
    "getDenom",
    "curl",
    "ichinrem",
    "iquorem",
    "plotlist",
    "plotparam",
    "plotpolar",
    "plotseq",
    "paramplot",
    "seqplot",
    "funcplot",
    "plotdensity",
    "plotmatrix",
    "densityplot",
    "graphe",
    "polarplot",
    "courbe_polaire",
    "plotimplicit",
    "implicitplot",
    "conic",
    "quadric",
    "reduced_conic",
    "reduced_quadric",
    "plotarea",
    "plotfunc",
    "plotcontour",
    "point2d",
    "point3d",
    "polar_point",
    "half_line",
    "line_inter",
    "single_inter",
    "bitmap",
    "bezier",
    "animation",
    "hyperplan",
    "hypersphere",
    "hypersurface",
    "frame_3d",
    "plot3d",
    "graphe3d",
    "plotinequation",
    "inequationplot",
    "envelope",
    "locus",
    "linetan",
    "tabvar",
    "gl_x",
    "gl_y",
    "plotode",
    "plotfield",
    "Unsupported plot feature",
    "Function plot",
    "Parametric plot",
    "parametric plot",
    "plots|conic",
    "Program mode removed",
    "Xcas syntax",
    "Source en syntaxe Xcas",
    "Graphic object",
    "graphic objects",
    "ilaplace",
    "irem",
    "smod",
    "barplot",
    "scatterplot",
    "matplotlib",
    "matplotx",
    "pylab",
    "numpy",
    "turtlex",
    "crypto",
    "replaced randomly",
    "cone",
    "cube",
    "cylinder",
    "dodecahedron",
    "icosahedron",
    "octahedron",
    "plane",
    "sphere",
    "tetrahedron",
    "volume",
    "multinomial",
    "randmultinomial",
    "basis",
    "image",
    "kernel",
    "rref",
    "keep_pivot",
    "minor_det",
    "rational_det",
]

STATIC_ENTRY_ABSENT = [
    "matrix",
    "det",
    "det_minor",
    "rank",
    "trace",
    "transpose",
    "cholesky",
    "rref",
    "ref",
    "gaussjord",
    "pivot",
    "keep_pivot",
    "charpoly",
    "pcar",
    "pcar_hessenberg",
    "gramschmidt",
    "jordan",
    "JordanBlock",
    "rat_jordan",
    "ranm",
    "ker",
    "kernel",
    "image",
    "basis",
    "svd",
    "egv",
    "egvl",
    "eigenvals",
    "eigenvects",
    "eigenvalues",
    "eigenvectors",
    "about",
    "egcd",
    "interp",
    "laplace",
    "plot",
    "python",
    "random",
    "resultant",
    "complex",
    "funcplot",
    "plotdensity",
    "plotmatrix",
    "densityplot",
    "graphe",
    "polarplot",
    "courbe_polaire",
    "plotimplicit",
    "implicitplot",
    "conic",
    "quadric",
    "reduced_conic",
    "reduced_quadric",
    "point2d",
    "point3d",
    "half_line",
    "polar_point",
    "line_inter",
    "single_inter",
    "bezier",
    "animation",
    "hyperplan",
    "hypersphere",
    "hypersurface",
    "frame_3d",
    "plot3d",
    "graphe3d",
    "plotinequation",
    "inequationplot",
    "envelope",
    "locus",
]


def fail(msg: str) -> None:
    raise SystemExit(f"FAIL removed-features: {msg}")


def word_hit(text: str, name: str) -> bool:
    call_only = {
        "plot",
        "rand",
        "det",
        "program",
        "bloc",
        "ifte",
        "for",
        "while",
        "local",
        "return",
        "try_catch",
        "throw",
        "break",
        "continue",
        "inputform",
        "choosebox",
        "output",
        "input",
        "dialog",
        "pause",
        "sleep",
        "execute",
    }
    if name in call_only:
        return re.search(rf'(?<![A-Za-z0-9_]){re.escape(name)}\s*\(', text) is not None
    return re.search(rf'(?<![A-Za-z0-9_]){re.escape(name)}(?![A-Za-z0-9_])', text) is not None


def fnv1a32(text: str) -> str:
    value = 2166136261
    for ch in text:
        value ^= ord(ch)
        value = (value * 16777619) & 0xFFFFFFFF
    return f"0x{value:08x}u"


def main() -> int:
    main_cc = (SRC / "main.cc").read_text(errors="ignore")
    if "cascas_reject_removed_feature" not in main_cc:
        fail("main.cc missing runtime reject hook")
    if "Err: unsupported (not A-level scope)" not in main_cc:
        fail("missing canonical unsupported message")

    for name in REMOVED:
        marker = f'"{name}"'
        hashed = fnv1a32(name)
        if marker not in main_cc and hashed not in main_cc:
            fail(f"main.cc denylist missing {name}")

    leaks: list[str] = []
    for rel in ["catalogen.cpp", "catalogfr.cpp"]:
        text = (SRC / rel).read_text(errors="ignore")
        for raw in re.findall(r'\{\s*"([^"]+)"', text):
            entry = raw.split("(", 1)[0].strip().lower()
            for name in REMOVED:
                if entry == name:
                    leaks.append(f"{rel}:{name}")
    help_dir = ROOT / "help/functions"
    for p in help_dir.glob("*.txt"):
        stem = p.stem.lower()
        if stem in REMOVED:
            leaks.append(f"help/functions/{p.name}")
        text = p.read_text(errors="ignore").lower()
        for name in REMOVED:
            if word_hit(text, name):
                leaks.append(f"help/functions/{p.name}:{name}")
                break
    if leaks:
        fail("public leaks " + ", ".join(leaks[:20]))

    static_leaks: list[str] = []
    static_files = list(SRC.glob("static_help*.h")) + [
        SRC / "helpfr.cc",
        SRC / "static_lexer.h",
        SRC / "static_lexer_full.h",
    ]
    for p in static_files:
        text = p.read_text(errors="ignore")
        for name in STATIC_ENTRY_ABSENT:
            if re.search(rf'\{{\s*"{re.escape(name)}"\s*,', text):
                static_leaks.append(f"{p.name}:{name}")
    if static_leaks:
        fail("static entry leaks " + ", ".join(static_leaks[:20]))

    for expr in BEHAVIOR_SAMPLES:
        proc = subprocess.run([str(RUNNER), expr], cwd=ROOT, text=True, capture_output=True)
        out = (proc.stdout or "") + (proc.stderr or "")
        if "unsupported" not in out.lower():
            fail(f"host runner did not reject {expr}: {out[:120]!r}")

    g3a = ROOT / "calculator_files/CasioCAS.g3a"
    if g3a.exists():
        proc = subprocess.run(["strings", str(g3a)], cwd=ROOT, text=True, capture_output=True)
        strings_text = proc.stdout or ""
        for name in BINARY_ABSENT:
            if re.search(rf'(?<![A-Za-z0-9_]){re.escape(name)}(?![A-Za-z0-9_])', strings_text):
                fail(f"binary leaks public token {name}")

    print(f"OK removed features hidden/rejected count={len(REMOVED)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
