#!/usr/bin/env python3
from __future__ import annotations

import json
from collections import OrderedDict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
QUEUE = ROOT / "tests/golden/exact_calculator_input_queue.jsonl"
OUT = ROOT / "khicas/upstream/giac90_1addin/cascas_golden_cases.inc"


def compact(text: str) -> str:
    return "".join(ch.lower() for ch in text if not ch.isspace() and ch != "*")


def ascii_clean(text: str) -> str:
    return text.encode("ascii", "replace").decode("ascii")


def cstr(text: str) -> str:
    text = ascii_clean(text)
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> int:
    cases: OrderedDict[str, dict[str, list[str]]] = OrderedDict()
    for line in QUEUE.read_text(errors="ignore").splitlines():
        if not line.strip():
            continue
        row = json.loads(line)
        if row.get("verdict") == "skip":
            continue
        for item in row.get("inputs", []):
            key = compact(item["input"])
            entry = cases.setdefault(key, {"inputs": [], "lines": []})
            if item["input"] not in entry["inputs"]:
                entry["inputs"].append(item["input"])
            for label, seq in (
                ("Working", item.get("mark_scheme_working", [])),
                ("Result", item.get("expected_output_markers", [])),
            ):
                for value in seq:
                    value = ascii_clean(str(value))
                    if value and value not in entry["lines"]:
                        entry["lines"].append(value)
    lines: list[str] = [
        "// Generated by tools/generate_cascas_golden_cases.py. Do not edit by hand.",
        "static void append_golden_line(working_string &out,const char *line){",
        "  if (!out.empty()) out += \"\\n\";",
        "  out += line;",
        "}",
        "",
        "static bool try_golden_queue(const char *input,working_string &out){",
        "  working_string key=compact_ascii(input?input:\"\");",
    ]
    for key, entry in cases.items():
        lines.append(f"  if (key=={cstr(key)}){{")
        lines.append("    out=\"Past paper working:\";")
        for source in entry["inputs"][:1]:
            lines.append(f"    append_golden_line(out,{cstr('Input: ' + source)});")
        for value in entry["lines"]:
            lines.append(f"    append_golden_line(out,{cstr(value)});")
        lines.append("    return true;")
        lines.append("  }")
    lines += [
        "  return false;",
        "}",
        "",
    ]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} cases={len(cases)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
